// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anime.sql

package store

import (
	"context"
	"database/sql"
)

const createAnime = `-- name: CreateAnime :one
INSERT INTO anime (id, library_id, title, title_zh, title_en, synopsis, cover_image_url,
    total_episodes, status, air_date, year, season, genres, bangumi_id, dandanplay_bangumi_id,
    watch_status, score,
    created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?,
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
RETURNING id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at, user_score, score, anidb_id, sync_disabled, watch_status_override, trakt_show_id
`

type CreateAnimeParams struct {
	ID                  string         `json:"id"`
	LibraryID           sql.NullString `json:"library_id"`
	Title               string         `json:"title"`
	TitleZh             sql.NullString `json:"title_zh"`
	TitleEn             sql.NullString `json:"title_en"`
	Synopsis            sql.NullString `json:"synopsis"`
	CoverImageUrl       sql.NullString `json:"cover_image_url"`
	TotalEpisodes       sql.NullInt64  `json:"total_episodes"`
	Status              string         `json:"status"`
	AirDate             sql.NullString `json:"air_date"`
	Year                sql.NullInt64  `json:"year"`
	Season              sql.NullString `json:"season"`
	Genres              string         `json:"genres"`
	BangumiID           sql.NullInt64  `json:"bangumi_id"`
	DandanplayBangumiID sql.NullInt64  `json:"dandanplay_bangumi_id"`
	WatchStatus         string         `json:"watch_status"`
	Score               float64        `json:"score"`
}

func (q *Queries) CreateAnime(ctx context.Context, arg CreateAnimeParams) (Anime, error) {
	row := q.db.QueryRowContext(ctx, createAnime,
		arg.ID,
		arg.LibraryID,
		arg.Title,
		arg.TitleZh,
		arg.TitleEn,
		arg.Synopsis,
		arg.CoverImageUrl,
		arg.TotalEpisodes,
		arg.Status,
		arg.AirDate,
		arg.Year,
		arg.Season,
		arg.Genres,
		arg.BangumiID,
		arg.DandanplayBangumiID,
		arg.WatchStatus,
		arg.Score,
	)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.TitleZh,
		&i.TitleEn,
		&i.Synopsis,
		&i.CoverImageUrl,
		&i.TotalEpisodes,
		&i.Status,
		&i.AirDate,
		&i.Year,
		&i.Season,
		&i.Genres,
		&i.IsCustom,
		&i.AnilistID,
		&i.BangumiID,
		&i.DandanplayBangumiID,
		&i.MalID,
		&i.TmdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WatchStatus,
		&i.WatchStatusUpdatedAt,
		&i.UserScore,
		&i.Score,
		&i.AnidbID,
		&i.SyncDisabled,
		&i.WatchStatusOverride,
		&i.TraktShowID,
	)
	return i, err
}

const deleteAnime = `-- name: DeleteAnime :exec
DELETE FROM anime WHERE id = ?
`

func (q *Queries) DeleteAnime(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAnime, id)
	return err
}

const deleteEpisodesByAnimeID = `-- name: DeleteEpisodesByAnimeID :exec
DELETE FROM episodes WHERE anime_id = ?
`

func (q *Queries) DeleteEpisodesByAnimeID(ctx context.Context, animeID string) error {
	_, err := q.db.ExecContext(ctx, deleteEpisodesByAnimeID, animeID)
	return err
}

const getAnime = `-- name: GetAnime :one
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at, user_score, score, anidb_id, sync_disabled, watch_status_override, trakt_show_id FROM anime WHERE id = ? LIMIT 1
`

func (q *Queries) GetAnime(ctx context.Context, id string) (Anime, error) {
	row := q.db.QueryRowContext(ctx, getAnime, id)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.TitleZh,
		&i.TitleEn,
		&i.Synopsis,
		&i.CoverImageUrl,
		&i.TotalEpisodes,
		&i.Status,
		&i.AirDate,
		&i.Year,
		&i.Season,
		&i.Genres,
		&i.IsCustom,
		&i.AnilistID,
		&i.BangumiID,
		&i.DandanplayBangumiID,
		&i.MalID,
		&i.TmdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WatchStatus,
		&i.WatchStatusUpdatedAt,
		&i.UserScore,
		&i.Score,
		&i.AnidbID,
		&i.SyncDisabled,
		&i.WatchStatusOverride,
		&i.TraktShowID,
	)
	return i, err
}

const getAnimeByAnidbID = `-- name: GetAnimeByAnidbID :one
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at, user_score, score, anidb_id, sync_disabled, watch_status_override, trakt_show_id FROM anime WHERE anidb_id = ? LIMIT 1
`

func (q *Queries) GetAnimeByAnidbID(ctx context.Context, anidbID sql.NullInt64) (Anime, error) {
	row := q.db.QueryRowContext(ctx, getAnimeByAnidbID, anidbID)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.TitleZh,
		&i.TitleEn,
		&i.Synopsis,
		&i.CoverImageUrl,
		&i.TotalEpisodes,
		&i.Status,
		&i.AirDate,
		&i.Year,
		&i.Season,
		&i.Genres,
		&i.IsCustom,
		&i.AnilistID,
		&i.BangumiID,
		&i.DandanplayBangumiID,
		&i.MalID,
		&i.TmdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WatchStatus,
		&i.WatchStatusUpdatedAt,
		&i.UserScore,
		&i.Score,
		&i.AnidbID,
		&i.SyncDisabled,
		&i.WatchStatusOverride,
		&i.TraktShowID,
	)
	return i, err
}

const getAnimeByAnilistID = `-- name: GetAnimeByAnilistID :one
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at, user_score, score, anidb_id, sync_disabled, watch_status_override, trakt_show_id FROM anime WHERE anilist_id = ? LIMIT 1
`

func (q *Queries) GetAnimeByAnilistID(ctx context.Context, anilistID sql.NullInt64) (Anime, error) {
	row := q.db.QueryRowContext(ctx, getAnimeByAnilistID, anilistID)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.TitleZh,
		&i.TitleEn,
		&i.Synopsis,
		&i.CoverImageUrl,
		&i.TotalEpisodes,
		&i.Status,
		&i.AirDate,
		&i.Year,
		&i.Season,
		&i.Genres,
		&i.IsCustom,
		&i.AnilistID,
		&i.BangumiID,
		&i.DandanplayBangumiID,
		&i.MalID,
		&i.TmdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WatchStatus,
		&i.WatchStatusUpdatedAt,
		&i.UserScore,
		&i.Score,
		&i.AnidbID,
		&i.SyncDisabled,
		&i.WatchStatusOverride,
		&i.TraktShowID,
	)
	return i, err
}

const getAnimeByBangumiID = `-- name: GetAnimeByBangumiID :one
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at, user_score, score, anidb_id, sync_disabled, watch_status_override, trakt_show_id FROM anime WHERE bangumi_id = ? LIMIT 1
`

func (q *Queries) GetAnimeByBangumiID(ctx context.Context, bangumiID sql.NullInt64) (Anime, error) {
	row := q.db.QueryRowContext(ctx, getAnimeByBangumiID, bangumiID)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.TitleZh,
		&i.TitleEn,
		&i.Synopsis,
		&i.CoverImageUrl,
		&i.TotalEpisodes,
		&i.Status,
		&i.AirDate,
		&i.Year,
		&i.Season,
		&i.Genres,
		&i.IsCustom,
		&i.AnilistID,
		&i.BangumiID,
		&i.DandanplayBangumiID,
		&i.MalID,
		&i.TmdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WatchStatus,
		&i.WatchStatusUpdatedAt,
		&i.UserScore,
		&i.Score,
		&i.AnidbID,
		&i.SyncDisabled,
		&i.WatchStatusOverride,
		&i.TraktShowID,
	)
	return i, err
}

const getAnimeByTMDBID = `-- name: GetAnimeByTMDBID :one
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at, user_score, score, anidb_id, sync_disabled, watch_status_override, trakt_show_id FROM anime WHERE tmdb_id = ? LIMIT 1
`

func (q *Queries) GetAnimeByTMDBID(ctx context.Context, tmdbID sql.NullInt64) (Anime, error) {
	row := q.db.QueryRowContext(ctx, getAnimeByTMDBID, tmdbID)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.TitleZh,
		&i.TitleEn,
		&i.Synopsis,
		&i.CoverImageUrl,
		&i.TotalEpisodes,
		&i.Status,
		&i.AirDate,
		&i.Year,
		&i.Season,
		&i.Genres,
		&i.IsCustom,
		&i.AnilistID,
		&i.BangumiID,
		&i.DandanplayBangumiID,
		&i.MalID,
		&i.TmdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WatchStatus,
		&i.WatchStatusUpdatedAt,
		&i.UserScore,
		&i.Score,
		&i.AnidbID,
		&i.SyncDisabled,
		&i.WatchStatusOverride,
		&i.TraktShowID,
	)
	return i, err
}

const getAnimeByTraktShowID = `-- name: GetAnimeByTraktShowID :one
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at, user_score, score, anidb_id, sync_disabled, watch_status_override, trakt_show_id FROM anime WHERE trakt_show_id = ? LIMIT 1
`

func (q *Queries) GetAnimeByTraktShowID(ctx context.Context, traktShowID sql.NullInt64) (Anime, error) {
	row := q.db.QueryRowContext(ctx, getAnimeByTraktShowID, traktShowID)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.TitleZh,
		&i.TitleEn,
		&i.Synopsis,
		&i.CoverImageUrl,
		&i.TotalEpisodes,
		&i.Status,
		&i.AirDate,
		&i.Year,
		&i.Season,
		&i.Genres,
		&i.IsCustom,
		&i.AnilistID,
		&i.BangumiID,
		&i.DandanplayBangumiID,
		&i.MalID,
		&i.TmdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WatchStatus,
		&i.WatchStatusUpdatedAt,
		&i.UserScore,
		&i.Score,
		&i.AnidbID,
		&i.SyncDisabled,
		&i.WatchStatusOverride,
		&i.TraktShowID,
	)
	return i, err
}

const listAnimeByLibrary = `-- name: ListAnimeByLibrary :many
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at, user_score, score, anidb_id, sync_disabled, watch_status_override, trakt_show_id FROM anime WHERE library_id = ?
`

func (q *Queries) ListAnimeByLibrary(ctx context.Context, libraryID sql.NullString) ([]Anime, error) {
	rows, err := q.db.QueryContext(ctx, listAnimeByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Anime{}
	for rows.Next() {
		var i Anime
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.TitleZh,
			&i.TitleEn,
			&i.Synopsis,
			&i.CoverImageUrl,
			&i.TotalEpisodes,
			&i.Status,
			&i.AirDate,
			&i.Year,
			&i.Season,
			&i.Genres,
			&i.IsCustom,
			&i.AnilistID,
			&i.BangumiID,
			&i.DandanplayBangumiID,
			&i.MalID,
			&i.TmdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WatchStatus,
			&i.WatchStatusUpdatedAt,
			&i.UserScore,
			&i.Score,
			&i.AnidbID,
			&i.SyncDisabled,
			&i.WatchStatusOverride,
			&i.TraktShowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnimeByLibraryID = `-- name: ListAnimeByLibraryID :many
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at, user_score, score, anidb_id, sync_disabled, watch_status_override, trakt_show_id FROM anime WHERE library_id = ? ORDER BY title
`

func (q *Queries) ListAnimeByLibraryID(ctx context.Context, libraryID sql.NullString) ([]Anime, error) {
	rows, err := q.db.QueryContext(ctx, listAnimeByLibraryID, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Anime{}
	for rows.Next() {
		var i Anime
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.TitleZh,
			&i.TitleEn,
			&i.Synopsis,
			&i.CoverImageUrl,
			&i.TotalEpisodes,
			&i.Status,
			&i.AirDate,
			&i.Year,
			&i.Season,
			&i.Genres,
			&i.IsCustom,
			&i.AnilistID,
			&i.BangumiID,
			&i.DandanplayBangumiID,
			&i.MalID,
			&i.TmdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WatchStatus,
			&i.WatchStatusUpdatedAt,
			&i.UserScore,
			&i.Score,
			&i.AnidbID,
			&i.SyncDisabled,
			&i.WatchStatusOverride,
			&i.TraktShowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnimeForUserWithProviderID = `-- name: ListAnimeForUserWithProviderID :many
SELECT DISTINCT a.id, a.library_id, a.title, a.title_zh, a.title_en, a.synopsis, a.cover_image_url, a.total_episodes, a.status, a.air_date, a.year, a.season, a.genres, a.is_custom, a.anilist_id, a.bangumi_id, a.dandanplay_bangumi_id, a.mal_id, a.tmdb_id, a.created_at, a.updated_at, a.watch_status, a.watch_status_updated_at, a.user_score, a.score, a.anidb_id, a.sync_disabled, a.watch_status_override, a.trakt_show_id FROM anime a
JOIN episodes e ON e.anime_id = a.id
JOIN watch_progress wp ON wp.episode_id = e.id
WHERE wp.user_id = ?1
  AND wp.completed = 1
  AND ( (?2 = 'anilist' AND a.anilist_id IS NOT NULL)
     OR (?2 = 'bangumi' AND a.bangumi_id IS NOT NULL) )
  AND a.sync_disabled = 0
`

type ListAnimeForUserWithProviderIDParams struct {
	UserID   string      `json:"user_id"`
	Provider interface{} `json:"provider"`
}

// A5 fix: only animes with at least one completed watch_progress episode.
func (q *Queries) ListAnimeForUserWithProviderID(ctx context.Context, arg ListAnimeForUserWithProviderIDParams) ([]Anime, error) {
	rows, err := q.db.QueryContext(ctx, listAnimeForUserWithProviderID, arg.UserID, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Anime{}
	for rows.Next() {
		var i Anime
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.TitleZh,
			&i.TitleEn,
			&i.Synopsis,
			&i.CoverImageUrl,
			&i.TotalEpisodes,
			&i.Status,
			&i.AirDate,
			&i.Year,
			&i.Season,
			&i.Genres,
			&i.IsCustom,
			&i.AnilistID,
			&i.BangumiID,
			&i.DandanplayBangumiID,
			&i.MalID,
			&i.TmdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WatchStatus,
			&i.WatchStatusUpdatedAt,
			&i.UserScore,
			&i.Score,
			&i.AnidbID,
			&i.SyncDisabled,
			&i.WatchStatusOverride,
			&i.TraktShowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkMediaFilesByAnimeID = `-- name: UnlinkMediaFilesByAnimeID :exec
UPDATE media_files SET episode_id = NULL, match_status = 'unmatched'
WHERE episode_id IN (SELECT id FROM episodes WHERE anime_id = ?)
`

func (q *Queries) UnlinkMediaFilesByAnimeID(ctx context.Context, animeID string) error {
	_, err := q.db.ExecContext(ctx, unlinkMediaFilesByAnimeID, animeID)
	return err
}

const updateAnimeExternalIDs = `-- name: UpdateAnimeExternalIDs :exec
UPDATE anime SET
    anidb_id   = COALESCE(anidb_id,   ?1),
    anilist_id = COALESCE(anilist_id, ?2),
    bangumi_id = COALESCE(bangumi_id, ?3),
    mal_id     = COALESCE(mal_id,     ?4),
    tmdb_id    = COALESCE(tmdb_id,    ?5),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?6
`

type UpdateAnimeExternalIDsParams struct {
	AnidbID   sql.NullInt64 `json:"anidb_id"`
	AnilistID sql.NullInt64 `json:"anilist_id"`
	BangumiID sql.NullInt64 `json:"bangumi_id"`
	MalID     sql.NullInt64 `json:"mal_id"`
	TmdbID    sql.NullInt64 `json:"tmdb_id"`
	ID        string        `json:"id"`
}

// Fills only NULL columns; never overwrites an existing value.
func (q *Queries) UpdateAnimeExternalIDs(ctx context.Context, arg UpdateAnimeExternalIDsParams) error {
	_, err := q.db.ExecContext(ctx, updateAnimeExternalIDs,
		arg.AnidbID,
		arg.AnilistID,
		arg.BangumiID,
		arg.MalID,
		arg.TmdbID,
		arg.ID,
	)
	return err
}

const updateAnimeLibraryID = `-- name: UpdateAnimeLibraryID :exec
UPDATE anime SET library_id = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateAnimeLibraryIDParams struct {
	LibraryID sql.NullString `json:"library_id"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateAnimeLibraryID(ctx context.Context, arg UpdateAnimeLibraryIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAnimeLibraryID, arg.LibraryID, arg.ID)
	return err
}

const updateAnimeScore = `-- name: UpdateAnimeScore :exec
UPDATE anime SET score = ?1, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE bangumi_id = ?2 AND (score = 0 OR score != ?1)
`

type UpdateAnimeScoreParams struct {
	Score     float64       `json:"score"`
	BangumiID sql.NullInt64 `json:"bangumi_id"`
}

func (q *Queries) UpdateAnimeScore(ctx context.Context, arg UpdateAnimeScoreParams) error {
	_, err := q.db.ExecContext(ctx, updateAnimeScore, arg.Score, arg.BangumiID)
	return err
}

const updateAnimeSyncFlags = `-- name: UpdateAnimeSyncFlags :exec
UPDATE anime
SET sync_disabled = ?1,
    watch_status_override = ?2,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?3
`

type UpdateAnimeSyncFlagsParams struct {
	SyncDisabled        int64  `json:"sync_disabled"`
	WatchStatusOverride string `json:"watch_status_override"`
	ID                  string `json:"id"`
}

func (q *Queries) UpdateAnimeSyncFlags(ctx context.Context, arg UpdateAnimeSyncFlagsParams) error {
	_, err := q.db.ExecContext(ctx, updateAnimeSyncFlags, arg.SyncDisabled, arg.WatchStatusOverride, arg.ID)
	return err
}

const updateAnimeTMDBID = `-- name: UpdateAnimeTMDBID :exec
UPDATE anime SET tmdb_id = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateAnimeTMDBIDParams struct {
	TmdbID sql.NullInt64 `json:"tmdb_id"`
	ID     string        `json:"id"`
}

func (q *Queries) UpdateAnimeTMDBID(ctx context.Context, arg UpdateAnimeTMDBIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAnimeTMDBID, arg.TmdbID, arg.ID)
	return err
}

const updateAnimeTraktShowID = `-- name: UpdateAnimeTraktShowID :exec
UPDATE anime SET trakt_show_id = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
`

type UpdateAnimeTraktShowIDParams struct {
	TraktShowID sql.NullInt64 `json:"trakt_show_id"`
	ID          string        `json:"id"`
}

func (q *Queries) UpdateAnimeTraktShowID(ctx context.Context, arg UpdateAnimeTraktShowIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAnimeTraktShowID, arg.TraktShowID, arg.ID)
	return err
}

const updateAnimeUserScore = `-- name: UpdateAnimeUserScore :exec
UPDATE anime SET user_score = ?1, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE bangumi_id = ?2
`

type UpdateAnimeUserScoreParams struct {
	UserScore sql.NullInt64 `json:"user_score"`
	BangumiID sql.NullInt64 `json:"bangumi_id"`
}

func (q *Queries) UpdateAnimeUserScore(ctx context.Context, arg UpdateAnimeUserScoreParams) error {
	_, err := q.db.ExecContext(ctx, updateAnimeUserScore, arg.UserScore, arg.BangumiID)
	return err
}
