// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anime.sql

package store

import (
	"context"
	"database/sql"
)

const createAnime = `-- name: CreateAnime :one
INSERT INTO anime (id, library_id, title, title_zh, title_en, synopsis, cover_image_url,
    total_episodes, status, air_date, year, season, genres, bangumi_id, dandanplay_bangumi_id,
    created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
RETURNING id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at
`

type CreateAnimeParams struct {
	ID                  string         `json:"id"`
	LibraryID           sql.NullString `json:"library_id"`
	Title               string         `json:"title"`
	TitleZh             sql.NullString `json:"title_zh"`
	TitleEn             sql.NullString `json:"title_en"`
	Synopsis            sql.NullString `json:"synopsis"`
	CoverImageUrl       sql.NullString `json:"cover_image_url"`
	TotalEpisodes       sql.NullInt64  `json:"total_episodes"`
	Status              string         `json:"status"`
	AirDate             sql.NullString `json:"air_date"`
	Year                sql.NullInt64  `json:"year"`
	Season              sql.NullString `json:"season"`
	Genres              string         `json:"genres"`
	BangumiID           sql.NullInt64  `json:"bangumi_id"`
	DandanplayBangumiID sql.NullInt64  `json:"dandanplay_bangumi_id"`
}

func (q *Queries) CreateAnime(ctx context.Context, arg CreateAnimeParams) (Anime, error) {
	row := q.db.QueryRowContext(ctx, createAnime,
		arg.ID,
		arg.LibraryID,
		arg.Title,
		arg.TitleZh,
		arg.TitleEn,
		arg.Synopsis,
		arg.CoverImageUrl,
		arg.TotalEpisodes,
		arg.Status,
		arg.AirDate,
		arg.Year,
		arg.Season,
		arg.Genres,
		arg.BangumiID,
		arg.DandanplayBangumiID,
	)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.TitleZh,
		&i.TitleEn,
		&i.Synopsis,
		&i.CoverImageUrl,
		&i.TotalEpisodes,
		&i.Status,
		&i.AirDate,
		&i.Year,
		&i.Season,
		&i.Genres,
		&i.IsCustom,
		&i.AnilistID,
		&i.BangumiID,
		&i.DandanplayBangumiID,
		&i.MalID,
		&i.TmdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WatchStatus,
		&i.WatchStatusUpdatedAt,
	)
	return i, err
}

const getAnime = `-- name: GetAnime :one
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at FROM anime WHERE id = ? LIMIT 1
`

func (q *Queries) GetAnime(ctx context.Context, id string) (Anime, error) {
	row := q.db.QueryRowContext(ctx, getAnime, id)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.TitleZh,
		&i.TitleEn,
		&i.Synopsis,
		&i.CoverImageUrl,
		&i.TotalEpisodes,
		&i.Status,
		&i.AirDate,
		&i.Year,
		&i.Season,
		&i.Genres,
		&i.IsCustom,
		&i.AnilistID,
		&i.BangumiID,
		&i.DandanplayBangumiID,
		&i.MalID,
		&i.TmdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WatchStatus,
		&i.WatchStatusUpdatedAt,
	)
	return i, err
}

const getAnimeByBangumiID = `-- name: GetAnimeByBangumiID :one
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at FROM anime WHERE bangumi_id = ? LIMIT 1
`

func (q *Queries) GetAnimeByBangumiID(ctx context.Context, bangumiID sql.NullInt64) (Anime, error) {
	row := q.db.QueryRowContext(ctx, getAnimeByBangumiID, bangumiID)
	var i Anime
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.TitleZh,
		&i.TitleEn,
		&i.Synopsis,
		&i.CoverImageUrl,
		&i.TotalEpisodes,
		&i.Status,
		&i.AirDate,
		&i.Year,
		&i.Season,
		&i.Genres,
		&i.IsCustom,
		&i.AnilistID,
		&i.BangumiID,
		&i.DandanplayBangumiID,
		&i.MalID,
		&i.TmdbID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WatchStatus,
		&i.WatchStatusUpdatedAt,
	)
	return i, err
}

const listAnimeByLibrary = `-- name: ListAnimeByLibrary :many
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at FROM anime WHERE library_id = ?
`

func (q *Queries) ListAnimeByLibrary(ctx context.Context, libraryID sql.NullString) ([]Anime, error) {
	rows, err := q.db.QueryContext(ctx, listAnimeByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Anime{}
	for rows.Next() {
		var i Anime
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.TitleZh,
			&i.TitleEn,
			&i.Synopsis,
			&i.CoverImageUrl,
			&i.TotalEpisodes,
			&i.Status,
			&i.AirDate,
			&i.Year,
			&i.Season,
			&i.Genres,
			&i.IsCustom,
			&i.AnilistID,
			&i.BangumiID,
			&i.DandanplayBangumiID,
			&i.MalID,
			&i.TmdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WatchStatus,
			&i.WatchStatusUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnimeByLibraryID = `-- name: ListAnimeByLibraryID :many
SELECT id, library_id, title, title_zh, title_en, synopsis, cover_image_url, total_episodes, status, air_date, year, season, genres, is_custom, anilist_id, bangumi_id, dandanplay_bangumi_id, mal_id, tmdb_id, created_at, updated_at, watch_status, watch_status_updated_at FROM anime WHERE library_id = ? ORDER BY title
`

func (q *Queries) ListAnimeByLibraryID(ctx context.Context, libraryID sql.NullString) ([]Anime, error) {
	rows, err := q.db.QueryContext(ctx, listAnimeByLibraryID, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Anime{}
	for rows.Next() {
		var i Anime
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Title,
			&i.TitleZh,
			&i.TitleEn,
			&i.Synopsis,
			&i.CoverImageUrl,
			&i.TotalEpisodes,
			&i.Status,
			&i.AirDate,
			&i.Year,
			&i.Season,
			&i.Genres,
			&i.IsCustom,
			&i.AnilistID,
			&i.BangumiID,
			&i.DandanplayBangumiID,
			&i.MalID,
			&i.TmdbID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WatchStatus,
			&i.WatchStatusUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnimeTMDBID = `-- name: UpdateAnimeTMDBID :exec
UPDATE anime SET tmdb_id = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateAnimeTMDBIDParams struct {
	TmdbID sql.NullInt64 `json:"tmdb_id"`
	ID     string        `json:"id"`
}

func (q *Queries) UpdateAnimeTMDBID(ctx context.Context, arg UpdateAnimeTMDBIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAnimeTMDBID, arg.TmdbID, arg.ID)
	return err
}
