// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package store

import (
	"context"
	"database/sql"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (id, name, token_hash, token_prefix, user_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
RETURNING id, name, token_hash, token_prefix, user_id, last_used_at, created_at, updated_at
`

type CreateAPITokenParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	TokenHash   string `json:"token_hash"`
	TokenPrefix string `json:"token_prefix"`
	UserID      string `json:"user_id"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.UserID,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.UserID,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = ? AND user_id = ?
`

type DeleteAPITokenParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIToken, arg.ID, arg.UserID)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, name, token_hash, token_prefix, user_id, last_used_at, created_at, updated_at FROM api_tokens WHERE token_hash = ? LIMIT 1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.UserID,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, name, token_prefix, user_id, last_used_at, created_at, updated_at
FROM api_tokens WHERE user_id = ? ORDER BY created_at DESC
`

type ListAPITokensByUserRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	TokenPrefix string         `json:"token_prefix"`
	UserID      string         `json:"user_id"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) ListAPITokensByUser(ctx context.Context, userID string) ([]ListAPITokensByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensByUserRow{}
	for rows.Next() {
		var i ListAPITokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.UserID,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateAPITokenLastUsed, id)
	return err
}
