// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package store

import (
	"context"
	"database/sql"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_log (
  id, user_id, token_id, agent_label, action_type, target_type, target_id,
  before_json, after_json, confidence, parent_id, dry_run
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, token_id, agent_label, action_type, target_type, target_id, before_json, after_json, confidence, parent_id, dry_run, undone_at, undone_by, created_at
`

type CreateAuditLogParams struct {
	ID         string          `json:"id"`
	UserID     string          `json:"user_id"`
	TokenID    sql.NullString  `json:"token_id"`
	AgentLabel sql.NullString  `json:"agent_label"`
	ActionType string          `json:"action_type"`
	TargetType sql.NullString  `json:"target_type"`
	TargetID   sql.NullString  `json:"target_id"`
	BeforeJson sql.NullString  `json:"before_json"`
	AfterJson  sql.NullString  `json:"after_json"`
	Confidence sql.NullFloat64 `json:"confidence"`
	ParentID   sql.NullString  `json:"parent_id"`
	DryRun     int64           `json:"dry_run"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.ID,
		arg.UserID,
		arg.TokenID,
		arg.AgentLabel,
		arg.ActionType,
		arg.TargetType,
		arg.TargetID,
		arg.BeforeJson,
		arg.AfterJson,
		arg.Confidence,
		arg.ParentID,
		arg.DryRun,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.AgentLabel,
		&i.ActionType,
		&i.TargetType,
		&i.TargetID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.Confidence,
		&i.ParentID,
		&i.DryRun,
		&i.UndoneAt,
		&i.UndoneBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, user_id, token_id, agent_label, action_type, target_type, target_id, before_json, after_json, confidence, parent_id, dry_run, undone_at, undone_by, created_at FROM audit_log WHERE id = ? LIMIT 1
`

func (q *Queries) GetAuditLog(ctx context.Context, id string) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getAuditLog, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.AgentLabel,
		&i.ActionType,
		&i.TargetType,
		&i.TargetID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.Confidence,
		&i.ParentID,
		&i.DryRun,
		&i.UndoneAt,
		&i.UndoneBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogByUser = `-- name: ListAuditLogByUser :many
SELECT id, user_id, token_id, agent_label, action_type, target_type, target_id, before_json, after_json, confidence, parent_id, dry_run, undone_at, undone_by, created_at FROM audit_log
WHERE user_id = ?
  AND (?4 IS NULL OR action_type = ?4)
  AND (?5 IS NULL OR created_at >= ?5)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogByUserParams struct {
	UserID     string      `json:"user_id"`
	ActionType interface{} `json:"action_type"`
	Since      interface{} `json:"since"`
	Limit      int64       `json:"limit"`
	Offset     int64       `json:"offset"`
}

func (q *Queries) ListAuditLogByUser(ctx context.Context, arg ListAuditLogByUserParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogByUser,
		arg.UserID,
		arg.ActionType,
		arg.Since,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenID,
			&i.AgentLabel,
			&i.ActionType,
			&i.TargetType,
			&i.TargetID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.Confidence,
			&i.ParentID,
			&i.DryRun,
			&i.UndoneAt,
			&i.UndoneBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogChildren = `-- name: ListAuditLogChildren :many
SELECT id, user_id, token_id, agent_label, action_type, target_type, target_id, before_json, after_json, confidence, parent_id, dry_run, undone_at, undone_by, created_at FROM audit_log WHERE parent_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListAuditLogChildren(ctx context.Context, parentID sql.NullString) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenID,
			&i.AgentLabel,
			&i.ActionType,
			&i.TargetType,
			&i.TargetID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.Confidence,
			&i.ParentID,
			&i.DryRun,
			&i.UndoneAt,
			&i.UndoneBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuditUndone = `-- name: MarkAuditUndone :exec
UPDATE audit_log
SET undone_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    undone_by = ?
WHERE id = ?
`

type MarkAuditUndoneParams struct {
	UndoneBy sql.NullString `json:"undone_by"`
	ID       string         `json:"id"`
}

func (q *Queries) MarkAuditUndone(ctx context.Context, arg MarkAuditUndoneParams) error {
	_, err := q.db.ExecContext(ctx, markAuditUndone, arg.UndoneBy, arg.ID)
	return err
}
