// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collection.sql

package store

import (
	"context"
	"database/sql"
)

const countCollectionByStatus = `-- name: CountCollectionByStatus :many
SELECT watch_status, COUNT(*) AS count
FROM anime a
WHERE a.watch_status != 'none'
  AND EXISTS (
    SELECT 1 FROM episodes e
    JOIN media_files mf ON mf.episode_id = e.id
    WHERE e.anime_id = a.id AND mf.match_status != 'unmatched'
  )
GROUP BY watch_status
`

type CountCollectionByStatusRow struct {
	WatchStatus string `json:"watch_status"`
	Count       int64  `json:"count"`
}

func (q *Queries) CountCollectionByStatus(ctx context.Context) ([]CountCollectionByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countCollectionByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCollectionByStatusRow{}
	for rows.Next() {
		var i CountCollectionByStatusRow
		if err := rows.Scan(&i.WatchStatus, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionAnime = `-- name: ListCollectionAnime :many
SELECT
  a.id,
  a.bangumi_id,
  a.title,
  a.title_zh,
  a.title_en,
  a.cover_image_url,
  a.total_episodes,
  a.status,
  a.watch_status,
  a.watch_status_updated_at,
  a.genres,
  a.year,
  a.season,
  a.air_date,
  a.created_at,
  a.user_score,
  COUNT(DISTINCT mf.id) AS local_file_count
FROM anime a
JOIN episodes e ON e.anime_id = a.id
JOIN media_files mf ON mf.episode_id = e.id
WHERE mf.match_status != 'unmatched'
  AND a.watch_status != 'none'
  AND (?1 = '' OR a.watch_status = ?1)
  AND (?2 = '' OR a.title LIKE '%' || ?2 || '%' OR COALESCE(a.title_zh, '') LIKE '%' || ?2 || '%')
GROUP BY a.id
ORDER BY a.watch_status_updated_at DESC, a.created_at DESC
`

type ListCollectionAnimeParams struct {
	StatusFilter interface{} `json:"status_filter"`
	SearchQuery  interface{} `json:"search_query"`
}

type ListCollectionAnimeRow struct {
	ID                   string         `json:"id"`
	BangumiID            sql.NullInt64  `json:"bangumi_id"`
	Title                string         `json:"title"`
	TitleZh              sql.NullString `json:"title_zh"`
	TitleEn              sql.NullString `json:"title_en"`
	CoverImageUrl        sql.NullString `json:"cover_image_url"`
	TotalEpisodes        sql.NullInt64  `json:"total_episodes"`
	Status               string         `json:"status"`
	WatchStatus          string         `json:"watch_status"`
	WatchStatusUpdatedAt sql.NullString `json:"watch_status_updated_at"`
	Genres               string         `json:"genres"`
	Year                 sql.NullInt64  `json:"year"`
	Season               sql.NullString `json:"season"`
	AirDate              sql.NullString `json:"air_date"`
	CreatedAt            string         `json:"created_at"`
	UserScore            sql.NullInt64  `json:"user_score"`
	LocalFileCount       int64          `json:"local_file_count"`
}

func (q *Queries) ListCollectionAnime(ctx context.Context, arg ListCollectionAnimeParams) ([]ListCollectionAnimeRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionAnime, arg.StatusFilter, arg.SearchQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionAnimeRow{}
	for rows.Next() {
		var i ListCollectionAnimeRow
		if err := rows.Scan(
			&i.ID,
			&i.BangumiID,
			&i.Title,
			&i.TitleZh,
			&i.TitleEn,
			&i.CoverImageUrl,
			&i.TotalEpisodes,
			&i.Status,
			&i.WatchStatus,
			&i.WatchStatusUpdatedAt,
			&i.Genres,
			&i.Year,
			&i.Season,
			&i.AirDate,
			&i.CreatedAt,
			&i.UserScore,
			&i.LocalFileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentlyMatchedAnime = `-- name: ListRecentlyMatchedAnime :many
SELECT
  a.id,
  a.bangumi_id,
  a.title,
  a.title_zh,
  a.cover_image_url,
  a.total_episodes,
  a.watch_status,
  a.user_score,
  COUNT(DISTINCT mf.id) AS local_file_count
FROM anime a
JOIN episodes e ON e.anime_id = a.id
JOIN media_files mf ON mf.episode_id = e.id
WHERE mf.match_status != 'unmatched'
  AND a.watch_status != 'none'
GROUP BY a.id
ORDER BY MAX(mf.created_at) DESC
LIMIT 10
`

type ListRecentlyMatchedAnimeRow struct {
	ID             string         `json:"id"`
	BangumiID      sql.NullInt64  `json:"bangumi_id"`
	Title          string         `json:"title"`
	TitleZh        sql.NullString `json:"title_zh"`
	CoverImageUrl  sql.NullString `json:"cover_image_url"`
	TotalEpisodes  sql.NullInt64  `json:"total_episodes"`
	WatchStatus    string         `json:"watch_status"`
	UserScore      sql.NullInt64  `json:"user_score"`
	LocalFileCount int64          `json:"local_file_count"`
}

func (q *Queries) ListRecentlyMatchedAnime(ctx context.Context) ([]ListRecentlyMatchedAnimeRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentlyMatchedAnime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentlyMatchedAnimeRow{}
	for rows.Next() {
		var i ListRecentlyMatchedAnimeRow
		if err := rows.Scan(
			&i.ID,
			&i.BangumiID,
			&i.Title,
			&i.TitleZh,
			&i.CoverImageUrl,
			&i.TotalEpisodes,
			&i.WatchStatus,
			&i.UserScore,
			&i.LocalFileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnimeWatchStatus = `-- name: UpdateAnimeWatchStatus :exec
UPDATE anime
SET watch_status = ?1,
    watch_status_updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE bangumi_id = ?2
`

type UpdateAnimeWatchStatusParams struct {
	WatchStatus string        `json:"watch_status"`
	BangumiID   sql.NullInt64 `json:"bangumi_id"`
}

func (q *Queries) UpdateAnimeWatchStatus(ctx context.Context, arg UpdateAnimeWatchStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAnimeWatchStatus, arg.WatchStatus, arg.BangumiID)
	return err
}
