// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: downloads.sql

package store

import (
	"context"
	"database/sql"
)

const createDownload = `-- name: CreateDownload :one
INSERT INTO downloads (id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, bangumi_id, library_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'))
RETURNING id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at, bangumi_id, library_id
`

type CreateDownloadParams struct {
	ID             string         `json:"id"`
	Gid            string         `json:"gid"`
	Url            string         `json:"url"`
	Name           string         `json:"name"`
	Status         string         `json:"status"`
	TotalBytes     int64          `json:"total_bytes"`
	CompletedBytes int64          `json:"completed_bytes"`
	SpeedBytes     int64          `json:"speed_bytes"`
	SaveDir        string         `json:"save_dir"`
	RuleID         sql.NullString `json:"rule_id"`
	BangumiID      sql.NullInt64  `json:"bangumi_id"`
	LibraryID      sql.NullString `json:"library_id"`
}

func (q *Queries) CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, createDownload,
		arg.ID,
		arg.Gid,
		arg.Url,
		arg.Name,
		arg.Status,
		arg.TotalBytes,
		arg.CompletedBytes,
		arg.SpeedBytes,
		arg.SaveDir,
		arg.RuleID,
		arg.BangumiID,
		arg.LibraryID,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.TotalBytes,
		&i.CompletedBytes,
		&i.SpeedBytes,
		&i.SaveDir,
		&i.RuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BangumiID,
		&i.LibraryID,
	)
	return i, err
}

const deleteDownload = `-- name: DeleteDownload :exec
DELETE FROM downloads WHERE gid = ?
`

func (q *Queries) DeleteDownload(ctx context.Context, gid string) error {
	_, err := q.db.ExecContext(ctx, deleteDownload, gid)
	return err
}

const getDownloadByGID = `-- name: GetDownloadByGID :one
SELECT id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at, bangumi_id, library_id FROM downloads WHERE gid = ? LIMIT 1
`

func (q *Queries) GetDownloadByGID(ctx context.Context, gid string) (Download, error) {
	row := q.db.QueryRowContext(ctx, getDownloadByGID, gid)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.TotalBytes,
		&i.CompletedBytes,
		&i.SpeedBytes,
		&i.SaveDir,
		&i.RuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BangumiID,
		&i.LibraryID,
	)
	return i, err
}

const getDownloadByURL = `-- name: GetDownloadByURL :one
SELECT id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at, bangumi_id, library_id FROM downloads WHERE url = ? LIMIT 1
`

func (q *Queries) GetDownloadByURL(ctx context.Context, url string) (Download, error) {
	row := q.db.QueryRowContext(ctx, getDownloadByURL, url)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.TotalBytes,
		&i.CompletedBytes,
		&i.SpeedBytes,
		&i.SaveDir,
		&i.RuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BangumiID,
		&i.LibraryID,
	)
	return i, err
}

const listActiveDownloads = `-- name: ListActiveDownloads :many
SELECT id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at, bangumi_id, library_id FROM downloads WHERE status IN ('active', 'waiting', 'paused') ORDER BY created_at DESC
`

func (q *Queries) ListActiveDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Gid,
			&i.Url,
			&i.Name,
			&i.Status,
			&i.TotalBytes,
			&i.CompletedBytes,
			&i.SpeedBytes,
			&i.SaveDir,
			&i.RuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BangumiID,
			&i.LibraryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedDownloads = `-- name: ListCompletedDownloads :many
SELECT id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at, bangumi_id, library_id FROM downloads WHERE status = 'complete' ORDER BY updated_at DESC LIMIT 50
`

func (q *Queries) ListCompletedDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Gid,
			&i.Url,
			&i.Name,
			&i.Status,
			&i.TotalBytes,
			&i.CompletedBytes,
			&i.SpeedBytes,
			&i.SaveDir,
			&i.RuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BangumiID,
			&i.LibraryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloads = `-- name: ListDownloads :many
SELECT id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at, bangumi_id, library_id FROM downloads ORDER BY created_at DESC
`

func (q *Queries) ListDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Gid,
			&i.Url,
			&i.Name,
			&i.Status,
			&i.TotalBytes,
			&i.CompletedBytes,
			&i.SpeedBytes,
			&i.SaveDir,
			&i.RuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BangumiID,
			&i.LibraryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadsByLibraryID = `-- name: ListDownloadsByLibraryID :many
SELECT id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at, bangumi_id, library_id FROM downloads WHERE library_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDownloadsByLibraryID(ctx context.Context, libraryID sql.NullString) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadsByLibraryID, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Gid,
			&i.Url,
			&i.Name,
			&i.Status,
			&i.TotalBytes,
			&i.CompletedBytes,
			&i.SpeedBytes,
			&i.SaveDir,
			&i.RuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BangumiID,
			&i.LibraryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadsByRuleID = `-- name: ListDownloadsByRuleID :many
SELECT id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at, bangumi_id, library_id FROM downloads WHERE rule_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDownloadsByRuleID(ctx context.Context, ruleID sql.NullString) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadsByRuleID, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Gid,
			&i.Url,
			&i.Name,
			&i.Status,
			&i.TotalBytes,
			&i.CompletedBytes,
			&i.SpeedBytes,
			&i.SaveDir,
			&i.RuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BangumiID,
			&i.LibraryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkDownloadsByRuleID = `-- name: UnlinkDownloadsByRuleID :exec
UPDATE downloads SET rule_id = NULL WHERE rule_id = ?
`

func (q *Queries) UnlinkDownloadsByRuleID(ctx context.Context, ruleID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, unlinkDownloadsByRuleID, ruleID)
	return err
}

const updateDownloadStatus = `-- name: UpdateDownloadStatus :exec
UPDATE downloads SET status = ?, total_bytes = ?, completed_bytes = ?, speed_bytes = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now') WHERE gid = ?
`

type UpdateDownloadStatusParams struct {
	Status         string `json:"status"`
	TotalBytes     int64  `json:"total_bytes"`
	CompletedBytes int64  `json:"completed_bytes"`
	SpeedBytes     int64  `json:"speed_bytes"`
	Gid            string `json:"gid"`
}

func (q *Queries) UpdateDownloadStatus(ctx context.Context, arg UpdateDownloadStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadStatus,
		arg.Status,
		arg.TotalBytes,
		arg.CompletedBytes,
		arg.SpeedBytes,
		arg.Gid,
	)
	return err
}
