// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: downloads.sql

package store

import (
	"context"
	"database/sql"
)

const createDownload = `-- name: CreateDownload :one
INSERT INTO downloads (id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'))
RETURNING id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at
`

type CreateDownloadParams struct {
	ID             string         `json:"id"`
	Gid            string         `json:"gid"`
	Url            string         `json:"url"`
	Name           string         `json:"name"`
	Status         string         `json:"status"`
	TotalBytes     int64          `json:"total_bytes"`
	CompletedBytes int64          `json:"completed_bytes"`
	SpeedBytes     int64          `json:"speed_bytes"`
	SaveDir        string         `json:"save_dir"`
	RuleID         sql.NullString `json:"rule_id"`
}

func (q *Queries) CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error) {
	row := q.db.QueryRowContext(ctx, createDownload,
		arg.ID,
		arg.Gid,
		arg.Url,
		arg.Name,
		arg.Status,
		arg.TotalBytes,
		arg.CompletedBytes,
		arg.SpeedBytes,
		arg.SaveDir,
		arg.RuleID,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.TotalBytes,
		&i.CompletedBytes,
		&i.SpeedBytes,
		&i.SaveDir,
		&i.RuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDownload = `-- name: DeleteDownload :exec
DELETE FROM downloads WHERE gid = ?
`

func (q *Queries) DeleteDownload(ctx context.Context, gid string) error {
	_, err := q.db.ExecContext(ctx, deleteDownload, gid)
	return err
}

const getDownloadByGID = `-- name: GetDownloadByGID :one
SELECT id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at FROM downloads WHERE gid = ? LIMIT 1
`

func (q *Queries) GetDownloadByGID(ctx context.Context, gid string) (Download, error) {
	row := q.db.QueryRowContext(ctx, getDownloadByGID, gid)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.TotalBytes,
		&i.CompletedBytes,
		&i.SpeedBytes,
		&i.SaveDir,
		&i.RuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDownloadByURL = `-- name: GetDownloadByURL :one
SELECT id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at FROM downloads WHERE url = ? LIMIT 1
`

func (q *Queries) GetDownloadByURL(ctx context.Context, url string) (Download, error) {
	row := q.db.QueryRowContext(ctx, getDownloadByURL, url)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Gid,
		&i.Url,
		&i.Name,
		&i.Status,
		&i.TotalBytes,
		&i.CompletedBytes,
		&i.SpeedBytes,
		&i.SaveDir,
		&i.RuleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDownloads = `-- name: ListDownloads :many
SELECT id, gid, url, name, status, total_bytes, completed_bytes, speed_bytes, save_dir, rule_id, created_at, updated_at FROM downloads ORDER BY created_at DESC
`

func (q *Queries) ListDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Gid,
			&i.Url,
			&i.Name,
			&i.Status,
			&i.TotalBytes,
			&i.CompletedBytes,
			&i.SpeedBytes,
			&i.SaveDir,
			&i.RuleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownloadStatus = `-- name: UpdateDownloadStatus :exec
UPDATE downloads SET status = ?, total_bytes = ?, completed_bytes = ?, speed_bytes = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now') WHERE gid = ?
`

type UpdateDownloadStatusParams struct {
	Status         string `json:"status"`
	TotalBytes     int64  `json:"total_bytes"`
	CompletedBytes int64  `json:"completed_bytes"`
	SpeedBytes     int64  `json:"speed_bytes"`
	Gid            string `json:"gid"`
}

func (q *Queries) UpdateDownloadStatus(ctx context.Context, arg UpdateDownloadStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadStatus,
		arg.Status,
		arg.TotalBytes,
		arg.CompletedBytes,
		arg.SpeedBytes,
		arg.Gid,
	)
	return err
}
