// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: download_rules.sql

package store

import (
	"context"
	"database/sql"
)

const createDownloadRule = `-- name: CreateDownloadRule :one
INSERT INTO download_rules (id, name, enabled, rss_feed_id, filter_regex, exclude_regex, save_dir, episode_offset, resolution_filter, subgroup_filter, min_seeders, library_id, bangumi_id, match_mode, episode_filter, episode_range, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ','now'))
RETURNING id, name, enabled, rss_feed_id, filter_regex, exclude_regex, save_dir, episode_offset, last_triggered_at, created_at, resolution_filter, subgroup_filter, min_seeders, library_id, bangumi_id, match_mode, episode_filter, episode_range
`

type CreateDownloadRuleParams struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Enabled          int64          `json:"enabled"`
	RssFeedID        string         `json:"rss_feed_id"`
	FilterRegex      string         `json:"filter_regex"`
	ExcludeRegex     string         `json:"exclude_regex"`
	SaveDir          string         `json:"save_dir"`
	EpisodeOffset    int64          `json:"episode_offset"`
	ResolutionFilter string         `json:"resolution_filter"`
	SubgroupFilter   string         `json:"subgroup_filter"`
	MinSeeders       int64          `json:"min_seeders"`
	LibraryID        sql.NullString `json:"library_id"`
	BangumiID        sql.NullInt64  `json:"bangumi_id"`
	MatchMode        string         `json:"match_mode"`
	EpisodeFilter    string         `json:"episode_filter"`
	EpisodeRange     string         `json:"episode_range"`
}

func (q *Queries) CreateDownloadRule(ctx context.Context, arg CreateDownloadRuleParams) (DownloadRule, error) {
	row := q.db.QueryRowContext(ctx, createDownloadRule,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.RssFeedID,
		arg.FilterRegex,
		arg.ExcludeRegex,
		arg.SaveDir,
		arg.EpisodeOffset,
		arg.ResolutionFilter,
		arg.SubgroupFilter,
		arg.MinSeeders,
		arg.LibraryID,
		arg.BangumiID,
		arg.MatchMode,
		arg.EpisodeFilter,
		arg.EpisodeRange,
	)
	var i DownloadRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.RssFeedID,
		&i.FilterRegex,
		&i.ExcludeRegex,
		&i.SaveDir,
		&i.EpisodeOffset,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.ResolutionFilter,
		&i.SubgroupFilter,
		&i.MinSeeders,
		&i.LibraryID,
		&i.BangumiID,
		&i.MatchMode,
		&i.EpisodeFilter,
		&i.EpisodeRange,
	)
	return i, err
}

const deleteDownloadRule = `-- name: DeleteDownloadRule :exec
DELETE FROM download_rules WHERE id = ?
`

func (q *Queries) DeleteDownloadRule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadRule, id)
	return err
}

const getDownloadRule = `-- name: GetDownloadRule :one
SELECT id, name, enabled, rss_feed_id, filter_regex, exclude_regex, save_dir, episode_offset, last_triggered_at, created_at, resolution_filter, subgroup_filter, min_seeders, library_id, bangumi_id, match_mode, episode_filter, episode_range FROM download_rules WHERE id = ? LIMIT 1
`

func (q *Queries) GetDownloadRule(ctx context.Context, id string) (DownloadRule, error) {
	row := q.db.QueryRowContext(ctx, getDownloadRule, id)
	var i DownloadRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.RssFeedID,
		&i.FilterRegex,
		&i.ExcludeRegex,
		&i.SaveDir,
		&i.EpisodeOffset,
		&i.LastTriggeredAt,
		&i.CreatedAt,
		&i.ResolutionFilter,
		&i.SubgroupFilter,
		&i.MinSeeders,
		&i.LibraryID,
		&i.BangumiID,
		&i.MatchMode,
		&i.EpisodeFilter,
		&i.EpisodeRange,
	)
	return i, err
}

const listDownloadRules = `-- name: ListDownloadRules :many
SELECT id, name, enabled, rss_feed_id, filter_regex, exclude_regex, save_dir, episode_offset, last_triggered_at, created_at, resolution_filter, subgroup_filter, min_seeders, library_id, bangumi_id, match_mode, episode_filter, episode_range FROM download_rules ORDER BY name
`

func (q *Queries) ListDownloadRules(ctx context.Context) ([]DownloadRule, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadRule{}
	for rows.Next() {
		var i DownloadRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.RssFeedID,
			&i.FilterRegex,
			&i.ExcludeRegex,
			&i.SaveDir,
			&i.EpisodeOffset,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.ResolutionFilter,
			&i.SubgroupFilter,
			&i.MinSeeders,
			&i.LibraryID,
			&i.BangumiID,
			&i.MatchMode,
			&i.EpisodeFilter,
			&i.EpisodeRange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadRulesByBangumiID = `-- name: ListDownloadRulesByBangumiID :many
SELECT id, name, enabled, rss_feed_id, filter_regex, exclude_regex, save_dir, episode_offset, last_triggered_at, created_at, resolution_filter, subgroup_filter, min_seeders, library_id, bangumi_id, match_mode, episode_filter, episode_range FROM download_rules WHERE bangumi_id = ? AND enabled = 1 ORDER BY created_at DESC
`

func (q *Queries) ListDownloadRulesByBangumiID(ctx context.Context, bangumiID sql.NullInt64) ([]DownloadRule, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadRulesByBangumiID, bangumiID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadRule{}
	for rows.Next() {
		var i DownloadRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.RssFeedID,
			&i.FilterRegex,
			&i.ExcludeRegex,
			&i.SaveDir,
			&i.EpisodeOffset,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.ResolutionFilter,
			&i.SubgroupFilter,
			&i.MinSeeders,
			&i.LibraryID,
			&i.BangumiID,
			&i.MatchMode,
			&i.EpisodeFilter,
			&i.EpisodeRange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadRulesByFeedID = `-- name: ListDownloadRulesByFeedID :many
SELECT id, name, enabled, rss_feed_id, filter_regex, exclude_regex, save_dir, episode_offset, last_triggered_at, created_at, resolution_filter, subgroup_filter, min_seeders, library_id, bangumi_id, match_mode, episode_filter, episode_range FROM download_rules WHERE rss_feed_id = ? AND enabled = 1
`

func (q *Queries) ListDownloadRulesByFeedID(ctx context.Context, rssFeedID string) ([]DownloadRule, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadRulesByFeedID, rssFeedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadRule{}
	for rows.Next() {
		var i DownloadRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.RssFeedID,
			&i.FilterRegex,
			&i.ExcludeRegex,
			&i.SaveDir,
			&i.EpisodeOffset,
			&i.LastTriggeredAt,
			&i.CreatedAt,
			&i.ResolutionFilter,
			&i.SubgroupFilter,
			&i.MinSeeders,
			&i.LibraryID,
			&i.BangumiID,
			&i.MatchMode,
			&i.EpisodeFilter,
			&i.EpisodeRange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownloadRule = `-- name: UpdateDownloadRule :exec
UPDATE download_rules SET name = ?, enabled = ?, rss_feed_id = ?, filter_regex = ?, exclude_regex = ?, save_dir = ?, episode_offset = ?, resolution_filter = ?, subgroup_filter = ?, min_seeders = ?, library_id = ?, bangumi_id = ?, match_mode = ?, episode_filter = ?, episode_range = ? WHERE id = ?
`

type UpdateDownloadRuleParams struct {
	Name             string         `json:"name"`
	Enabled          int64          `json:"enabled"`
	RssFeedID        string         `json:"rss_feed_id"`
	FilterRegex      string         `json:"filter_regex"`
	ExcludeRegex     string         `json:"exclude_regex"`
	SaveDir          string         `json:"save_dir"`
	EpisodeOffset    int64          `json:"episode_offset"`
	ResolutionFilter string         `json:"resolution_filter"`
	SubgroupFilter   string         `json:"subgroup_filter"`
	MinSeeders       int64          `json:"min_seeders"`
	LibraryID        sql.NullString `json:"library_id"`
	BangumiID        sql.NullInt64  `json:"bangumi_id"`
	MatchMode        string         `json:"match_mode"`
	EpisodeFilter    string         `json:"episode_filter"`
	EpisodeRange     string         `json:"episode_range"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateDownloadRule(ctx context.Context, arg UpdateDownloadRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadRule,
		arg.Name,
		arg.Enabled,
		arg.RssFeedID,
		arg.FilterRegex,
		arg.ExcludeRegex,
		arg.SaveDir,
		arg.EpisodeOffset,
		arg.ResolutionFilter,
		arg.SubgroupFilter,
		arg.MinSeeders,
		arg.LibraryID,
		arg.BangumiID,
		arg.MatchMode,
		arg.EpisodeFilter,
		arg.EpisodeRange,
		arg.ID,
	)
	return err
}

const updateDownloadRuleTriggered = `-- name: UpdateDownloadRuleTriggered :exec
UPDATE download_rules SET last_triggered_at = strftime('%Y-%m-%dT%H:%M:%SZ','now') WHERE id = ?
`

func (q *Queries) UpdateDownloadRuleTriggered(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateDownloadRuleTriggered, id)
	return err
}
