// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes.sql

package store

import (
	"context"
	"database/sql"
)

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (id, anime_id, episode_number, title, title_zh, air_date,
    dandanplay_episode_id, bangumi_episode_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?,
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
RETURNING id, anime_id, episode_number, title, title_zh, air_date, synopsis, thumbnail_url, dandanplay_episode_id, bangumi_episode_id, mal_episode_id, created_at, updated_at, synopsis_zh
`

type CreateEpisodeParams struct {
	ID                  string         `json:"id"`
	AnimeID             string         `json:"anime_id"`
	EpisodeNumber       float64        `json:"episode_number"`
	Title               sql.NullString `json:"title"`
	TitleZh             sql.NullString `json:"title_zh"`
	AirDate             sql.NullString `json:"air_date"`
	DandanplayEpisodeID sql.NullInt64  `json:"dandanplay_episode_id"`
	BangumiEpisodeID    sql.NullInt64  `json:"bangumi_episode_id"`
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, createEpisode,
		arg.ID,
		arg.AnimeID,
		arg.EpisodeNumber,
		arg.Title,
		arg.TitleZh,
		arg.AirDate,
		arg.DandanplayEpisodeID,
		arg.BangumiEpisodeID,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeNumber,
		&i.Title,
		&i.TitleZh,
		&i.AirDate,
		&i.Synopsis,
		&i.ThumbnailUrl,
		&i.DandanplayEpisodeID,
		&i.BangumiEpisodeID,
		&i.MalEpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SynopsisZh,
	)
	return i, err
}

const getEpisode = `-- name: GetEpisode :one
SELECT id, anime_id, episode_number, title, title_zh, air_date, synopsis, thumbnail_url, dandanplay_episode_id, bangumi_episode_id, mal_episode_id, created_at, updated_at, synopsis_zh FROM episodes WHERE id = ? LIMIT 1
`

func (q *Queries) GetEpisode(ctx context.Context, id string) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisode, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeNumber,
		&i.Title,
		&i.TitleZh,
		&i.AirDate,
		&i.Synopsis,
		&i.ThumbnailUrl,
		&i.DandanplayEpisodeID,
		&i.BangumiEpisodeID,
		&i.MalEpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SynopsisZh,
	)
	return i, err
}

const getEpisodeByAnimeAndNumber = `-- name: GetEpisodeByAnimeAndNumber :one
SELECT id, anime_id, episode_number, title, title_zh, air_date, synopsis, thumbnail_url, dandanplay_episode_id, bangumi_episode_id, mal_episode_id, created_at, updated_at, synopsis_zh FROM episodes WHERE anime_id = ? AND episode_number = ? LIMIT 1
`

type GetEpisodeByAnimeAndNumberParams struct {
	AnimeID       string  `json:"anime_id"`
	EpisodeNumber float64 `json:"episode_number"`
}

func (q *Queries) GetEpisodeByAnimeAndNumber(ctx context.Context, arg GetEpisodeByAnimeAndNumberParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByAnimeAndNumber, arg.AnimeID, arg.EpisodeNumber)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeNumber,
		&i.Title,
		&i.TitleZh,
		&i.AirDate,
		&i.Synopsis,
		&i.ThumbnailUrl,
		&i.DandanplayEpisodeID,
		&i.BangumiEpisodeID,
		&i.MalEpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SynopsisZh,
	)
	return i, err
}

const getEpisodeByDandanplayID = `-- name: GetEpisodeByDandanplayID :one
SELECT id, anime_id, episode_number, title, title_zh, air_date, synopsis, thumbnail_url, dandanplay_episode_id, bangumi_episode_id, mal_episode_id, created_at, updated_at, synopsis_zh FROM episodes WHERE dandanplay_episode_id = ? LIMIT 1
`

func (q *Queries) GetEpisodeByDandanplayID(ctx context.Context, dandanplayEpisodeID sql.NullInt64) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByDandanplayID, dandanplayEpisodeID)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeNumber,
		&i.Title,
		&i.TitleZh,
		&i.AirDate,
		&i.Synopsis,
		&i.ThumbnailUrl,
		&i.DandanplayEpisodeID,
		&i.BangumiEpisodeID,
		&i.MalEpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SynopsisZh,
	)
	return i, err
}

const listEpisodesByAnimeID = `-- name: ListEpisodesByAnimeID :many
SELECT id, anime_id, episode_number, title, title_zh, air_date, synopsis, thumbnail_url, dandanplay_episode_id, bangumi_episode_id, mal_episode_id, created_at, updated_at, synopsis_zh FROM episodes WHERE anime_id = ? ORDER BY episode_number
`

func (q *Queries) ListEpisodesByAnimeID(ctx context.Context, animeID string) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesByAnimeID, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.AnimeID,
			&i.EpisodeNumber,
			&i.Title,
			&i.TitleZh,
			&i.AirDate,
			&i.Synopsis,
			&i.ThumbnailUrl,
			&i.DandanplayEpisodeID,
			&i.BangumiEpisodeID,
			&i.MalEpisodeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SynopsisZh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEpisodeTMDBMetadata = `-- name: UpdateEpisodeTMDBMetadata :exec
UPDATE episodes
SET synopsis_zh = COALESCE(NULLIF(?, ''), synopsis_zh),
    title_zh = COALESCE(NULLIF(?, ''), title_zh),
    thumbnail_url = COALESCE(NULLIF(?, ''), thumbnail_url),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateEpisodeTMDBMetadataParams struct {
	NULLIF   interface{} `json:"NULLIF"`
	NULLIF_2 interface{} `json:"NULLIF_2"`
	NULLIF_3 interface{} `json:"NULLIF_3"`
	ID       string      `json:"id"`
}

func (q *Queries) UpdateEpisodeTMDBMetadata(ctx context.Context, arg UpdateEpisodeTMDBMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodeTMDBMetadata,
		arg.NULLIF,
		arg.NULLIF_2,
		arg.NULLIF_3,
		arg.ID,
	)
	return err
}
