// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes.sql

package store

import (
	"context"
	"database/sql"
)

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (id, anime_id, episode_number, title, title_zh, air_date,
    dandanplay_episode_id, bangumi_episode_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?,
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
RETURNING id, anime_id, episode_number, title, title_zh, air_date, synopsis, thumbnail_url, dandanplay_episode_id, bangumi_episode_id, mal_episode_id, created_at, updated_at, synopsis_zh, preferred_media_file_id, preferred_manually_set
`

type CreateEpisodeParams struct {
	ID                  string         `json:"id"`
	AnimeID             string         `json:"anime_id"`
	EpisodeNumber       float64        `json:"episode_number"`
	Title               sql.NullString `json:"title"`
	TitleZh             sql.NullString `json:"title_zh"`
	AirDate             sql.NullString `json:"air_date"`
	DandanplayEpisodeID sql.NullInt64  `json:"dandanplay_episode_id"`
	BangumiEpisodeID    sql.NullInt64  `json:"bangumi_episode_id"`
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, createEpisode,
		arg.ID,
		arg.AnimeID,
		arg.EpisodeNumber,
		arg.Title,
		arg.TitleZh,
		arg.AirDate,
		arg.DandanplayEpisodeID,
		arg.BangumiEpisodeID,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeNumber,
		&i.Title,
		&i.TitleZh,
		&i.AirDate,
		&i.Synopsis,
		&i.ThumbnailUrl,
		&i.DandanplayEpisodeID,
		&i.BangumiEpisodeID,
		&i.MalEpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SynopsisZh,
		&i.PreferredMediaFileID,
		&i.PreferredManuallySet,
	)
	return i, err
}

const getEpisode = `-- name: GetEpisode :one
SELECT id, anime_id, episode_number, title, title_zh, air_date, synopsis, thumbnail_url, dandanplay_episode_id, bangumi_episode_id, mal_episode_id, created_at, updated_at, synopsis_zh, preferred_media_file_id, preferred_manually_set FROM episodes WHERE id = ? LIMIT 1
`

func (q *Queries) GetEpisode(ctx context.Context, id string) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisode, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeNumber,
		&i.Title,
		&i.TitleZh,
		&i.AirDate,
		&i.Synopsis,
		&i.ThumbnailUrl,
		&i.DandanplayEpisodeID,
		&i.BangumiEpisodeID,
		&i.MalEpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SynopsisZh,
		&i.PreferredMediaFileID,
		&i.PreferredManuallySet,
	)
	return i, err
}

const getEpisodeByAnimeAndNumber = `-- name: GetEpisodeByAnimeAndNumber :one
SELECT id, anime_id, episode_number, title, title_zh, air_date, synopsis, thumbnail_url, dandanplay_episode_id, bangumi_episode_id, mal_episode_id, created_at, updated_at, synopsis_zh, preferred_media_file_id, preferred_manually_set FROM episodes WHERE anime_id = ? AND episode_number = ? LIMIT 1
`

type GetEpisodeByAnimeAndNumberParams struct {
	AnimeID       string  `json:"anime_id"`
	EpisodeNumber float64 `json:"episode_number"`
}

func (q *Queries) GetEpisodeByAnimeAndNumber(ctx context.Context, arg GetEpisodeByAnimeAndNumberParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByAnimeAndNumber, arg.AnimeID, arg.EpisodeNumber)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeNumber,
		&i.Title,
		&i.TitleZh,
		&i.AirDate,
		&i.Synopsis,
		&i.ThumbnailUrl,
		&i.DandanplayEpisodeID,
		&i.BangumiEpisodeID,
		&i.MalEpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SynopsisZh,
		&i.PreferredMediaFileID,
		&i.PreferredManuallySet,
	)
	return i, err
}

const getEpisodeByDandanplayID = `-- name: GetEpisodeByDandanplayID :one
SELECT id, anime_id, episode_number, title, title_zh, air_date, synopsis, thumbnail_url, dandanplay_episode_id, bangumi_episode_id, mal_episode_id, created_at, updated_at, synopsis_zh, preferred_media_file_id, preferred_manually_set FROM episodes WHERE dandanplay_episode_id = ? LIMIT 1
`

func (q *Queries) GetEpisodeByDandanplayID(ctx context.Context, dandanplayEpisodeID sql.NullInt64) (Episode, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByDandanplayID, dandanplayEpisodeID)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.EpisodeNumber,
		&i.Title,
		&i.TitleZh,
		&i.AirDate,
		&i.Synopsis,
		&i.ThumbnailUrl,
		&i.DandanplayEpisodeID,
		&i.BangumiEpisodeID,
		&i.MalEpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SynopsisZh,
		&i.PreferredMediaFileID,
		&i.PreferredManuallySet,
	)
	return i, err
}

const listEpisodesByAnimeID = `-- name: ListEpisodesByAnimeID :many
SELECT id, anime_id, episode_number, title, title_zh, air_date, synopsis, thumbnail_url, dandanplay_episode_id, bangumi_episode_id, mal_episode_id, created_at, updated_at, synopsis_zh, preferred_media_file_id, preferred_manually_set FROM episodes WHERE anime_id = ? ORDER BY episode_number
`

func (q *Queries) ListEpisodesByAnimeID(ctx context.Context, animeID string) ([]Episode, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesByAnimeID, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Episode{}
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.AnimeID,
			&i.EpisodeNumber,
			&i.Title,
			&i.TitleZh,
			&i.AirDate,
			&i.Synopsis,
			&i.ThumbnailUrl,
			&i.DandanplayEpisodeID,
			&i.BangumiEpisodeID,
			&i.MalEpisodeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SynopsisZh,
			&i.PreferredMediaFileID,
			&i.PreferredManuallySet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesByAnimeIDWithAirDate = `-- name: ListEpisodesByAnimeIDWithAirDate :many
SELECT id, anime_id, episode_number, air_date FROM episodes
WHERE anime_id = ? ORDER BY episode_number ASC
`

type ListEpisodesByAnimeIDWithAirDateRow struct {
	ID            string         `json:"id"`
	AnimeID       string         `json:"anime_id"`
	EpisodeNumber float64        `json:"episode_number"`
	AirDate       sql.NullString `json:"air_date"`
}

func (q *Queries) ListEpisodesByAnimeIDWithAirDate(ctx context.Context, animeID string) ([]ListEpisodesByAnimeIDWithAirDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesByAnimeIDWithAirDate, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpisodesByAnimeIDWithAirDateRow{}
	for rows.Next() {
		var i ListEpisodesByAnimeIDWithAirDateRow
		if err := rows.Scan(
			&i.ID,
			&i.AnimeID,
			&i.EpisodeNumber,
			&i.AirDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesByLibraryIDWithAirDate = `-- name: ListEpisodesByLibraryIDWithAirDate :many
SELECT e.id, e.anime_id, e.episode_number, e.air_date
FROM episodes e
JOIN anime a ON a.id = e.anime_id
WHERE a.library_id = ? ORDER BY e.anime_id, e.episode_number ASC
`

type ListEpisodesByLibraryIDWithAirDateRow struct {
	ID            string         `json:"id"`
	AnimeID       string         `json:"anime_id"`
	EpisodeNumber float64        `json:"episode_number"`
	AirDate       sql.NullString `json:"air_date"`
}

func (q *Queries) ListEpisodesByLibraryIDWithAirDate(ctx context.Context, libraryID sql.NullString) ([]ListEpisodesByLibraryIDWithAirDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesByLibraryIDWithAirDate, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpisodesByLibraryIDWithAirDateRow{}
	for rows.Next() {
		var i ListEpisodesByLibraryIDWithAirDateRow
		if err := rows.Scan(
			&i.ID,
			&i.AnimeID,
			&i.EpisodeNumber,
			&i.AirDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEpisodePreferredAuto = `-- name: SetEpisodePreferredAuto :exec
UPDATE episodes
SET preferred_media_file_id = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2 AND preferred_manually_set = 0
`

type SetEpisodePreferredAutoParams struct {
	FileID sql.NullString `json:"file_id"`
	ID     string         `json:"id"`
}

// Only writes when no manual preference is set yet.
func (q *Queries) SetEpisodePreferredAuto(ctx context.Context, arg SetEpisodePreferredAutoParams) error {
	_, err := q.db.ExecContext(ctx, setEpisodePreferredAuto, arg.FileID, arg.ID)
	return err
}

const setEpisodePreferredManual = `-- name: SetEpisodePreferredManual :exec
UPDATE episodes
SET preferred_media_file_id = ?1,
    preferred_manually_set = 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2
`

type SetEpisodePreferredManualParams struct {
	FileID sql.NullString `json:"file_id"`
	ID     string         `json:"id"`
}

func (q *Queries) SetEpisodePreferredManual(ctx context.Context, arg SetEpisodePreferredManualParams) error {
	_, err := q.db.ExecContext(ctx, setEpisodePreferredManual, arg.FileID, arg.ID)
	return err
}

const updateEpisodeTMDBMetadata = `-- name: UpdateEpisodeTMDBMetadata :exec
UPDATE episodes
SET synopsis_zh = COALESCE(NULLIF(?, ''), synopsis_zh),
    title_zh = COALESCE(NULLIF(?, ''), title_zh),
    thumbnail_url = COALESCE(NULLIF(?, ''), thumbnail_url),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateEpisodeTMDBMetadataParams struct {
	NULLIF   interface{} `json:"NULLIF"`
	NULLIF_2 interface{} `json:"NULLIF_2"`
	NULLIF_3 interface{} `json:"NULLIF_3"`
	ID       string      `json:"id"`
}

func (q *Queries) UpdateEpisodeTMDBMetadata(ctx context.Context, arg UpdateEpisodeTMDBMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodeTMDBMetadata,
		arg.NULLIF,
		arg.NULLIF_2,
		arg.NULLIF_3,
		arg.ID,
	)
	return err
}
