// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_danmaku.sql

package store

import (
	"context"
)

const deleteAllExternalDanmaku = `-- name: DeleteAllExternalDanmaku :exec
DELETE FROM external_danmaku
WHERE media_file_id = ?
`

func (q *Queries) DeleteAllExternalDanmaku(ctx context.Context, mediaFileID string) error {
	_, err := q.db.ExecContext(ctx, deleteAllExternalDanmaku, mediaFileID)
	return err
}

const deleteExternalDanmaku = `-- name: DeleteExternalDanmaku :exec
DELETE FROM external_danmaku
WHERE media_file_id = ? AND source = ?
`

type DeleteExternalDanmakuParams struct {
	MediaFileID string `json:"media_file_id"`
	Source      string `json:"source"`
}

func (q *Queries) DeleteExternalDanmaku(ctx context.Context, arg DeleteExternalDanmakuParams) error {
	_, err := q.db.ExecContext(ctx, deleteExternalDanmaku, arg.MediaFileID, arg.Source)
	return err
}

const getExternalDanmakuByMediaFile = `-- name: GetExternalDanmakuByMediaFile :many
SELECT id, media_file_id, source, video_id, part_index, comments_json, comment_count, created_at FROM external_danmaku
WHERE media_file_id = ?
ORDER BY source
`

func (q *Queries) GetExternalDanmakuByMediaFile(ctx context.Context, mediaFileID string) ([]ExternalDanmaku, error) {
	rows, err := q.db.QueryContext(ctx, getExternalDanmakuByMediaFile, mediaFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalDanmaku{}
	for rows.Next() {
		var i ExternalDanmaku
		if err := rows.Scan(
			&i.ID,
			&i.MediaFileID,
			&i.Source,
			&i.VideoID,
			&i.PartIndex,
			&i.CommentsJson,
			&i.CommentCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExternalDanmaku = `-- name: UpsertExternalDanmaku :one
INSERT INTO external_danmaku (media_file_id, source, video_id, part_index, comments_json, comment_count)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(media_file_id, source) DO UPDATE SET
    video_id = excluded.video_id,
    part_index = excluded.part_index,
    comments_json = excluded.comments_json,
    comment_count = excluded.comment_count,
    created_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, media_file_id, source, video_id, part_index, comments_json, comment_count, created_at
`

type UpsertExternalDanmakuParams struct {
	MediaFileID  string `json:"media_file_id"`
	Source       string `json:"source"`
	VideoID      string `json:"video_id"`
	PartIndex    int64  `json:"part_index"`
	CommentsJson string `json:"comments_json"`
	CommentCount int64  `json:"comment_count"`
}

func (q *Queries) UpsertExternalDanmaku(ctx context.Context, arg UpsertExternalDanmakuParams) (ExternalDanmaku, error) {
	row := q.db.QueryRowContext(ctx, upsertExternalDanmaku,
		arg.MediaFileID,
		arg.Source,
		arg.VideoID,
		arg.PartIndex,
		arg.CommentsJson,
		arg.CommentCount,
	)
	var i ExternalDanmaku
	err := row.Scan(
		&i.ID,
		&i.MediaFileID,
		&i.Source,
		&i.VideoID,
		&i.PartIndex,
		&i.CommentsJson,
		&i.CommentCount,
		&i.CreatedAt,
	)
	return i, err
}
