// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_devices.sql

package store

import (
	"context"
)

const countActiveExternalDevices = `-- name: CountActiveExternalDevices :one
SELECT COUNT(*) FROM external_devices WHERE revoked = 0
`

func (q *Queries) CountActiveExternalDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveExternalDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExternalDevice = `-- name: GetExternalDevice :one
SELECT device_id, user_id, client, device_name, first_seen, last_seen, revoked FROM external_devices WHERE device_id = ?
`

func (q *Queries) GetExternalDevice(ctx context.Context, deviceID string) (ExternalDevice, error) {
	row := q.db.QueryRowContext(ctx, getExternalDevice, deviceID)
	var i ExternalDevice
	err := row.Scan(
		&i.DeviceID,
		&i.UserID,
		&i.Client,
		&i.DeviceName,
		&i.FirstSeen,
		&i.LastSeen,
		&i.Revoked,
	)
	return i, err
}

const listExternalDevices = `-- name: ListExternalDevices :many
SELECT device_id, user_id, client, device_name, first_seen, last_seen, revoked FROM external_devices ORDER BY last_seen DESC
`

func (q *Queries) ListExternalDevices(ctx context.Context) ([]ExternalDevice, error) {
	rows, err := q.db.QueryContext(ctx, listExternalDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalDevice{}
	for rows.Next() {
		var i ExternalDevice
		if err := rows.Scan(
			&i.DeviceID,
			&i.UserID,
			&i.Client,
			&i.DeviceName,
			&i.FirstSeen,
			&i.LastSeen,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeExternalDevice = `-- name: RevokeExternalDevice :execrows
UPDATE external_devices SET revoked = 1 WHERE device_id = ?
`

func (q *Queries) RevokeExternalDevice(ctx context.Context, deviceID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeExternalDevice, deviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchExternalDevice = `-- name: TouchExternalDevice :exec
UPDATE external_devices SET last_seen = ? WHERE device_id = ?
`

type TouchExternalDeviceParams struct {
	LastSeen string `json:"last_seen"`
	DeviceID string `json:"device_id"`
}

func (q *Queries) TouchExternalDevice(ctx context.Context, arg TouchExternalDeviceParams) error {
	_, err := q.db.ExecContext(ctx, touchExternalDevice, arg.LastSeen, arg.DeviceID)
	return err
}

const upsertExternalDevice = `-- name: UpsertExternalDevice :one
INSERT INTO external_devices (device_id, user_id, client, device_name, first_seen, last_seen, revoked)
VALUES (?, ?, ?, ?, ?, ?, 0)
ON CONFLICT(device_id) DO UPDATE SET
    user_id = excluded.user_id,
    client = excluded.client,
    device_name = excluded.device_name,
    last_seen = excluded.last_seen,
    revoked = 0
RETURNING device_id, user_id, client, device_name, first_seen, last_seen, revoked
`

type UpsertExternalDeviceParams struct {
	DeviceID   string `json:"device_id"`
	UserID     string `json:"user_id"`
	Client     string `json:"client"`
	DeviceName string `json:"device_name"`
	FirstSeen  string `json:"first_seen"`
	LastSeen   string `json:"last_seen"`
}

func (q *Queries) UpsertExternalDevice(ctx context.Context, arg UpsertExternalDeviceParams) (ExternalDevice, error) {
	row := q.db.QueryRowContext(ctx, upsertExternalDevice,
		arg.DeviceID,
		arg.UserID,
		arg.Client,
		arg.DeviceName,
		arg.FirstSeen,
		arg.LastSeen,
	)
	var i ExternalDevice
	err := row.Scan(
		&i.DeviceID,
		&i.UserID,
		&i.Client,
		&i.DeviceName,
		&i.FirstSeen,
		&i.LastSeen,
		&i.Revoked,
	)
	return i, err
}
