// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hot_tags.sql

package store

import (
	"context"
	"database/sql"
)

const listHotTags = `-- name: ListHotTags :many
SELECT id, name, category, count, created_at
FROM hot_tags
ORDER BY count DESC, name ASC
`

func (q *Queries) ListHotTags(ctx context.Context) ([]HotTag, error) {
	rows, err := q.db.QueryContext(ctx, listHotTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotTag{}
	for rows.Next() {
		var i HotTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Count,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotTagsByCategory = `-- name: ListHotTagsByCategory :many
SELECT id, name, category, count, created_at
FROM hot_tags
WHERE category = ?
ORDER BY count DESC, name ASC
`

func (q *Queries) ListHotTagsByCategory(ctx context.Context, category string) ([]HotTag, error) {
	rows, err := q.db.QueryContext(ctx, listHotTagsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotTag{}
	for rows.Next() {
		var i HotTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Count,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHotTags = `-- name: SearchHotTags :many
SELECT id, name, category, count, created_at
FROM hot_tags
WHERE name LIKE '%' || ? || '%'
ORDER BY count DESC, name ASC
LIMIT 20
`

func (q *Queries) SearchHotTags(ctx context.Context, dollar_1 sql.NullString) ([]HotTag, error) {
	rows, err := q.db.QueryContext(ctx, searchHotTags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HotTag{}
	for rows.Next() {
		var i HotTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Count,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
