// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: libraries.sql

package store

import (
	"context"
	"database/sql"
)

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO libraries (id, name, path, enabled, scan_interval_minutes, source_type, source_config_encrypted, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
RETURNING id, name, path, enabled, scan_interval_minutes, last_scanned_at, created_at, updated_at, source_type, source_config_encrypted, rename_template, rename_auto
`

type CreateLibraryParams struct {
	ID                    string         `json:"id"`
	Name                  string         `json:"name"`
	Path                  string         `json:"path"`
	Enabled               int64          `json:"enabled"`
	ScanIntervalMinutes   int64          `json:"scan_interval_minutes"`
	SourceType            string         `json:"source_type"`
	SourceConfigEncrypted sql.NullString `json:"source_config_encrypted"`
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, createLibrary,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.Enabled,
		arg.ScanIntervalMinutes,
		arg.SourceType,
		arg.SourceConfigEncrypted,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Enabled,
		&i.ScanIntervalMinutes,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.SourceConfigEncrypted,
		&i.RenameTemplate,
		&i.RenameAuto,
	)
	return i, err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE FROM libraries WHERE id = ?
`

func (q *Queries) DeleteLibrary(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLibrary, id)
	return err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, path, enabled, scan_interval_minutes, last_scanned_at, created_at, updated_at, source_type, source_config_encrypted, rename_template, rename_auto FROM libraries WHERE id = ? LIMIT 1
`

func (q *Queries) GetLibrary(ctx context.Context, id string) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Enabled,
		&i.ScanIntervalMinutes,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.SourceConfigEncrypted,
		&i.RenameTemplate,
		&i.RenameAuto,
	)
	return i, err
}

const getLibraryWithStats = `-- name: GetLibraryWithStats :one
SELECT l.id, l.name, l.path, l.enabled, l.scan_interval_minutes, l.last_scanned_at, l.created_at, l.updated_at, l.source_type, l.source_config_encrypted, l.rename_template, l.rename_auto,
  COALESCE(s.file_count, 0) AS file_count,
  COALESCE(s.matched_count, 0) AS matched_count,
  COALESCE(s.unmatched_count, 0) AS unmatched_count,
  COALESCE(s.total_size_bytes, 0) AS total_size_bytes
FROM libraries l
LEFT JOIN (
  SELECT library_id,
    COUNT(*) AS file_count,
    SUM(CASE WHEN match_status != 'unmatched' THEN 1 ELSE 0 END) AS matched_count,
    SUM(CASE WHEN match_status = 'unmatched' THEN 1 ELSE 0 END) AS unmatched_count,
    COALESCE(SUM(size_bytes), 0) AS total_size_bytes
  FROM media_files GROUP BY library_id
) s ON l.id = s.library_id
WHERE l.id = ?
`

type GetLibraryWithStatsRow struct {
	ID                    string         `json:"id"`
	Name                  string         `json:"name"`
	Path                  string         `json:"path"`
	Enabled               int64          `json:"enabled"`
	ScanIntervalMinutes   int64          `json:"scan_interval_minutes"`
	LastScannedAt         sql.NullString `json:"last_scanned_at"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
	SourceType            string         `json:"source_type"`
	SourceConfigEncrypted sql.NullString `json:"source_config_encrypted"`
	RenameTemplate        string         `json:"rename_template"`
	RenameAuto            int64          `json:"rename_auto"`
	FileCount             int64          `json:"file_count"`
	MatchedCount          float64        `json:"matched_count"`
	UnmatchedCount        float64        `json:"unmatched_count"`
	TotalSizeBytes        interface{}    `json:"total_size_bytes"`
}

func (q *Queries) GetLibraryWithStats(ctx context.Context, id string) (GetLibraryWithStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getLibraryWithStats, id)
	var i GetLibraryWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Enabled,
		&i.ScanIntervalMinutes,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.SourceConfigEncrypted,
		&i.RenameTemplate,
		&i.RenameAuto,
		&i.FileCount,
		&i.MatchedCount,
		&i.UnmatchedCount,
		&i.TotalSizeBytes,
	)
	return i, err
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, path, enabled, scan_interval_minutes, last_scanned_at, created_at, updated_at, source_type, source_config_encrypted, rename_template, rename_auto FROM libraries ORDER BY name
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Enabled,
			&i.ScanIntervalMinutes,
			&i.LastScannedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceType,
			&i.SourceConfigEncrypted,
			&i.RenameTemplate,
			&i.RenameAuto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibrariesWithStats = `-- name: ListLibrariesWithStats :many
SELECT l.id, l.name, l.path, l.enabled, l.scan_interval_minutes, l.last_scanned_at, l.created_at, l.updated_at, l.source_type, l.source_config_encrypted, l.rename_template, l.rename_auto,
  COALESCE(s.file_count, 0) AS file_count,
  COALESCE(s.matched_count, 0) AS matched_count,
  COALESCE(s.unmatched_count, 0) AS unmatched_count,
  COALESCE(s.total_size_bytes, 0) AS total_size_bytes
FROM libraries l
LEFT JOIN (
  SELECT library_id,
    COUNT(*) AS file_count,
    SUM(CASE WHEN match_status != 'unmatched' THEN 1 ELSE 0 END) AS matched_count,
    SUM(CASE WHEN match_status = 'unmatched' THEN 1 ELSE 0 END) AS unmatched_count,
    COALESCE(SUM(size_bytes), 0) AS total_size_bytes
  FROM media_files GROUP BY library_id
) s ON l.id = s.library_id
ORDER BY l.name ASC
`

type ListLibrariesWithStatsRow struct {
	ID                    string         `json:"id"`
	Name                  string         `json:"name"`
	Path                  string         `json:"path"`
	Enabled               int64          `json:"enabled"`
	ScanIntervalMinutes   int64          `json:"scan_interval_minutes"`
	LastScannedAt         sql.NullString `json:"last_scanned_at"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
	SourceType            string         `json:"source_type"`
	SourceConfigEncrypted sql.NullString `json:"source_config_encrypted"`
	RenameTemplate        string         `json:"rename_template"`
	RenameAuto            int64          `json:"rename_auto"`
	FileCount             int64          `json:"file_count"`
	MatchedCount          float64        `json:"matched_count"`
	UnmatchedCount        float64        `json:"unmatched_count"`
	TotalSizeBytes        interface{}    `json:"total_size_bytes"`
}

func (q *Queries) ListLibrariesWithStats(ctx context.Context) ([]ListLibrariesWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLibrariesWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibrariesWithStatsRow{}
	for rows.Next() {
		var i ListLibrariesWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Enabled,
			&i.ScanIntervalMinutes,
			&i.LastScannedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceType,
			&i.SourceConfigEncrypted,
			&i.RenameTemplate,
			&i.RenameAuto,
			&i.FileCount,
			&i.MatchedCount,
			&i.UnmatchedCount,
			&i.TotalSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLibrary = `-- name: UpdateLibrary :one
UPDATE libraries
SET name = ?, path = ?, enabled = ?, scan_interval_minutes = ?,
    source_type = ?, source_config_encrypted = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, name, path, enabled, scan_interval_minutes, last_scanned_at, created_at, updated_at, source_type, source_config_encrypted, rename_template, rename_auto
`

type UpdateLibraryParams struct {
	Name                  string         `json:"name"`
	Path                  string         `json:"path"`
	Enabled               int64          `json:"enabled"`
	ScanIntervalMinutes   int64          `json:"scan_interval_minutes"`
	SourceType            string         `json:"source_type"`
	SourceConfigEncrypted sql.NullString `json:"source_config_encrypted"`
	ID                    string         `json:"id"`
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, updateLibrary,
		arg.Name,
		arg.Path,
		arg.Enabled,
		arg.ScanIntervalMinutes,
		arg.SourceType,
		arg.SourceConfigEncrypted,
		arg.ID,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Enabled,
		&i.ScanIntervalMinutes,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.SourceConfigEncrypted,
		&i.RenameTemplate,
		&i.RenameAuto,
	)
	return i, err
}

const updateLibraryLastScanned = `-- name: UpdateLibraryLastScanned :exec
UPDATE libraries
SET last_scanned_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    updated_at      = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

func (q *Queries) UpdateLibraryLastScanned(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateLibraryLastScanned, id)
	return err
}

const updateLibraryRenameConfig = `-- name: UpdateLibraryRenameConfig :exec
UPDATE libraries
SET rename_template = ?1,
    rename_auto = ?2,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?3
`

type UpdateLibraryRenameConfigParams struct {
	Template string `json:"template"`
	Auto     int64  `json:"auto"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateLibraryRenameConfig(ctx context.Context, arg UpdateLibraryRenameConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateLibraryRenameConfig, arg.Template, arg.Auto, arg.ID)
	return err
}
