// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: libraries.sql

package store

import (
	"context"
)

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO libraries (id, name, path, enabled, scan_interval_minutes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
RETURNING id, name, path, enabled, scan_interval_minutes, last_scanned_at, created_at, updated_at
`

type CreateLibraryParams struct {
	ID                  string `json:"id"`
	Name                string `json:"name"`
	Path                string `json:"path"`
	Enabled             int64  `json:"enabled"`
	ScanIntervalMinutes int64  `json:"scan_interval_minutes"`
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, createLibrary,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.Enabled,
		arg.ScanIntervalMinutes,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Enabled,
		&i.ScanIntervalMinutes,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE FROM libraries WHERE id = ?
`

func (q *Queries) DeleteLibrary(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLibrary, id)
	return err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, path, enabled, scan_interval_minutes, last_scanned_at, created_at, updated_at FROM libraries WHERE id = ? LIMIT 1
`

func (q *Queries) GetLibrary(ctx context.Context, id string) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Enabled,
		&i.ScanIntervalMinutes,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, path, enabled, scan_interval_minutes, last_scanned_at, created_at, updated_at FROM libraries ORDER BY name
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Enabled,
			&i.ScanIntervalMinutes,
			&i.LastScannedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLibrary = `-- name: UpdateLibrary :one
UPDATE libraries
SET name = ?, path = ?, enabled = ?, scan_interval_minutes = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
RETURNING id, name, path, enabled, scan_interval_minutes, last_scanned_at, created_at, updated_at
`

type UpdateLibraryParams struct {
	Name                string `json:"name"`
	Path                string `json:"path"`
	Enabled             int64  `json:"enabled"`
	ScanIntervalMinutes int64  `json:"scan_interval_minutes"`
	ID                  string `json:"id"`
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, updateLibrary,
		arg.Name,
		arg.Path,
		arg.Enabled,
		arg.ScanIntervalMinutes,
		arg.ID,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Enabled,
		&i.ScanIntervalMinutes,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLibraryLastScanned = `-- name: UpdateLibraryLastScanned :exec
UPDATE libraries
SET last_scanned_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    updated_at      = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

func (q *Queries) UpdateLibraryLastScanned(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateLibraryLastScanned, id)
	return err
}
