// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_files.sql

package store

import (
	"context"
	"database/sql"
)

const clearMediaFileMatch = `-- name: ClearMediaFileMatch :exec
UPDATE media_files
SET dandanplay_anime_id = NULL, dandanplay_episode_id = NULL,
    episode_id = NULL, match_status = 'unmatched',
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

func (q *Queries) ClearMediaFileMatch(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearMediaFileMatch, id)
	return err
}

const countMediaFilesByLibrary = `-- name: CountMediaFilesByLibrary :one
SELECT COUNT(*) FROM media_files WHERE library_id = ?
`

func (q *Queries) CountMediaFilesByLibrary(ctx context.Context, libraryID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaFilesByLibrary, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMediaFilesByStatus = `-- name: CountMediaFilesByStatus :one
SELECT COUNT(*) AS total
FROM media_files
WHERE library_id = ?
  AND (? = 'all' OR (? = 'matched' AND match_status != 'unmatched') OR match_status = ?)
  AND (? = '' OR filename LIKE '%' || ? || '%')
`

type CountMediaFilesByStatusParams struct {
	LibraryID   string         `json:"library_id"`
	Column2     interface{}    `json:"column_2"`
	Column3     interface{}    `json:"column_3"`
	MatchStatus string         `json:"match_status"`
	Column5     interface{}    `json:"column_5"`
	Column6     sql.NullString `json:"column_6"`
}

func (q *Queries) CountMediaFilesByStatus(ctx context.Context, arg CountMediaFilesByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaFilesByStatus,
		arg.LibraryID,
		arg.Column2,
		arg.Column3,
		arg.MatchStatus,
		arg.Column5,
		arg.Column6,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countMediaFilesPerEpisodeByAnime = `-- name: CountMediaFilesPerEpisodeByAnime :many
SELECT e.id AS episode_id, e.episode_number, COUNT(mf.id) AS file_count
FROM episodes e
JOIN media_files mf ON mf.episode_id = e.id
WHERE e.anime_id = ?1
GROUP BY e.id, e.episode_number
`

type CountMediaFilesPerEpisodeByAnimeRow struct {
	EpisodeID     string  `json:"episode_id"`
	EpisodeNumber float64 `json:"episode_number"`
	FileCount     int64   `json:"file_count"`
}

func (q *Queries) CountMediaFilesPerEpisodeByAnime(ctx context.Context, animeID string) ([]CountMediaFilesPerEpisodeByAnimeRow, error) {
	rows, err := q.db.QueryContext(ctx, countMediaFilesPerEpisodeByAnime, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMediaFilesPerEpisodeByAnimeRow{}
	for rows.Next() {
		var i CountMediaFilesPerEpisodeByAnimeRow
		if err := rows.Scan(&i.EpisodeID, &i.EpisodeNumber, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMediaFilesPerEpisodeByLibrary = `-- name: CountMediaFilesPerEpisodeByLibrary :many
SELECT e.anime_id, e.id AS episode_id, e.episode_number, COUNT(mf.id) AS file_count
FROM episodes e
JOIN media_files mf ON mf.episode_id = e.id
JOIN anime a ON a.id = e.anime_id
WHERE a.library_id = ?1
GROUP BY e.anime_id, e.id, e.episode_number
`

type CountMediaFilesPerEpisodeByLibraryRow struct {
	AnimeID       string  `json:"anime_id"`
	EpisodeID     string  `json:"episode_id"`
	EpisodeNumber float64 `json:"episode_number"`
	FileCount     int64   `json:"file_count"`
}

func (q *Queries) CountMediaFilesPerEpisodeByLibrary(ctx context.Context, libraryID sql.NullString) ([]CountMediaFilesPerEpisodeByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, countMediaFilesPerEpisodeByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMediaFilesPerEpisodeByLibraryRow{}
	for rows.Next() {
		var i CountMediaFilesPerEpisodeByLibraryRow
		if err := rows.Scan(
			&i.AnimeID,
			&i.EpisodeID,
			&i.EpisodeNumber,
			&i.FileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMediaFile = `-- name: DeleteMediaFile :exec
DELETE FROM media_files WHERE path = ?
`

func (q *Queries) DeleteMediaFile(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteMediaFile, path)
	return err
}

const deleteMediaFileByID = `-- name: DeleteMediaFileByID :exec
DELETE FROM media_files WHERE id = ?
`

func (q *Queries) DeleteMediaFileByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMediaFileByID, id)
	return err
}

const getMediaFileByID = `-- name: GetMediaFileByID :one
SELECT id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at, dandanplay_anime_id, bangumi_subject_id, bangumi_episode_id FROM media_files WHERE id = ? LIMIT 1
`

func (q *Queries) GetMediaFileByID(ctx context.Context, id string) (MediaFile, error) {
	row := q.db.QueryRowContext(ctx, getMediaFileByID, id)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.LibraryID,
		&i.Path,
		&i.Filename,
		&i.SizeBytes,
		&i.DurationSeconds,
		&i.ContainerFormat,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Width,
		&i.Height,
		&i.FileHash,
		&i.DandanplayEpisodeID,
		&i.MatchStatus,
		&i.VideoTracks,
		&i.AudioTracks,
		&i.SubtitleTracks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DandanplayAnimeID,
		&i.BangumiSubjectID,
		&i.BangumiEpisodeID,
	)
	return i, err
}

const linkMediaFileToEpisode = `-- name: LinkMediaFileToEpisode :exec
UPDATE media_files
SET episode_id = ?1,
    match_status = 'manual',
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2
`

type LinkMediaFileToEpisodeParams struct {
	EpisodeID sql.NullString `json:"episode_id"`
	ID        string         `json:"id"`
}

func (q *Queries) LinkMediaFileToEpisode(ctx context.Context, arg LinkMediaFileToEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, linkMediaFileToEpisode, arg.EpisodeID, arg.ID)
	return err
}

const listAllUnmatchedMediaFilesByLibrary = `-- name: ListAllUnmatchedMediaFilesByLibrary :many
SELECT id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at, dandanplay_anime_id, bangumi_subject_id, bangumi_episode_id FROM media_files
WHERE library_id = ? AND match_status = 'unmatched'
`

func (q *Queries) ListAllUnmatchedMediaFilesByLibrary(ctx context.Context, libraryID string) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, listAllUnmatchedMediaFilesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFile{}
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.LibraryID,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.ContainerFormat,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Width,
			&i.Height,
			&i.FileHash,
			&i.DandanplayEpisodeID,
			&i.MatchStatus,
			&i.VideoTracks,
			&i.AudioTracks,
			&i.SubtitleTracks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DandanplayAnimeID,
			&i.BangumiSubjectID,
			&i.BangumiEpisodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBangumiMatchedUnlinkedMediaFiles = `-- name: ListBangumiMatchedUnlinkedMediaFiles :many
SELECT id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at, dandanplay_anime_id, bangumi_subject_id, bangumi_episode_id FROM media_files
WHERE library_id = ? AND bangumi_subject_id IS NOT NULL AND episode_id IS NULL
`

func (q *Queries) ListBangumiMatchedUnlinkedMediaFiles(ctx context.Context, libraryID string) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, listBangumiMatchedUnlinkedMediaFiles, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFile{}
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.LibraryID,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.ContainerFormat,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Width,
			&i.Height,
			&i.FileHash,
			&i.DandanplayEpisodeID,
			&i.MatchStatus,
			&i.VideoTracks,
			&i.AudioTracks,
			&i.SubtitleTracks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DandanplayAnimeID,
			&i.BangumiSubjectID,
			&i.BangumiEpisodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuplicateEpisodesByAnime = `-- name: ListDuplicateEpisodesByAnime :many
SELECT e.id AS episode_id, e.episode_number,
       e.preferred_media_file_id, e.preferred_manually_set,
       COUNT(mf.id) AS file_count,
       SUM(mf.size_bytes) AS total_bytes
FROM episodes e
JOIN media_files mf ON mf.episode_id = e.id
WHERE e.anime_id = ?1
GROUP BY e.id
HAVING file_count >= 2
`

type ListDuplicateEpisodesByAnimeRow struct {
	EpisodeID            string          `json:"episode_id"`
	EpisodeNumber        float64         `json:"episode_number"`
	PreferredMediaFileID sql.NullString  `json:"preferred_media_file_id"`
	PreferredManuallySet int64           `json:"preferred_manually_set"`
	FileCount            int64           `json:"file_count"`
	TotalBytes           sql.NullFloat64 `json:"total_bytes"`
}

func (q *Queries) ListDuplicateEpisodesByAnime(ctx context.Context, animeID string) ([]ListDuplicateEpisodesByAnimeRow, error) {
	rows, err := q.db.QueryContext(ctx, listDuplicateEpisodesByAnime, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateEpisodesByAnimeRow{}
	for rows.Next() {
		var i ListDuplicateEpisodesByAnimeRow
		if err := rows.Scan(
			&i.EpisodeID,
			&i.EpisodeNumber,
			&i.PreferredMediaFileID,
			&i.PreferredManuallySet,
			&i.FileCount,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuplicateEpisodesByLibrary = `-- name: ListDuplicateEpisodesByLibrary :many
SELECT a.id AS anime_id, a.title,
       e.id AS episode_id, e.episode_number,
       e.preferred_media_file_id, e.preferred_manually_set,
       COUNT(mf.id) AS file_count,
       SUM(mf.size_bytes) AS total_bytes
FROM episodes e
JOIN anime a ON a.id = e.anime_id
JOIN media_files mf ON mf.episode_id = e.id
WHERE a.library_id = ?1
GROUP BY e.id
HAVING file_count >= 2
`

type ListDuplicateEpisodesByLibraryRow struct {
	AnimeID              string          `json:"anime_id"`
	Title                string          `json:"title"`
	EpisodeID            string          `json:"episode_id"`
	EpisodeNumber        float64         `json:"episode_number"`
	PreferredMediaFileID sql.NullString  `json:"preferred_media_file_id"`
	PreferredManuallySet int64           `json:"preferred_manually_set"`
	FileCount            int64           `json:"file_count"`
	TotalBytes           sql.NullFloat64 `json:"total_bytes"`
}

func (q *Queries) ListDuplicateEpisodesByLibrary(ctx context.Context, libraryID sql.NullString) ([]ListDuplicateEpisodesByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listDuplicateEpisodesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateEpisodesByLibraryRow{}
	for rows.Next() {
		var i ListDuplicateEpisodesByLibraryRow
		if err := rows.Scan(
			&i.AnimeID,
			&i.Title,
			&i.EpisodeID,
			&i.EpisodeNumber,
			&i.PreferredMediaFileID,
			&i.PreferredManuallySet,
			&i.FileCount,
			&i.TotalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchedUnlinkedMediaFiles = `-- name: ListMatchedUnlinkedMediaFiles :many
SELECT id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at, dandanplay_anime_id, bangumi_subject_id, bangumi_episode_id FROM media_files
WHERE library_id = ? AND dandanplay_episode_id IS NOT NULL AND episode_id IS NULL
`

func (q *Queries) ListMatchedUnlinkedMediaFiles(ctx context.Context, libraryID string) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, listMatchedUnlinkedMediaFiles, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFile{}
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.LibraryID,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.ContainerFormat,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Width,
			&i.Height,
			&i.FileHash,
			&i.DandanplayEpisodeID,
			&i.MatchStatus,
			&i.VideoTracks,
			&i.AudioTracks,
			&i.SubtitleTracks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DandanplayAnimeID,
			&i.BangumiSubjectID,
			&i.BangumiEpisodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaFilePathsByLibrary = `-- name: ListMediaFilePathsByLibrary :many
SELECT path FROM media_files WHERE library_id = ?
`

func (q *Queries) ListMediaFilePathsByLibrary(ctx context.Context, libraryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMediaFilePathsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaFileTreeByLibrary = `-- name: ListMediaFileTreeByLibrary :many
SELECT mf.id, mf.path, mf.filename, mf.size_bytes, mf.match_status,
       COALESCE(a.title, '') AS matched_anime_title,
       COALESCE(e.episode_number, 0) AS matched_episode_sort,
       COALESCE(a.bangumi_id, 0) AS matched_bangumi_id,
       (SELECT COUNT(*) FROM subtitle_files sf WHERE sf.media_file_id = mf.id) AS subtitle_count
FROM media_files mf
LEFT JOIN episodes e ON mf.episode_id = e.id
LEFT JOIN anime a ON e.anime_id = a.id
WHERE mf.library_id = ?
ORDER BY mf.path ASC
`

type ListMediaFileTreeByLibraryRow struct {
	ID                 string  `json:"id"`
	Path               string  `json:"path"`
	Filename           string  `json:"filename"`
	SizeBytes          int64   `json:"size_bytes"`
	MatchStatus        string  `json:"match_status"`
	MatchedAnimeTitle  string  `json:"matched_anime_title"`
	MatchedEpisodeSort float64 `json:"matched_episode_sort"`
	MatchedBangumiID   int64   `json:"matched_bangumi_id"`
	SubtitleCount      int64   `json:"subtitle_count"`
}

func (q *Queries) ListMediaFileTreeByLibrary(ctx context.Context, libraryID string) ([]ListMediaFileTreeByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediaFileTreeByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaFileTreeByLibraryRow{}
	for rows.Next() {
		var i ListMediaFileTreeByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.MatchStatus,
			&i.MatchedAnimeTitle,
			&i.MatchedEpisodeSort,
			&i.MatchedBangumiID,
			&i.SubtitleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaFilesByAnime = `-- name: ListMediaFilesByAnime :many
SELECT mf.id, mf.episode_id, mf.library_id, mf.path, mf.filename, mf.size_bytes, mf.duration_seconds, mf.container_format, mf.video_codec, mf.audio_codec, mf.width, mf.height, mf.file_hash, mf.dandanplay_episode_id, mf.match_status, mf.video_tracks, mf.audio_tracks, mf.subtitle_tracks, mf.created_at, mf.updated_at, mf.dandanplay_anime_id, mf.bangumi_subject_id, mf.bangumi_episode_id FROM media_files mf
JOIN episodes e ON e.id = mf.episode_id
WHERE e.anime_id = ?
`

func (q *Queries) ListMediaFilesByAnime(ctx context.Context, animeID string) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, listMediaFilesByAnime, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFile{}
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.LibraryID,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.ContainerFormat,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Width,
			&i.Height,
			&i.FileHash,
			&i.DandanplayEpisodeID,
			&i.MatchStatus,
			&i.VideoTracks,
			&i.AudioTracks,
			&i.SubtitleTracks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DandanplayAnimeID,
			&i.BangumiSubjectID,
			&i.BangumiEpisodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaFilesByEpisode = `-- name: ListMediaFilesByEpisode :many
SELECT id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at, dandanplay_anime_id, bangumi_subject_id, bangumi_episode_id FROM media_files WHERE episode_id = ? ORDER BY size_bytes DESC
`

func (q *Queries) ListMediaFilesByEpisode(ctx context.Context, episodeID sql.NullString) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, listMediaFilesByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFile{}
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.LibraryID,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.ContainerFormat,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Width,
			&i.Height,
			&i.FileHash,
			&i.DandanplayEpisodeID,
			&i.MatchStatus,
			&i.VideoTracks,
			&i.AudioTracks,
			&i.SubtitleTracks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DandanplayAnimeID,
			&i.BangumiSubjectID,
			&i.BangumiEpisodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaFilesByLibrary = `-- name: ListMediaFilesByLibrary :many
SELECT mf.id, mf.episode_id, mf.library_id, mf.path, mf.filename, mf.size_bytes, mf.duration_seconds, mf.container_format, mf.video_codec, mf.audio_codec, mf.width, mf.height, mf.file_hash, mf.dandanplay_episode_id, mf.match_status, mf.video_tracks, mf.audio_tracks, mf.subtitle_tracks, mf.created_at, mf.updated_at, mf.dandanplay_anime_id, mf.bangumi_subject_id, mf.bangumi_episode_id,
       COALESCE(a.title, '') AS matched_anime_title,
       COALESCE(e.episode_number, 0) AS matched_episode_sort,
       COALESCE(a.bangumi_id, 0) AS matched_bangumi_id,
       (SELECT COUNT(*) FROM subtitle_files sf WHERE sf.media_file_id = mf.id) AS subtitle_count
FROM media_files mf
LEFT JOIN episodes e ON mf.episode_id = e.id
LEFT JOIN anime a ON e.anime_id = a.id
WHERE mf.library_id = ?
  AND (? = 'all' OR (? = 'matched' AND mf.match_status != 'unmatched') OR mf.match_status = ?)
  AND (? = '' OR mf.filename LIKE '%' || ? || '%')
ORDER BY mf.filename ASC
LIMIT ? OFFSET ?
`

type ListMediaFilesByLibraryParams struct {
	LibraryID   string         `json:"library_id"`
	Column2     interface{}    `json:"column_2"`
	Column3     interface{}    `json:"column_3"`
	MatchStatus string         `json:"match_status"`
	Column5     interface{}    `json:"column_5"`
	Column6     sql.NullString `json:"column_6"`
	Limit       int64          `json:"limit"`
	Offset      int64          `json:"offset"`
}

type ListMediaFilesByLibraryRow struct {
	ID                  string         `json:"id"`
	EpisodeID           sql.NullString `json:"episode_id"`
	LibraryID           string         `json:"library_id"`
	Path                string         `json:"path"`
	Filename            string         `json:"filename"`
	SizeBytes           int64          `json:"size_bytes"`
	DurationSeconds     sql.NullInt64  `json:"duration_seconds"`
	ContainerFormat     sql.NullString `json:"container_format"`
	VideoCodec          sql.NullString `json:"video_codec"`
	AudioCodec          sql.NullString `json:"audio_codec"`
	Width               sql.NullInt64  `json:"width"`
	Height              sql.NullInt64  `json:"height"`
	FileHash            sql.NullString `json:"file_hash"`
	DandanplayEpisodeID sql.NullInt64  `json:"dandanplay_episode_id"`
	MatchStatus         string         `json:"match_status"`
	VideoTracks         string         `json:"video_tracks"`
	AudioTracks         string         `json:"audio_tracks"`
	SubtitleTracks      string         `json:"subtitle_tracks"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
	DandanplayAnimeID   sql.NullInt64  `json:"dandanplay_anime_id"`
	BangumiSubjectID    sql.NullInt64  `json:"bangumi_subject_id"`
	BangumiEpisodeID    sql.NullInt64  `json:"bangumi_episode_id"`
	MatchedAnimeTitle   string         `json:"matched_anime_title"`
	MatchedEpisodeSort  float64        `json:"matched_episode_sort"`
	MatchedBangumiID    int64          `json:"matched_bangumi_id"`
	SubtitleCount       int64          `json:"subtitle_count"`
}

func (q *Queries) ListMediaFilesByLibrary(ctx context.Context, arg ListMediaFilesByLibraryParams) ([]ListMediaFilesByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediaFilesByLibrary,
		arg.LibraryID,
		arg.Column2,
		arg.Column3,
		arg.MatchStatus,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaFilesByLibraryRow{}
	for rows.Next() {
		var i ListMediaFilesByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.LibraryID,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.ContainerFormat,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Width,
			&i.Height,
			&i.FileHash,
			&i.DandanplayEpisodeID,
			&i.MatchStatus,
			&i.VideoTracks,
			&i.AudioTracks,
			&i.SubtitleTracks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DandanplayAnimeID,
			&i.BangumiSubjectID,
			&i.BangumiEpisodeID,
			&i.MatchedAnimeTitle,
			&i.MatchedEpisodeSort,
			&i.MatchedBangumiID,
			&i.SubtitleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedMediaFilesByLibrary = `-- name: ListUnmatchedMediaFilesByLibrary :many
SELECT id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at, dandanplay_anime_id, bangumi_subject_id, bangumi_episode_id FROM media_files
WHERE library_id = ? AND match_status = 'unmatched' AND file_hash IS NOT NULL
`

func (q *Queries) ListUnmatchedMediaFilesByLibrary(ctx context.Context, libraryID string) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, listUnmatchedMediaFilesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFile{}
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.LibraryID,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.ContainerFormat,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Width,
			&i.Height,
			&i.FileHash,
			&i.DandanplayEpisodeID,
			&i.MatchStatus,
			&i.VideoTracks,
			&i.AudioTracks,
			&i.SubtitleTracks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DandanplayAnimeID,
			&i.BangumiSubjectID,
			&i.BangumiEpisodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaFileBangumiIDs = `-- name: UpdateMediaFileBangumiIDs :exec
UPDATE media_files
SET bangumi_subject_id = ?, bangumi_episode_id = ?, match_status = 'auto',
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateMediaFileBangumiIDsParams struct {
	BangumiSubjectID sql.NullInt64 `json:"bangumi_subject_id"`
	BangumiEpisodeID sql.NullInt64 `json:"bangumi_episode_id"`
	ID               string        `json:"id"`
}

func (q *Queries) UpdateMediaFileBangumiIDs(ctx context.Context, arg UpdateMediaFileBangumiIDsParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFileBangumiIDs, arg.BangumiSubjectID, arg.BangumiEpisodeID, arg.ID)
	return err
}

const updateMediaFileDandanplayID = `-- name: UpdateMediaFileDandanplayID :exec
UPDATE media_files
SET dandanplay_episode_id = ?, match_status = 'auto',
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateMediaFileDandanplayIDParams struct {
	DandanplayEpisodeID sql.NullInt64 `json:"dandanplay_episode_id"`
	ID                  string        `json:"id"`
}

func (q *Queries) UpdateMediaFileDandanplayID(ctx context.Context, arg UpdateMediaFileDandanplayIDParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFileDandanplayID, arg.DandanplayEpisodeID, arg.ID)
	return err
}

const updateMediaFileDandanplayIDs = `-- name: UpdateMediaFileDandanplayIDs :exec
UPDATE media_files
SET dandanplay_episode_id = ?, dandanplay_anime_id = ?, match_status = 'auto',
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateMediaFileDandanplayIDsParams struct {
	DandanplayEpisodeID sql.NullInt64 `json:"dandanplay_episode_id"`
	DandanplayAnimeID   sql.NullInt64 `json:"dandanplay_anime_id"`
	ID                  string        `json:"id"`
}

func (q *Queries) UpdateMediaFileDandanplayIDs(ctx context.Context, arg UpdateMediaFileDandanplayIDsParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFileDandanplayIDs, arg.DandanplayEpisodeID, arg.DandanplayAnimeID, arg.ID)
	return err
}

const updateMediaFileEpisodeID = `-- name: UpdateMediaFileEpisodeID :exec
UPDATE media_files
SET episode_id = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateMediaFileEpisodeIDParams struct {
	EpisodeID sql.NullString `json:"episode_id"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateMediaFileEpisodeID(ctx context.Context, arg UpdateMediaFileEpisodeIDParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFileEpisodeID, arg.EpisodeID, arg.ID)
	return err
}

const updateMediaFileHash = `-- name: UpdateMediaFileHash :exec
UPDATE media_files
SET file_hash = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateMediaFileHashParams struct {
	FileHash sql.NullString `json:"file_hash"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateMediaFileHash(ctx context.Context, arg UpdateMediaFileHashParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFileHash, arg.FileHash, arg.ID)
	return err
}

const updateMediaFileMatch = `-- name: UpdateMediaFileMatch :exec
UPDATE media_files
SET dandanplay_anime_id = ?, dandanplay_episode_id = ?, match_status = 'manual',
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateMediaFileMatchParams struct {
	DandanplayAnimeID   sql.NullInt64 `json:"dandanplay_anime_id"`
	DandanplayEpisodeID sql.NullInt64 `json:"dandanplay_episode_id"`
	ID                  string        `json:"id"`
}

func (q *Queries) UpdateMediaFileMatch(ctx context.Context, arg UpdateMediaFileMatchParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFileMatch, arg.DandanplayAnimeID, arg.DandanplayEpisodeID, arg.ID)
	return err
}

const updateMediaFilePath = `-- name: UpdateMediaFilePath :exec
UPDATE media_files SET path = ?, filename = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
`

type UpdateMediaFilePathParams struct {
	Path     string `json:"path"`
	Filename string `json:"filename"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateMediaFilePath(ctx context.Context, arg UpdateMediaFilePathParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFilePath, arg.Path, arg.Filename, arg.ID)
	return err
}

const upsertMediaFile = `-- name: UpsertMediaFile :one
INSERT INTO media_files (id, library_id, path, filename, size_bytes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
ON CONFLICT(path) DO UPDATE SET
    filename   = excluded.filename,
    size_bytes = excluded.size_bytes,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at, dandanplay_anime_id, bangumi_subject_id, bangumi_episode_id
`

type UpsertMediaFileParams struct {
	ID        string `json:"id"`
	LibraryID string `json:"library_id"`
	Path      string `json:"path"`
	Filename  string `json:"filename"`
	SizeBytes int64  `json:"size_bytes"`
}

func (q *Queries) UpsertMediaFile(ctx context.Context, arg UpsertMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRowContext(ctx, upsertMediaFile,
		arg.ID,
		arg.LibraryID,
		arg.Path,
		arg.Filename,
		arg.SizeBytes,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.LibraryID,
		&i.Path,
		&i.Filename,
		&i.SizeBytes,
		&i.DurationSeconds,
		&i.ContainerFormat,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Width,
		&i.Height,
		&i.FileHash,
		&i.DandanplayEpisodeID,
		&i.MatchStatus,
		&i.VideoTracks,
		&i.AudioTracks,
		&i.SubtitleTracks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DandanplayAnimeID,
		&i.BangumiSubjectID,
		&i.BangumiEpisodeID,
	)
	return i, err
}
