// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_files.sql

package store

import (
	"context"
	"database/sql"
)

const countMediaFilesByLibrary = `-- name: CountMediaFilesByLibrary :one
SELECT COUNT(*) FROM media_files WHERE library_id = ?
`

func (q *Queries) CountMediaFilesByLibrary(ctx context.Context, libraryID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaFilesByLibrary, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMediaFile = `-- name: DeleteMediaFile :exec
DELETE FROM media_files WHERE path = ?
`

func (q *Queries) DeleteMediaFile(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteMediaFile, path)
	return err
}

const getMediaFileByID = `-- name: GetMediaFileByID :one
SELECT id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at, dandanplay_anime_id FROM media_files WHERE id = ? LIMIT 1
`

func (q *Queries) GetMediaFileByID(ctx context.Context, id string) (MediaFile, error) {
	row := q.db.QueryRowContext(ctx, getMediaFileByID, id)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.LibraryID,
		&i.Path,
		&i.Filename,
		&i.SizeBytes,
		&i.DurationSeconds,
		&i.ContainerFormat,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Width,
		&i.Height,
		&i.FileHash,
		&i.DandanplayEpisodeID,
		&i.MatchStatus,
		&i.VideoTracks,
		&i.AudioTracks,
		&i.SubtitleTracks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DandanplayAnimeID,
	)
	return i, err
}

const listMatchedUnlinkedMediaFiles = `-- name: ListMatchedUnlinkedMediaFiles :many
SELECT id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at, dandanplay_anime_id FROM media_files
WHERE library_id = ? AND dandanplay_episode_id IS NOT NULL AND episode_id IS NULL
`

func (q *Queries) ListMatchedUnlinkedMediaFiles(ctx context.Context, libraryID string) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, listMatchedUnlinkedMediaFiles, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFile{}
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.LibraryID,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.ContainerFormat,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Width,
			&i.Height,
			&i.FileHash,
			&i.DandanplayEpisodeID,
			&i.MatchStatus,
			&i.VideoTracks,
			&i.AudioTracks,
			&i.SubtitleTracks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DandanplayAnimeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaFilePathsByLibrary = `-- name: ListMediaFilePathsByLibrary :many
SELECT path FROM media_files WHERE library_id = ?
`

func (q *Queries) ListMediaFilePathsByLibrary(ctx context.Context, libraryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMediaFilePathsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedMediaFilesByLibrary = `-- name: ListUnmatchedMediaFilesByLibrary :many
SELECT id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at, dandanplay_anime_id FROM media_files
WHERE library_id = ? AND match_status = 'unmatched' AND file_hash IS NOT NULL
`

func (q *Queries) ListUnmatchedMediaFilesByLibrary(ctx context.Context, libraryID string) ([]MediaFile, error) {
	rows, err := q.db.QueryContext(ctx, listUnmatchedMediaFilesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaFile{}
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.EpisodeID,
			&i.LibraryID,
			&i.Path,
			&i.Filename,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.ContainerFormat,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.Width,
			&i.Height,
			&i.FileHash,
			&i.DandanplayEpisodeID,
			&i.MatchStatus,
			&i.VideoTracks,
			&i.AudioTracks,
			&i.SubtitleTracks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DandanplayAnimeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaFileDandanplayID = `-- name: UpdateMediaFileDandanplayID :exec
UPDATE media_files
SET dandanplay_episode_id = ?, match_status = 'auto',
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateMediaFileDandanplayIDParams struct {
	DandanplayEpisodeID sql.NullInt64 `json:"dandanplay_episode_id"`
	ID                  string        `json:"id"`
}

func (q *Queries) UpdateMediaFileDandanplayID(ctx context.Context, arg UpdateMediaFileDandanplayIDParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFileDandanplayID, arg.DandanplayEpisodeID, arg.ID)
	return err
}

const updateMediaFileDandanplayIDs = `-- name: UpdateMediaFileDandanplayIDs :exec
UPDATE media_files
SET dandanplay_episode_id = ?, dandanplay_anime_id = ?, match_status = 'auto',
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateMediaFileDandanplayIDsParams struct {
	DandanplayEpisodeID sql.NullInt64 `json:"dandanplay_episode_id"`
	DandanplayAnimeID   sql.NullInt64 `json:"dandanplay_anime_id"`
	ID                  string        `json:"id"`
}

func (q *Queries) UpdateMediaFileDandanplayIDs(ctx context.Context, arg UpdateMediaFileDandanplayIDsParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFileDandanplayIDs, arg.DandanplayEpisodeID, arg.DandanplayAnimeID, arg.ID)
	return err
}

const updateMediaFileEpisodeID = `-- name: UpdateMediaFileEpisodeID :exec
UPDATE media_files
SET episode_id = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateMediaFileEpisodeIDParams struct {
	EpisodeID sql.NullString `json:"episode_id"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateMediaFileEpisodeID(ctx context.Context, arg UpdateMediaFileEpisodeIDParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFileEpisodeID, arg.EpisodeID, arg.ID)
	return err
}

const updateMediaFileHash = `-- name: UpdateMediaFileHash :exec
UPDATE media_files
SET file_hash = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?
`

type UpdateMediaFileHashParams struct {
	FileHash sql.NullString `json:"file_hash"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateMediaFileHash(ctx context.Context, arg UpdateMediaFileHashParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaFileHash, arg.FileHash, arg.ID)
	return err
}

const upsertMediaFile = `-- name: UpsertMediaFile :one
INSERT INTO media_files (id, library_id, path, filename, size_bytes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
ON CONFLICT(path) DO UPDATE SET
    filename   = excluded.filename,
    size_bytes = excluded.size_bytes,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at, dandanplay_anime_id
`

type UpsertMediaFileParams struct {
	ID        string `json:"id"`
	LibraryID string `json:"library_id"`
	Path      string `json:"path"`
	Filename  string `json:"filename"`
	SizeBytes int64  `json:"size_bytes"`
}

func (q *Queries) UpsertMediaFile(ctx context.Context, arg UpsertMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRowContext(ctx, upsertMediaFile,
		arg.ID,
		arg.LibraryID,
		arg.Path,
		arg.Filename,
		arg.SizeBytes,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.LibraryID,
		&i.Path,
		&i.Filename,
		&i.SizeBytes,
		&i.DurationSeconds,
		&i.ContainerFormat,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Width,
		&i.Height,
		&i.FileHash,
		&i.DandanplayEpisodeID,
		&i.MatchStatus,
		&i.VideoTracks,
		&i.AudioTracks,
		&i.SubtitleTracks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DandanplayAnimeID,
	)
	return i, err
}
