// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_files.sql

package store

import (
	"context"
)

const countMediaFilesByLibrary = `-- name: CountMediaFilesByLibrary :one
SELECT COUNT(*) FROM media_files WHERE library_id = ?
`

func (q *Queries) CountMediaFilesByLibrary(ctx context.Context, libraryID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaFilesByLibrary, libraryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMediaFile = `-- name: DeleteMediaFile :exec
DELETE FROM media_files WHERE path = ?
`

func (q *Queries) DeleteMediaFile(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteMediaFile, path)
	return err
}

const listMediaFilePathsByLibrary = `-- name: ListMediaFilePathsByLibrary :many
SELECT path FROM media_files WHERE library_id = ?
`

func (q *Queries) ListMediaFilePathsByLibrary(ctx context.Context, libraryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMediaFilePathsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMediaFile = `-- name: UpsertMediaFile :one
INSERT INTO media_files (id, library_id, path, filename, size_bytes, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
ON CONFLICT(path) DO UPDATE SET
    filename   = excluded.filename,
    size_bytes = excluded.size_bytes,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, episode_id, library_id, path, filename, size_bytes, duration_seconds, container_format, video_codec, audio_codec, width, height, file_hash, dandanplay_episode_id, match_status, video_tracks, audio_tracks, subtitle_tracks, created_at, updated_at
`

type UpsertMediaFileParams struct {
	ID        string `json:"id"`
	LibraryID string `json:"library_id"`
	Path      string `json:"path"`
	Filename  string `json:"filename"`
	SizeBytes int64  `json:"size_bytes"`
}

func (q *Queries) UpsertMediaFile(ctx context.Context, arg UpsertMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRowContext(ctx, upsertMediaFile,
		arg.ID,
		arg.LibraryID,
		arg.Path,
		arg.Filename,
		arg.SizeBytes,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.EpisodeID,
		&i.LibraryID,
		&i.Path,
		&i.Filename,
		&i.SizeBytes,
		&i.DurationSeconds,
		&i.ContainerFormat,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.Width,
		&i.Height,
		&i.FileHash,
		&i.DandanplayEpisodeID,
		&i.MatchStatus,
		&i.VideoTracks,
		&i.AudioTracks,
		&i.SubtitleTracks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
