// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Anime struct {
	ID                   string         `json:"id"`
	LibraryID            sql.NullString `json:"library_id"`
	Title                string         `json:"title"`
	TitleZh              sql.NullString `json:"title_zh"`
	TitleEn              sql.NullString `json:"title_en"`
	Synopsis             sql.NullString `json:"synopsis"`
	CoverImageUrl        sql.NullString `json:"cover_image_url"`
	TotalEpisodes        sql.NullInt64  `json:"total_episodes"`
	Status               string         `json:"status"`
	AirDate              sql.NullString `json:"air_date"`
	Year                 sql.NullInt64  `json:"year"`
	Season               sql.NullString `json:"season"`
	Genres               string         `json:"genres"`
	IsCustom             int64          `json:"is_custom"`
	AnilistID            sql.NullInt64  `json:"anilist_id"`
	BangumiID            sql.NullInt64  `json:"bangumi_id"`
	DandanplayBangumiID  sql.NullInt64  `json:"dandanplay_bangumi_id"`
	MalID                sql.NullInt64  `json:"mal_id"`
	TmdbID               sql.NullInt64  `json:"tmdb_id"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	WatchStatus          string         `json:"watch_status"`
	WatchStatusUpdatedAt sql.NullString `json:"watch_status_updated_at"`
	UserScore            sql.NullInt64  `json:"user_score"`
	Score                float64        `json:"score"`
}

type Download struct {
	ID             string         `json:"id"`
	Gid            string         `json:"gid"`
	Url            string         `json:"url"`
	Name           string         `json:"name"`
	Status         string         `json:"status"`
	TotalBytes     int64          `json:"total_bytes"`
	CompletedBytes int64          `json:"completed_bytes"`
	SpeedBytes     int64          `json:"speed_bytes"`
	SaveDir        string         `json:"save_dir"`
	RuleID         sql.NullString `json:"rule_id"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
	BangumiID      sql.NullInt64  `json:"bangumi_id"`
	LibraryID      sql.NullString `json:"library_id"`
}

type DownloadRule struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Enabled          int64          `json:"enabled"`
	RssFeedID        string         `json:"rss_feed_id"`
	FilterRegex      string         `json:"filter_regex"`
	ExcludeRegex     string         `json:"exclude_regex"`
	SaveDir          string         `json:"save_dir"`
	EpisodeOffset    int64          `json:"episode_offset"`
	LastTriggeredAt  sql.NullString `json:"last_triggered_at"`
	CreatedAt        string         `json:"created_at"`
	ResolutionFilter string         `json:"resolution_filter"`
	SubgroupFilter   string         `json:"subgroup_filter"`
	MinSeeders       int64          `json:"min_seeders"`
	LibraryID        sql.NullString `json:"library_id"`
	BangumiID        sql.NullInt64  `json:"bangumi_id"`
}

type Episode struct {
	ID                  string         `json:"id"`
	AnimeID             string         `json:"anime_id"`
	EpisodeNumber       float64        `json:"episode_number"`
	Title               sql.NullString `json:"title"`
	TitleZh             sql.NullString `json:"title_zh"`
	AirDate             sql.NullString `json:"air_date"`
	Synopsis            sql.NullString `json:"synopsis"`
	ThumbnailUrl        sql.NullString `json:"thumbnail_url"`
	DandanplayEpisodeID sql.NullInt64  `json:"dandanplay_episode_id"`
	BangumiEpisodeID    sql.NullInt64  `json:"bangumi_episode_id"`
	MalEpisodeID        sql.NullInt64  `json:"mal_episode_id"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
	SynopsisZh          sql.NullString `json:"synopsis_zh"`
}

type HotTag struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Category  string `json:"category"`
	Count     int64  `json:"count"`
	CreatedAt string `json:"created_at"`
}

type Library struct {
	ID                    string         `json:"id"`
	Name                  string         `json:"name"`
	Path                  string         `json:"path"`
	Enabled               int64          `json:"enabled"`
	ScanIntervalMinutes   int64          `json:"scan_interval_minutes"`
	LastScannedAt         sql.NullString `json:"last_scanned_at"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
	SourceType            string         `json:"source_type"`
	SourceConfigEncrypted sql.NullString `json:"source_config_encrypted"`
}

type MediaFile struct {
	ID                  string         `json:"id"`
	EpisodeID           sql.NullString `json:"episode_id"`
	LibraryID           string         `json:"library_id"`
	Path                string         `json:"path"`
	Filename            string         `json:"filename"`
	SizeBytes           int64          `json:"size_bytes"`
	DurationSeconds     sql.NullInt64  `json:"duration_seconds"`
	ContainerFormat     sql.NullString `json:"container_format"`
	VideoCodec          sql.NullString `json:"video_codec"`
	AudioCodec          sql.NullString `json:"audio_codec"`
	Width               sql.NullInt64  `json:"width"`
	Height              sql.NullInt64  `json:"height"`
	FileHash            sql.NullString `json:"file_hash"`
	DandanplayEpisodeID sql.NullInt64  `json:"dandanplay_episode_id"`
	MatchStatus         string         `json:"match_status"`
	VideoTracks         string         `json:"video_tracks"`
	AudioTracks         string         `json:"audio_tracks"`
	SubtitleTracks      string         `json:"subtitle_tracks"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
	DandanplayAnimeID   sql.NullInt64  `json:"dandanplay_anime_id"`
	BangumiSubjectID    sql.NullInt64  `json:"bangumi_subject_id"`
	BangumiEpisodeID    sql.NullInt64  `json:"bangumi_episode_id"`
}

type Playlist struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type PlaylistEntry struct {
	ID         string `json:"id"`
	PlaylistID string `json:"playlist_id"`
	EpisodeID  string `json:"episode_id"`
	Position   int64  `json:"position"`
	AddedAt    string `json:"added_at"`
}

type RssFeed struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Url                  string         `json:"url"`
	Type                 string         `json:"type"`
	Enabled              int64          `json:"enabled"`
	FetchIntervalMinutes int64          `json:"fetch_interval_minutes"`
	LastFetchedAt        sql.NullString `json:"last_fetched_at"`
	CreatedAt            string         `json:"created_at"`
}

type ScanSummary struct {
	ID             string         `json:"id"`
	LibraryID      string         `json:"library_id"`
	StartedAt      string         `json:"started_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	FilesFound     int64          `json:"files_found"`
	FilesMatched   int64          `json:"files_matched"`
	FilesUnmatched int64          `json:"files_unmatched"`
	Errors         string         `json:"errors"`
}

type Setting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type SubtitleFile struct {
	ID          string `json:"id"`
	MediaFileID string `json:"media_file_id"`
	Path        string `json:"path"`
	Language    string `json:"language"`
	Format      string `json:"format"`
	Source      string `json:"source"`
	CreatedAt   string `json:"created_at"`
}

type TranscodeSession struct {
	ID           string         `json:"id"`
	MediaFileID  string         `json:"media_file_id"`
	SessionToken string         `json:"session_token"`
	Status       string         `json:"status"`
	OutputDir    string         `json:"output_dir"`
	Codec        sql.NullString `json:"codec"`
	Resolution   sql.NullString `json:"resolution"`
	Progress     int64          `json:"progress"`
	ExpiresAt    string         `json:"expires_at"`
	CreatedAt    string         `json:"created_at"`
}

type User struct {
	ID               string `json:"id"`
	Username         string `json:"username"`
	PasswordHash     string `json:"password_hash"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
	TotpSecret       string `json:"totp_secret"`
	TwoFactorEnabled int64  `json:"two_factor_enabled"`
}

type WatchProgress struct {
	ID              string         `json:"id"`
	UserID          string         `json:"user_id"`
	EpisodeID       string         `json:"episode_id"`
	MediaFileID     sql.NullString `json:"media_file_id"`
	PositionSeconds int64          `json:"position_seconds"`
	DurationSeconds sql.NullInt64  `json:"duration_seconds"`
	Completed       int64          `json:"completed"`
	LastWatchedAt   string         `json:"last_watched_at"`
	BangumiSyncedAt sql.NullString `json:"bangumi_synced_at"`
	MalSyncedAt     sql.NullString `json:"mal_synced_at"`
	AnilistSyncedAt sql.NullString `json:"anilist_synced_at"`
}
