// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Anime struct {
	ID                   string         `json:"id"`
	LibraryID            sql.NullString `json:"library_id"`
	Title                string         `json:"title"`
	TitleZh              sql.NullString `json:"title_zh"`
	TitleEn              sql.NullString `json:"title_en"`
	Synopsis             sql.NullString `json:"synopsis"`
	CoverImageUrl        sql.NullString `json:"cover_image_url"`
	TotalEpisodes        sql.NullInt64  `json:"total_episodes"`
	Status               string         `json:"status"`
	AirDate              sql.NullString `json:"air_date"`
	Year                 sql.NullInt64  `json:"year"`
	Season               sql.NullString `json:"season"`
	Genres               string         `json:"genres"`
	IsCustom             int64          `json:"is_custom"`
	AnilistID            sql.NullInt64  `json:"anilist_id"`
	BangumiID            sql.NullInt64  `json:"bangumi_id"`
	DandanplayBangumiID  sql.NullInt64  `json:"dandanplay_bangumi_id"`
	MalID                sql.NullInt64  `json:"mal_id"`
	TmdbID               sql.NullInt64  `json:"tmdb_id"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	WatchStatus          string         `json:"watch_status"`
	WatchStatusUpdatedAt sql.NullString `json:"watch_status_updated_at"`
	UserScore            sql.NullInt64  `json:"user_score"`
	Score                float64        `json:"score"`
	AnidbID              sql.NullInt64  `json:"anidb_id"`
	SyncDisabled         int64          `json:"sync_disabled"`
	WatchStatusOverride  string         `json:"watch_status_override"`
	TraktShowID          sql.NullInt64  `json:"trakt_show_id"`
}

type ApiToken struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	TokenHash     string         `json:"token_hash"`
	TokenPrefix   string         `json:"token_prefix"`
	UserID        string         `json:"user_id"`
	LastUsedAt    sql.NullString `json:"last_used_at"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
	LastIp        string         `json:"last_ip"`
	LastUserAgent string         `json:"last_user_agent"`
}

type AuditLog struct {
	ID         string          `json:"id"`
	UserID     string          `json:"user_id"`
	TokenID    sql.NullString  `json:"token_id"`
	AgentLabel sql.NullString  `json:"agent_label"`
	ActionType string          `json:"action_type"`
	TargetType sql.NullString  `json:"target_type"`
	TargetID   sql.NullString  `json:"target_id"`
	BeforeJson sql.NullString  `json:"before_json"`
	AfterJson  sql.NullString  `json:"after_json"`
	Confidence sql.NullFloat64 `json:"confidence"`
	ParentID   sql.NullString  `json:"parent_id"`
	DryRun     int64           `json:"dry_run"`
	UndoneAt   sql.NullString  `json:"undone_at"`
	UndoneBy   sql.NullString  `json:"undone_by"`
	CreatedAt  string          `json:"created_at"`
}

type BackupConfig struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	Type       string         `json:"type"`
	Config     string         `json:"config"`
	Enabled    int64          `json:"enabled"`
	LastSyncAt sql.NullString `json:"last_sync_at"`
}

type Download struct {
	ID             string         `json:"id"`
	Gid            string         `json:"gid"`
	Url            string         `json:"url"`
	Name           string         `json:"name"`
	Status         string         `json:"status"`
	TotalBytes     int64          `json:"total_bytes"`
	CompletedBytes int64          `json:"completed_bytes"`
	SpeedBytes     int64          `json:"speed_bytes"`
	SaveDir        string         `json:"save_dir"`
	RuleID         sql.NullString `json:"rule_id"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
	BangumiID      sql.NullInt64  `json:"bangumi_id"`
	LibraryID      sql.NullString `json:"library_id"`
}

type DownloadRule struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Enabled          int64          `json:"enabled"`
	RssFeedID        string         `json:"rss_feed_id"`
	FilterRegex      string         `json:"filter_regex"`
	ExcludeRegex     string         `json:"exclude_regex"`
	SaveDir          string         `json:"save_dir"`
	EpisodeOffset    int64          `json:"episode_offset"`
	LastTriggeredAt  sql.NullString `json:"last_triggered_at"`
	CreatedAt        string         `json:"created_at"`
	ResolutionFilter string         `json:"resolution_filter"`
	SubgroupFilter   string         `json:"subgroup_filter"`
	MinSeeders       int64          `json:"min_seeders"`
	LibraryID        sql.NullString `json:"library_id"`
	BangumiID        sql.NullInt64  `json:"bangumi_id"`
	MatchMode        string         `json:"match_mode"`
	EpisodeFilter    string         `json:"episode_filter"`
	EpisodeRange     string         `json:"episode_range"`
}

type Episode struct {
	ID                   string         `json:"id"`
	AnimeID              string         `json:"anime_id"`
	EpisodeNumber        float64        `json:"episode_number"`
	Title                sql.NullString `json:"title"`
	TitleZh              sql.NullString `json:"title_zh"`
	AirDate              sql.NullString `json:"air_date"`
	Synopsis             sql.NullString `json:"synopsis"`
	ThumbnailUrl         sql.NullString `json:"thumbnail_url"`
	DandanplayEpisodeID  sql.NullInt64  `json:"dandanplay_episode_id"`
	BangumiEpisodeID     sql.NullInt64  `json:"bangumi_episode_id"`
	MalEpisodeID         sql.NullInt64  `json:"mal_episode_id"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
	SynopsisZh           sql.NullString `json:"synopsis_zh"`
	PreferredMediaFileID sql.NullString `json:"preferred_media_file_id"`
	PreferredManuallySet int64          `json:"preferred_manually_set"`
}

type ExternalDanmaku struct {
	ID           int64  `json:"id"`
	MediaFileID  string `json:"media_file_id"`
	Source       string `json:"source"`
	VideoID      string `json:"video_id"`
	PartIndex    int64  `json:"part_index"`
	CommentsJson string `json:"comments_json"`
	CommentCount int64  `json:"comment_count"`
	CreatedAt    string `json:"created_at"`
}

type HotTag struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Category  string `json:"category"`
	Count     int64  `json:"count"`
	CreatedAt string `json:"created_at"`
}

type Library struct {
	ID                    string         `json:"id"`
	Name                  string         `json:"name"`
	Path                  string         `json:"path"`
	Enabled               int64          `json:"enabled"`
	ScanIntervalMinutes   int64          `json:"scan_interval_minutes"`
	LastScannedAt         sql.NullString `json:"last_scanned_at"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
	SourceType            string         `json:"source_type"`
	SourceConfigEncrypted sql.NullString `json:"source_config_encrypted"`
	RenameTemplate        string         `json:"rename_template"`
	RenameAuto            int64          `json:"rename_auto"`
}

type MediaFile struct {
	ID                  string         `json:"id"`
	EpisodeID           sql.NullString `json:"episode_id"`
	LibraryID           string         `json:"library_id"`
	Path                string         `json:"path"`
	Filename            string         `json:"filename"`
	SizeBytes           int64          `json:"size_bytes"`
	DurationSeconds     sql.NullInt64  `json:"duration_seconds"`
	ContainerFormat     sql.NullString `json:"container_format"`
	VideoCodec          sql.NullString `json:"video_codec"`
	AudioCodec          sql.NullString `json:"audio_codec"`
	Width               sql.NullInt64  `json:"width"`
	Height              sql.NullInt64  `json:"height"`
	FileHash            sql.NullString `json:"file_hash"`
	DandanplayEpisodeID sql.NullInt64  `json:"dandanplay_episode_id"`
	MatchStatus         string         `json:"match_status"`
	VideoTracks         string         `json:"video_tracks"`
	AudioTracks         string         `json:"audio_tracks"`
	SubtitleTracks      string         `json:"subtitle_tracks"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
	DandanplayAnimeID   sql.NullInt64  `json:"dandanplay_anime_id"`
	BangumiSubjectID    sql.NullInt64  `json:"bangumi_subject_id"`
	BangumiEpisodeID    sql.NullInt64  `json:"bangumi_episode_id"`
}

type Notification struct {
	ID        string         `json:"id"`
	Type      string         `json:"type"`
	Title     string         `json:"title"`
	Message   string         `json:"message"`
	Severity  string         `json:"severity"`
	Read      int64          `json:"read"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt string         `json:"created_at"`
}

type NotificationDelivery struct {
	ID             string         `json:"id"`
	NotificationID string         `json:"notification_id"`
	Provider       string         `json:"provider"`
	Status         string         `json:"status"`
	Attempts       int64          `json:"attempts"`
	LastError      sql.NullString `json:"last_error"`
	NextRetryAt    sql.NullString `json:"next_retry_at"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type Playlist struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type PlaylistEntry struct {
	ID         string `json:"id"`
	PlaylistID string `json:"playlist_id"`
	EpisodeID  string `json:"episode_id"`
	Position   int64  `json:"position"`
	AddedAt    string `json:"added_at"`
}

type RenameHistory struct {
	ID          string         `json:"id"`
	BatchID     string         `json:"batch_id"`
	LibraryID   string         `json:"library_id"`
	MediaFileID sql.NullString `json:"media_file_id"`
	OldPath     string         `json:"old_path"`
	NewPath     string         `json:"new_path"`
	AppliedAt   string         `json:"applied_at"`
	RevertedAt  sql.NullString `json:"reverted_at"`
}

type RssFeed struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Url                  string         `json:"url"`
	Type                 string         `json:"type"`
	Enabled              int64          `json:"enabled"`
	FetchIntervalMinutes int64          `json:"fetch_interval_minutes"`
	LastFetchedAt        sql.NullString `json:"last_fetched_at"`
	CreatedAt            string         `json:"created_at"`
}

type ScanSummary struct {
	ID             string         `json:"id"`
	LibraryID      string         `json:"library_id"`
	StartedAt      string         `json:"started_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	FilesFound     int64          `json:"files_found"`
	FilesMatched   int64          `json:"files_matched"`
	FilesUnmatched int64          `json:"files_unmatched"`
	Errors         string         `json:"errors"`
}

type SegmentMark struct {
	ID          string  `json:"id"`
	MediaFileID string  `json:"media_file_id"`
	Type        string  `json:"type"`
	StartTime   float64 `json:"start_time"`
	EndTime     float64 `json:"end_time"`
	Source      string  `json:"source"`
	CreatedAt   string  `json:"created_at"`
}

type Setting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type SubtitleFile struct {
	ID          string `json:"id"`
	MediaFileID string `json:"media_file_id"`
	Path        string `json:"path"`
	Language    string `json:"language"`
	Format      string `json:"format"`
	Source      string `json:"source"`
	CreatedAt   string `json:"created_at"`
}

type SyncOutbox struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	Provider      string         `json:"provider"`
	AnimeID       string         `json:"anime_id"`
	Kind          string         `json:"kind"`
	Payload       string         `json:"payload"`
	Attempts      int64          `json:"attempts"`
	NextAttemptAt string         `json:"next_attempt_at"`
	LastError     sql.NullString `json:"last_error"`
	CreatedAt     string         `json:"created_at"`
	CompletedAt   sql.NullString `json:"completed_at"`
}

type SyncProviderState struct {
	UserID       string         `json:"user_id"`
	Provider     string         `json:"provider"`
	PullEnabled  int64          `json:"pull_enabled"`
	LastPulledAt sql.NullString `json:"last_pulled_at"`
}

type TranscodeSession struct {
	ID           string         `json:"id"`
	MediaFileID  string         `json:"media_file_id"`
	SessionToken string         `json:"session_token"`
	Status       string         `json:"status"`
	OutputDir    string         `json:"output_dir"`
	Codec        sql.NullString `json:"codec"`
	Resolution   sql.NullString `json:"resolution"`
	Progress     int64          `json:"progress"`
	ExpiresAt    string         `json:"expires_at"`
	CreatedAt    string         `json:"created_at"`
}

type User struct {
	ID               string `json:"id"`
	Username         string `json:"username"`
	PasswordHash     string `json:"password_hash"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
	TotpSecret       string `json:"totp_secret"`
	TwoFactorEnabled int64  `json:"two_factor_enabled"`
}

type UserPreference struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Scope     string `json:"scope"`
	ScopeID   string `json:"scope_id"`
	Data      string `json:"data"`
	UpdatedAt string `json:"updated_at"`
}

type WatchProgress struct {
	ID              string         `json:"id"`
	UserID          string         `json:"user_id"`
	EpisodeID       string         `json:"episode_id"`
	MediaFileID     sql.NullString `json:"media_file_id"`
	PositionSeconds int64          `json:"position_seconds"`
	DurationSeconds sql.NullInt64  `json:"duration_seconds"`
	Completed       int64          `json:"completed"`
	LastWatchedAt   string         `json:"last_watched_at"`
	BangumiSyncedAt sql.NullString `json:"bangumi_synced_at"`
	MalSyncedAt     sql.NullString `json:"mal_synced_at"`
	AnilistSyncedAt sql.NullString `json:"anilist_synced_at"`
}
