// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_deliveries.sql

package store

import (
	"context"
	"database/sql"
)

const createNotificationDelivery = `-- name: CreateNotificationDelivery :one
INSERT INTO notification_deliveries (id, notification_id, provider, status, attempts, last_error, next_retry_at, created_at, updated_at)
VALUES (?, ?, ?, 'pending', 0, NULL, NULL, strftime('%Y-%m-%dT%H:%M:%SZ','now'), strftime('%Y-%m-%dT%H:%M:%SZ','now'))
RETURNING id, notification_id, provider, status, attempts, last_error, next_retry_at, created_at, updated_at
`

type CreateNotificationDeliveryParams struct {
	ID             string `json:"id"`
	NotificationID string `json:"notification_id"`
	Provider       string `json:"provider"`
}

func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRowContext(ctx, createNotificationDelivery, arg.ID, arg.NotificationID, arg.Provider)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Provider,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldDeliveries = `-- name: DeleteOldDeliveries :exec
DELETE FROM notification_deliveries WHERE created_at < ?
`

func (q *Queries) DeleteOldDeliveries(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, deleteOldDeliveries, createdAt)
	return err
}

const getLastDeliveryByProvider = `-- name: GetLastDeliveryByProvider :one
SELECT id, notification_id, provider, status, attempts, last_error, next_retry_at, created_at, updated_at FROM notification_deliveries
WHERE provider = ? AND status IN ('sent', 'failed')
ORDER BY updated_at DESC LIMIT 1
`

func (q *Queries) GetLastDeliveryByProvider(ctx context.Context, provider string) (NotificationDelivery, error) {
	row := q.db.QueryRowContext(ctx, getLastDeliveryByProvider, provider)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Provider,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingDeliveries = `-- name: ListPendingDeliveries :many
SELECT id, notification_id, provider, status, attempts, last_error, next_retry_at, created_at, updated_at FROM notification_deliveries
WHERE status = 'pending' AND (next_retry_at IS NULL OR next_retry_at <= ?) AND attempts < 3
ORDER BY created_at ASC
LIMIT 50
`

func (q *Queries) ListPendingDeliveries(ctx context.Context, nextRetryAt sql.NullString) ([]NotificationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDeliveries, nextRetryAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Provider,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryFailure = `-- name: UpdateDeliveryFailure :exec
UPDATE notification_deliveries
SET attempts = attempts + 1,
    last_error = ?,
    next_retry_at = ?,
    status = CASE WHEN attempts + 1 >= 3 THEN 'failed' ELSE 'pending' END,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
`

type UpdateDeliveryFailureParams struct {
	LastError   sql.NullString `json:"last_error"`
	NextRetryAt sql.NullString `json:"next_retry_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateDeliveryFailure(ctx context.Context, arg UpdateDeliveryFailureParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryFailure, arg.LastError, arg.NextRetryAt, arg.ID)
	return err
}

const updateDeliverySuccess = `-- name: UpdateDeliverySuccess :exec
UPDATE notification_deliveries
SET status = 'sent', updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
`

func (q *Queries) UpdateDeliverySuccess(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateDeliverySuccess, id)
	return err
}
