// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package store

import (
	"context"
	"database/sql"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE read = 0
`

func (q *Queries) CountUnreadNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, type, title, message, severity, read, metadata, created_at)
VALUES (?, ?, ?, ?, ?, 0, ?, strftime('%Y-%m-%dT%H:%M:%SZ','now'))
RETURNING id, type, title, message, severity, read, metadata, created_at
`

type CreateNotificationParams struct {
	ID       string         `json:"id"`
	Type     string         `json:"type"`
	Title    string         `json:"title"`
	Message  string         `json:"message"`
	Severity string         `json:"severity"`
	Metadata sql.NullString `json:"metadata"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.Severity,
		arg.Metadata,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Severity,
		&i.Read,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllNotifications = `-- name: DeleteAllNotifications :exec
DELETE FROM notifications
`

func (q *Queries) DeleteAllNotifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllNotifications)
	return err
}

const deleteOldReadNotifications = `-- name: DeleteOldReadNotifications :exec
DELETE FROM notifications WHERE read = 1 AND created_at < ?
`

func (q *Queries) DeleteOldReadNotifications(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, deleteOldReadNotifications, createdAt)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, type, title, message, severity, read, metadata, created_at FROM notifications ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListNotificationsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Severity,
			&i.Read,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByType = `-- name: ListNotificationsByType :many
SELECT id, type, title, message, severity, read, metadata, created_at FROM notifications WHERE type LIKE ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListNotificationsByTypeParams struct {
	Type   string `json:"type"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListNotificationsByType(ctx context.Context, arg ListNotificationsByTypeParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Severity,
			&i.Read,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read = 1 WHERE read = 0
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read = 1 WHERE id = ?
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, id)
	return err
}
