// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playable_episodes.sql

package store

import (
	"context"
	"database/sql"
)

const listPlayableEpisodes = `-- name: ListPlayableEpisodes :many
SELECT
  e.id AS episode_id,
  e.episode_number AS sort,
  e.title AS episode_title,
  e.title_zh AS episode_title_zh,
  e.air_date,
  e.synopsis,
  e.synopsis_zh,
  e.thumbnail_url AS image,
  mf.id AS media_file_id,
  mf.filename AS media_filename,
  mf.size_bytes AS media_size_bytes,
  mf.width AS media_width,
  mf.height AS media_height,
  mf.video_codec AS media_video_codec,
  mf.audio_codec AS media_audio_codec,
  wp.position_seconds,
  wp.duration_seconds AS progress_duration,
  wp.completed
FROM episodes e
LEFT JOIN media_files mf ON mf.episode_id = e.id
LEFT JOIN watch_progress wp ON wp.episode_id = e.id
WHERE e.anime_id = ?1
ORDER BY e.episode_number ASC
`

type ListPlayableEpisodesRow struct {
	EpisodeID        string         `json:"episode_id"`
	Sort             float64        `json:"sort"`
	EpisodeTitle     sql.NullString `json:"episode_title"`
	EpisodeTitleZh   sql.NullString `json:"episode_title_zh"`
	AirDate          sql.NullString `json:"air_date"`
	Synopsis         sql.NullString `json:"synopsis"`
	SynopsisZh       sql.NullString `json:"synopsis_zh"`
	Image            sql.NullString `json:"image"`
	MediaFileID      sql.NullString `json:"media_file_id"`
	MediaFilename    sql.NullString `json:"media_filename"`
	MediaSizeBytes   sql.NullInt64  `json:"media_size_bytes"`
	MediaWidth       sql.NullInt64  `json:"media_width"`
	MediaHeight      sql.NullInt64  `json:"media_height"`
	MediaVideoCodec  sql.NullString `json:"media_video_codec"`
	MediaAudioCodec  sql.NullString `json:"media_audio_codec"`
	PositionSeconds  sql.NullInt64  `json:"position_seconds"`
	ProgressDuration sql.NullInt64  `json:"progress_duration"`
	Completed        sql.NullInt64  `json:"completed"`
}

func (q *Queries) ListPlayableEpisodes(ctx context.Context, animeID string) ([]ListPlayableEpisodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayableEpisodes, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayableEpisodesRow{}
	for rows.Next() {
		var i ListPlayableEpisodesRow
		if err := rows.Scan(
			&i.EpisodeID,
			&i.Sort,
			&i.EpisodeTitle,
			&i.EpisodeTitleZh,
			&i.AirDate,
			&i.Synopsis,
			&i.SynopsisZh,
			&i.Image,
			&i.MediaFileID,
			&i.MediaFilename,
			&i.MediaSizeBytes,
			&i.MediaWidth,
			&i.MediaHeight,
			&i.MediaVideoCodec,
			&i.MediaAudioCodec,
			&i.PositionSeconds,
			&i.ProgressDuration,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
