// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package store

import (
	"context"
)

const createSegmentMark = `-- name: CreateSegmentMark :one
INSERT INTO segment_marks (id, media_file_id, type, start_time, end_time, source, created_at)
VALUES (?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
ON CONFLICT(media_file_id, type, source) DO UPDATE SET
    start_time = excluded.start_time,
    end_time = excluded.end_time
RETURNING id, media_file_id, type, start_time, end_time, source, created_at
`

type CreateSegmentMarkParams struct {
	ID          string  `json:"id"`
	MediaFileID string  `json:"media_file_id"`
	Type        string  `json:"type"`
	StartTime   float64 `json:"start_time"`
	EndTime     float64 `json:"end_time"`
	Source      string  `json:"source"`
}

func (q *Queries) CreateSegmentMark(ctx context.Context, arg CreateSegmentMarkParams) (SegmentMark, error) {
	row := q.db.QueryRowContext(ctx, createSegmentMark,
		arg.ID,
		arg.MediaFileID,
		arg.Type,
		arg.StartTime,
		arg.EndTime,
		arg.Source,
	)
	var i SegmentMark
	err := row.Scan(
		&i.ID,
		&i.MediaFileID,
		&i.Type,
		&i.StartTime,
		&i.EndTime,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBackupConfig = `-- name: DeleteBackupConfig :exec
DELETE FROM backup_configs
WHERE user_id = ? AND type = ?
`

type DeleteBackupConfigParams struct {
	UserID string `json:"user_id"`
	Type   string `json:"type"`
}

func (q *Queries) DeleteBackupConfig(ctx context.Context, arg DeleteBackupConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteBackupConfig, arg.UserID, arg.Type)
	return err
}

const deleteSegmentMark = `-- name: DeleteSegmentMark :exec
DELETE FROM segment_marks WHERE id = ?
`

func (q *Queries) DeleteSegmentMark(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSegmentMark, id)
	return err
}

const deleteUserPreference = `-- name: DeleteUserPreference :exec
DELETE FROM user_preferences
WHERE user_id = ? AND scope = ? AND scope_id = ?
`

type DeleteUserPreferenceParams struct {
	UserID  string `json:"user_id"`
	Scope   string `json:"scope"`
	ScopeID string `json:"scope_id"`
}

func (q *Queries) DeleteUserPreference(ctx context.Context, arg DeleteUserPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserPreference, arg.UserID, arg.Scope, arg.ScopeID)
	return err
}

const getAllUserPreferences = `-- name: GetAllUserPreferences :many
SELECT id, user_id, scope, scope_id, data, updated_at FROM user_preferences
WHERE user_id = ?
ORDER BY scope, scope_id
`

func (q *Queries) GetAllUserPreferences(ctx context.Context, userID string) ([]UserPreference, error) {
	rows, err := q.db.QueryContext(ctx, getAllUserPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPreference{}
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Scope,
			&i.ScopeID,
			&i.Data,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBackupConfig = `-- name: GetBackupConfig :one
SELECT id, user_id, type, config, enabled, last_sync_at FROM backup_configs
WHERE user_id = ? AND type = ?
LIMIT 1
`

type GetBackupConfigParams struct {
	UserID string `json:"user_id"`
	Type   string `json:"type"`
}

func (q *Queries) GetBackupConfig(ctx context.Context, arg GetBackupConfigParams) (BackupConfig, error) {
	row := q.db.QueryRowContext(ctx, getBackupConfig, arg.UserID, arg.Type)
	var i BackupConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.LastSyncAt,
	)
	return i, err
}

const getUserPreference = `-- name: GetUserPreference :one
SELECT id, user_id, scope, scope_id, data, updated_at FROM user_preferences
WHERE user_id = ? AND scope = ? AND scope_id = ?
LIMIT 1
`

type GetUserPreferenceParams struct {
	UserID  string `json:"user_id"`
	Scope   string `json:"scope"`
	ScopeID string `json:"scope_id"`
}

func (q *Queries) GetUserPreference(ctx context.Context, arg GetUserPreferenceParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserPreference, arg.UserID, arg.Scope, arg.ScopeID)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Scope,
		&i.ScopeID,
		&i.Data,
		&i.UpdatedAt,
	)
	return i, err
}

const listBackupConfigs = `-- name: ListBackupConfigs :many
SELECT id, user_id, type, config, enabled, last_sync_at FROM backup_configs
WHERE user_id = ?
`

func (q *Queries) ListBackupConfigs(ctx context.Context, userID string) ([]BackupConfig, error) {
	rows, err := q.db.QueryContext(ctx, listBackupConfigs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupConfig{}
	for rows.Next() {
		var i BackupConfig
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.LastSyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegmentMarks = `-- name: ListSegmentMarks :many
SELECT id, media_file_id, type, start_time, end_time, source, created_at FROM segment_marks
WHERE media_file_id = ?
ORDER BY start_time ASC
`

func (q *Queries) ListSegmentMarks(ctx context.Context, mediaFileID string) ([]SegmentMark, error) {
	rows, err := q.db.QueryContext(ctx, listSegmentMarks, mediaFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SegmentMark{}
	for rows.Next() {
		var i SegmentMark
		if err := rows.Scan(
			&i.ID,
			&i.MediaFileID,
			&i.Type,
			&i.StartTime,
			&i.EndTime,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPreferences = `-- name: ListUserPreferences :many
SELECT id, user_id, scope, scope_id, data, updated_at FROM user_preferences
WHERE user_id = ? AND scope = ?
ORDER BY updated_at DESC
`

type ListUserPreferencesParams struct {
	UserID string `json:"user_id"`
	Scope  string `json:"scope"`
}

func (q *Queries) ListUserPreferences(ctx context.Context, arg ListUserPreferencesParams) ([]UserPreference, error) {
	rows, err := q.db.QueryContext(ctx, listUserPreferences, arg.UserID, arg.Scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPreference{}
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Scope,
			&i.ScopeID,
			&i.Data,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBackupSyncTime = `-- name: UpdateBackupSyncTime :exec
UPDATE backup_configs
SET last_sync_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE user_id = ? AND type = ?
`

type UpdateBackupSyncTimeParams struct {
	UserID string `json:"user_id"`
	Type   string `json:"type"`
}

func (q *Queries) UpdateBackupSyncTime(ctx context.Context, arg UpdateBackupSyncTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateBackupSyncTime, arg.UserID, arg.Type)
	return err
}

const upsertBackupConfig = `-- name: UpsertBackupConfig :one
INSERT INTO backup_configs (id, user_id, type, config, enabled)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(user_id, type) DO UPDATE SET
    config = excluded.config,
    enabled = excluded.enabled
RETURNING id, user_id, type, config, enabled, last_sync_at
`

type UpsertBackupConfigParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	Type    string `json:"type"`
	Config  string `json:"config"`
	Enabled int64  `json:"enabled"`
}

func (q *Queries) UpsertBackupConfig(ctx context.Context, arg UpsertBackupConfigParams) (BackupConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertBackupConfig,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Config,
		arg.Enabled,
	)
	var i BackupConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.LastSyncAt,
	)
	return i, err
}

const upsertUserPreference = `-- name: UpsertUserPreference :one
INSERT INTO user_preferences (id, user_id, scope, scope_id, data, updated_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
ON CONFLICT(user_id, scope, scope_id) DO UPDATE SET
    data = excluded.data,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, user_id, scope, scope_id, data, updated_at
`

type UpsertUserPreferenceParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	Scope   string `json:"scope"`
	ScopeID string `json:"scope_id"`
	Data    string `json:"data"`
}

func (q *Queries) UpsertUserPreference(ctx context.Context, arg UpsertUserPreferenceParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, upsertUserPreference,
		arg.ID,
		arg.UserID,
		arg.Scope,
		arg.ScopeID,
		arg.Data,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Scope,
		&i.ScopeID,
		&i.Data,
		&i.UpdatedAt,
	)
	return i, err
}
