// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CompleteScanSummary(ctx context.Context, arg CompleteScanSummaryParams) error
	CountMediaFilesByLibrary(ctx context.Context, libraryID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error)
	CreateScanSummary(ctx context.Context, arg CreateScanSummaryParams) (ScanSummary, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteLibrary(ctx context.Context, id string) error
	DeleteMediaFile(ctx context.Context, path string) error
	GetLibrary(ctx context.Context, id string) (Library, error)
	GetMediaFileByID(ctx context.Context, id string) (MediaFile, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListLibraries(ctx context.Context) ([]Library, error)
	ListMediaFilePathsByLibrary(ctx context.Context, libraryID string) ([]string, error)
	ListScanSummaries(ctx context.Context, libraryID string) ([]ScanSummary, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListUnmatchedMediaFilesByLibrary(ctx context.Context, libraryID string) ([]MediaFile, error)
	UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error)
	UpdateLibraryLastScanned(ctx context.Context, id string) error
	UpdateMediaFileDandanplayID(ctx context.Context, arg UpdateMediaFileDandanplayIDParams) error
	UpdateMediaFileHash(ctx context.Context, arg UpdateMediaFileHashParams) error
	UpsertMediaFile(ctx context.Context, arg UpsertMediaFileParams) (MediaFile, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
}

var _ Querier = (*Queries)(nil)
