// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	CompleteScanSummary(ctx context.Context, arg CompleteScanSummaryParams) error
	CountMediaFilesByLibrary(ctx context.Context, libraryID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAnime(ctx context.Context, arg CreateAnimeParams) (Anime, error)
	CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error)
	CreateDownloadRule(ctx context.Context, arg CreateDownloadRuleParams) (DownloadRule, error)
	CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error)
	CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error)
	CreateRSSFeed(ctx context.Context, arg CreateRSSFeedParams) (RssFeed, error)
	CreateScanSummary(ctx context.Context, arg CreateScanSummaryParams) (ScanSummary, error)
	CreateSubtitleFile(ctx context.Context, arg CreateSubtitleFileParams) (SubtitleFile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDownload(ctx context.Context, gid string) error
	DeleteDownloadRule(ctx context.Context, id string) error
	DeleteLibrary(ctx context.Context, id string) error
	DeleteMediaFile(ctx context.Context, path string) error
	DeleteRSSFeed(ctx context.Context, id string) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteSubtitleFile(ctx context.Context, id string) error
	GetAnime(ctx context.Context, id string) (Anime, error)
	GetAnimeByBangumiID(ctx context.Context, bangumiID sql.NullInt64) (Anime, error)
	GetDownloadByGID(ctx context.Context, gid string) (Download, error)
	GetDownloadByURL(ctx context.Context, url string) (Download, error)
	GetEpisode(ctx context.Context, id string) (Episode, error)
	GetEpisodeByDandanplayID(ctx context.Context, dandanplayEpisodeID sql.NullInt64) (Episode, error)
	GetLibrary(ctx context.Context, id string) (Library, error)
	GetMediaFileByID(ctx context.Context, id string) (MediaFile, error)
	GetRSSFeed(ctx context.Context, id string) (RssFeed, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetSubtitleFile(ctx context.Context, id string) (SubtitleFile, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWatchProgress(ctx context.Context, arg GetWatchProgressParams) (WatchProgress, error)
	GetWatchProgressByMediaFile(ctx context.Context, arg GetWatchProgressByMediaFileParams) (WatchProgress, error)
	ListAnimeByLibraryID(ctx context.Context, libraryID sql.NullString) ([]Anime, error)
	ListCompletedWatchProgress(ctx context.Context, userID string) ([]WatchProgress, error)
	ListDownloadRules(ctx context.Context) ([]DownloadRule, error)
	ListDownloadRulesByFeedID(ctx context.Context, rssFeedID string) ([]DownloadRule, error)
	ListDownloads(ctx context.Context) ([]Download, error)
	ListEpisodesByAnimeID(ctx context.Context, animeID string) ([]Episode, error)
	ListLibraries(ctx context.Context) ([]Library, error)
	ListMatchedUnlinkedMediaFiles(ctx context.Context, libraryID string) ([]MediaFile, error)
	ListMediaFilePathsByLibrary(ctx context.Context, libraryID string) ([]string, error)
	ListRSSFeeds(ctx context.Context) ([]RssFeed, error)
	ListScanSummaries(ctx context.Context, libraryID string) ([]ScanSummary, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListSubtitlePathsByMediaFile(ctx context.Context, mediaFileID string) ([]string, error)
	ListSubtitlesByMediaFile(ctx context.Context, mediaFileID string) ([]SubtitleFile, error)
	ListUnmatchedMediaFilesByLibrary(ctx context.Context, libraryID string) ([]MediaFile, error)
	ListWatchProgressByUser(ctx context.Context, userID string) ([]WatchProgress, error)
	UpdateDownloadRule(ctx context.Context, arg UpdateDownloadRuleParams) error
	UpdateDownloadRuleTriggered(ctx context.Context, id string) error
	UpdateDownloadStatus(ctx context.Context, arg UpdateDownloadStatusParams) error
	UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error)
	UpdateLibraryLastScanned(ctx context.Context, id string) error
	UpdateMediaFileDandanplayID(ctx context.Context, arg UpdateMediaFileDandanplayIDParams) error
	UpdateMediaFileDandanplayIDs(ctx context.Context, arg UpdateMediaFileDandanplayIDsParams) error
	UpdateMediaFileEpisodeID(ctx context.Context, arg UpdateMediaFileEpisodeIDParams) error
	UpdateMediaFileHash(ctx context.Context, arg UpdateMediaFileHashParams) error
	UpdateRSSFeed(ctx context.Context, arg UpdateRSSFeedParams) error
	UpdateRSSFeedLastFetched(ctx context.Context, id string) error
	UpsertMediaFile(ctx context.Context, arg UpsertMediaFileParams) (MediaFile, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
	UpsertWatchProgress(ctx context.Context, arg UpsertWatchProgressParams) (WatchProgress, error)
}

var _ Querier = (*Queries)(nil)
