// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rename_history.sql

package store

import (
	"context"
	"database/sql"
)

const insertRenameHistory = `-- name: InsertRenameHistory :exec
INSERT INTO rename_history (id, batch_id, library_id, media_file_id, old_path, new_path)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertRenameHistoryParams struct {
	ID          string         `json:"id"`
	BatchID     string         `json:"batch_id"`
	LibraryID   string         `json:"library_id"`
	MediaFileID sql.NullString `json:"media_file_id"`
	OldPath     string         `json:"old_path"`
	NewPath     string         `json:"new_path"`
}

func (q *Queries) InsertRenameHistory(ctx context.Context, arg InsertRenameHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertRenameHistory,
		arg.ID,
		arg.BatchID,
		arg.LibraryID,
		arg.MediaFileID,
		arg.OldPath,
		arg.NewPath,
	)
	return err
}

const listRenameHistoryBatches = `-- name: ListRenameHistoryBatches :many
SELECT batch_id, MIN(applied_at) AS applied_at,
       COUNT(*) AS row_count,
       SUM(CASE WHEN reverted_at IS NULL THEN 0 ELSE 1 END) AS reverted_count
FROM rename_history
WHERE library_id = ?
GROUP BY batch_id
ORDER BY applied_at DESC
LIMIT ?
`

type ListRenameHistoryBatchesParams struct {
	LibraryID string `json:"library_id"`
	Limit     int64  `json:"limit"`
}

type ListRenameHistoryBatchesRow struct {
	BatchID       string          `json:"batch_id"`
	AppliedAt     interface{}     `json:"applied_at"`
	RowCount      int64           `json:"row_count"`
	RevertedCount sql.NullFloat64 `json:"reverted_count"`
}

func (q *Queries) ListRenameHistoryBatches(ctx context.Context, arg ListRenameHistoryBatchesParams) ([]ListRenameHistoryBatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRenameHistoryBatches, arg.LibraryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRenameHistoryBatchesRow{}
	for rows.Next() {
		var i ListRenameHistoryBatchesRow
		if err := rows.Scan(
			&i.BatchID,
			&i.AppliedAt,
			&i.RowCount,
			&i.RevertedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenameHistoryByBatch = `-- name: ListRenameHistoryByBatch :many
SELECT id, batch_id, library_id, media_file_id, old_path, new_path, applied_at, reverted_at FROM rename_history WHERE batch_id = ? ORDER BY applied_at DESC
`

func (q *Queries) ListRenameHistoryByBatch(ctx context.Context, batchID string) ([]RenameHistory, error) {
	rows, err := q.db.QueryContext(ctx, listRenameHistoryByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RenameHistory{}
	for rows.Next() {
		var i RenameHistory
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.LibraryID,
			&i.MediaFileID,
			&i.OldPath,
			&i.NewPath,
			&i.AppliedAt,
			&i.RevertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRenameHistoryReverted = `-- name: MarkRenameHistoryReverted :exec
UPDATE rename_history SET reverted_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
`

func (q *Queries) MarkRenameHistoryReverted(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markRenameHistoryReverted, id)
	return err
}
