// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rss_feeds.sql

package store

import (
	"context"
)

const createRSSFeed = `-- name: CreateRSSFeed :one
INSERT INTO rss_feeds (id, name, url, type, enabled, fetch_interval_minutes, created_at)
VALUES (?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ','now'))
RETURNING id, name, url, type, enabled, fetch_interval_minutes, last_fetched_at, created_at
`

type CreateRSSFeedParams struct {
	ID                   string `json:"id"`
	Name                 string `json:"name"`
	Url                  string `json:"url"`
	Type                 string `json:"type"`
	Enabled              int64  `json:"enabled"`
	FetchIntervalMinutes int64  `json:"fetch_interval_minutes"`
}

func (q *Queries) CreateRSSFeed(ctx context.Context, arg CreateRSSFeedParams) (RssFeed, error) {
	row := q.db.QueryRowContext(ctx, createRSSFeed,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Type,
		arg.Enabled,
		arg.FetchIntervalMinutes,
	)
	var i RssFeed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Type,
		&i.Enabled,
		&i.FetchIntervalMinutes,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRSSFeed = `-- name: DeleteRSSFeed :exec
DELETE FROM rss_feeds WHERE id = ?
`

func (q *Queries) DeleteRSSFeed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRSSFeed, id)
	return err
}

const getRSSFeed = `-- name: GetRSSFeed :one
SELECT id, name, url, type, enabled, fetch_interval_minutes, last_fetched_at, created_at FROM rss_feeds WHERE id = ? LIMIT 1
`

func (q *Queries) GetRSSFeed(ctx context.Context, id string) (RssFeed, error) {
	row := q.db.QueryRowContext(ctx, getRSSFeed, id)
	var i RssFeed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Type,
		&i.Enabled,
		&i.FetchIntervalMinutes,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRSSFeeds = `-- name: ListRSSFeeds :many
SELECT id, name, url, type, enabled, fetch_interval_minutes, last_fetched_at, created_at FROM rss_feeds ORDER BY name
`

func (q *Queries) ListRSSFeeds(ctx context.Context) ([]RssFeed, error) {
	rows, err := q.db.QueryContext(ctx, listRSSFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RssFeed{}
	for rows.Next() {
		var i RssFeed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Type,
			&i.Enabled,
			&i.FetchIntervalMinutes,
			&i.LastFetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRSSFeed = `-- name: UpdateRSSFeed :exec
UPDATE rss_feeds SET name = ?, url = ?, type = ?, enabled = ?, fetch_interval_minutes = ? WHERE id = ?
`

type UpdateRSSFeedParams struct {
	Name                 string `json:"name"`
	Url                  string `json:"url"`
	Type                 string `json:"type"`
	Enabled              int64  `json:"enabled"`
	FetchIntervalMinutes int64  `json:"fetch_interval_minutes"`
	ID                   string `json:"id"`
}

func (q *Queries) UpdateRSSFeed(ctx context.Context, arg UpdateRSSFeedParams) error {
	_, err := q.db.ExecContext(ctx, updateRSSFeed,
		arg.Name,
		arg.Url,
		arg.Type,
		arg.Enabled,
		arg.FetchIntervalMinutes,
		arg.ID,
	)
	return err
}

const updateRSSFeedLastFetched = `-- name: UpdateRSSFeedLastFetched :exec
UPDATE rss_feeds SET last_fetched_at = strftime('%Y-%m-%dT%H:%M:%SZ','now') WHERE id = ?
`

func (q *Queries) UpdateRSSFeedLastFetched(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateRSSFeedLastFetched, id)
	return err
}
