// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan_summaries.sql

package store

import (
	"context"
)

const completeScanSummary = `-- name: CompleteScanSummary :exec
UPDATE scan_summaries
SET completed_at    = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    files_found     = ?,
    files_unmatched = ?
WHERE id = ?
`

type CompleteScanSummaryParams struct {
	FilesFound     int64  `json:"files_found"`
	FilesUnmatched int64  `json:"files_unmatched"`
	ID             string `json:"id"`
}

func (q *Queries) CompleteScanSummary(ctx context.Context, arg CompleteScanSummaryParams) error {
	_, err := q.db.ExecContext(ctx, completeScanSummary, arg.FilesFound, arg.FilesUnmatched, arg.ID)
	return err
}

const createScanSummary = `-- name: CreateScanSummary :one
INSERT INTO scan_summaries (id, library_id)
VALUES (?, ?)
RETURNING id, library_id, started_at, completed_at, files_found, files_matched, files_unmatched, errors
`

type CreateScanSummaryParams struct {
	ID        string `json:"id"`
	LibraryID string `json:"library_id"`
}

func (q *Queries) CreateScanSummary(ctx context.Context, arg CreateScanSummaryParams) (ScanSummary, error) {
	row := q.db.QueryRowContext(ctx, createScanSummary, arg.ID, arg.LibraryID)
	var i ScanSummary
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FilesFound,
		&i.FilesMatched,
		&i.FilesUnmatched,
		&i.Errors,
	)
	return i, err
}

const listScanSummaries = `-- name: ListScanSummaries :many
SELECT id, library_id, started_at, completed_at, files_found, files_matched, files_unmatched, errors FROM scan_summaries
WHERE library_id = ?
ORDER BY started_at DESC
LIMIT 10
`

func (q *Queries) ListScanSummaries(ctx context.Context, libraryID string) ([]ScanSummary, error) {
	rows, err := q.db.QueryContext(ctx, listScanSummaries, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanSummary{}
	for rows.Next() {
		var i ScanSummary
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilesFound,
			&i.FilesMatched,
			&i.FilesUnmatched,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
