// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subtitle_files.sql

package store

import (
	"context"
)

const createSubtitleFile = `-- name: CreateSubtitleFile :one
INSERT INTO subtitle_files (id, media_file_id, path, language, format, source)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, media_file_id, path, language, format, source, created_at
`

type CreateSubtitleFileParams struct {
	ID          string `json:"id"`
	MediaFileID string `json:"media_file_id"`
	Path        string `json:"path"`
	Language    string `json:"language"`
	Format      string `json:"format"`
	Source      string `json:"source"`
}

func (q *Queries) CreateSubtitleFile(ctx context.Context, arg CreateSubtitleFileParams) (SubtitleFile, error) {
	row := q.db.QueryRowContext(ctx, createSubtitleFile,
		arg.ID,
		arg.MediaFileID,
		arg.Path,
		arg.Language,
		arg.Format,
		arg.Source,
	)
	var i SubtitleFile
	err := row.Scan(
		&i.ID,
		&i.MediaFileID,
		&i.Path,
		&i.Language,
		&i.Format,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubtitleFile = `-- name: DeleteSubtitleFile :exec
DELETE FROM subtitle_files WHERE id = ?
`

func (q *Queries) DeleteSubtitleFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSubtitleFile, id)
	return err
}

const getSubtitleFile = `-- name: GetSubtitleFile :one
SELECT id, media_file_id, path, language, format, source, created_at FROM subtitle_files WHERE id = ? LIMIT 1
`

func (q *Queries) GetSubtitleFile(ctx context.Context, id string) (SubtitleFile, error) {
	row := q.db.QueryRowContext(ctx, getSubtitleFile, id)
	var i SubtitleFile
	err := row.Scan(
		&i.ID,
		&i.MediaFileID,
		&i.Path,
		&i.Language,
		&i.Format,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listSubtitlePathsByMediaFile = `-- name: ListSubtitlePathsByMediaFile :many
SELECT path FROM subtitle_files WHERE media_file_id = ?
`

func (q *Queries) ListSubtitlePathsByMediaFile(ctx context.Context, mediaFileID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSubtitlePathsByMediaFile, mediaFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtitlesByMediaFile = `-- name: ListSubtitlesByMediaFile :many
SELECT id, media_file_id, path, language, format, source, created_at FROM subtitle_files WHERE media_file_id = ? ORDER BY language
`

func (q *Queries) ListSubtitlesByMediaFile(ctx context.Context, mediaFileID string) ([]SubtitleFile, error) {
	rows, err := q.db.QueryContext(ctx, listSubtitlesByMediaFile, mediaFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubtitleFile{}
	for rows.Next() {
		var i SubtitleFile
		if err := rows.Scan(
			&i.ID,
			&i.MediaFileID,
			&i.Path,
			&i.Language,
			&i.Format,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
