// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_state.sql

package store

import (
	"context"
	"database/sql"
)

const getSyncProviderState = `-- name: GetSyncProviderState :one
SELECT user_id, provider, pull_enabled, last_pulled_at FROM sync_provider_state WHERE user_id = ? AND provider = ? LIMIT 1
`

type GetSyncProviderStateParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetSyncProviderState(ctx context.Context, arg GetSyncProviderStateParams) (SyncProviderState, error) {
	row := q.db.QueryRowContext(ctx, getSyncProviderState, arg.UserID, arg.Provider)
	var i SyncProviderState
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.PullEnabled,
		&i.LastPulledAt,
	)
	return i, err
}

const listPullEnabledProviders = `-- name: ListPullEnabledProviders :many
SELECT user_id, provider FROM sync_provider_state WHERE pull_enabled = 1
`

type ListPullEnabledProvidersRow struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) ListPullEnabledProviders(ctx context.Context) ([]ListPullEnabledProvidersRow, error) {
	rows, err := q.db.QueryContext(ctx, listPullEnabledProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPullEnabledProvidersRow{}
	for rows.Next() {
		var i ListPullEnabledProvidersRow
		if err := rows.Scan(&i.UserID, &i.Provider); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPullEnabled = `-- name: SetPullEnabled :exec
INSERT INTO sync_provider_state (user_id, provider, pull_enabled)
VALUES (?, ?, ?)
ON CONFLICT(user_id, provider) DO UPDATE SET pull_enabled = excluded.pull_enabled
`

type SetPullEnabledParams struct {
	UserID      string `json:"user_id"`
	Provider    string `json:"provider"`
	PullEnabled int64  `json:"pull_enabled"`
}

func (q *Queries) SetPullEnabled(ctx context.Context, arg SetPullEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setPullEnabled, arg.UserID, arg.Provider, arg.PullEnabled)
	return err
}

const upsertSyncProviderState = `-- name: UpsertSyncProviderState :exec
INSERT INTO sync_provider_state (user_id, provider, pull_enabled, last_pulled_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, provider) DO UPDATE SET
    pull_enabled = excluded.pull_enabled,
    last_pulled_at = COALESCE(excluded.last_pulled_at, sync_provider_state.last_pulled_at)
`

type UpsertSyncProviderStateParams struct {
	UserID       string         `json:"user_id"`
	Provider     string         `json:"provider"`
	PullEnabled  int64          `json:"pull_enabled"`
	LastPulledAt sql.NullString `json:"last_pulled_at"`
}

func (q *Queries) UpsertSyncProviderState(ctx context.Context, arg UpsertSyncProviderStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncProviderState,
		arg.UserID,
		arg.Provider,
		arg.PullEnabled,
		arg.LastPulledAt,
	)
	return err
}
