// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_outbox.sql

package store

import (
	"context"
	"database/sql"
)

const countPendingSyncOpsByUserProvider = `-- name: CountPendingSyncOpsByUserProvider :one
SELECT COUNT(*) FROM sync_outbox
WHERE user_id = ? AND provider = ? AND completed_at IS NULL
`

type CountPendingSyncOpsByUserProviderParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) CountPendingSyncOpsByUserProvider(ctx context.Context, arg CountPendingSyncOpsByUserProviderParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingSyncOpsByUserProvider, arg.UserID, arg.Provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCompletedSyncOpsOlderThan = `-- name: DeleteCompletedSyncOpsOlderThan :exec
DELETE FROM sync_outbox WHERE completed_at IS NOT NULL AND completed_at < ?
`

func (q *Queries) DeleteCompletedSyncOpsOlderThan(ctx context.Context, completedAt sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteCompletedSyncOpsOlderThan, completedAt)
	return err
}

const enqueueSyncOp = `-- name: EnqueueSyncOp :exec
INSERT INTO sync_outbox (id, user_id, provider, anime_id, kind, payload, next_attempt_at)
VALUES (?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ','now'))
`

type EnqueueSyncOpParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
	AnimeID  string `json:"anime_id"`
	Kind     string `json:"kind"`
	Payload  string `json:"payload"`
}

func (q *Queries) EnqueueSyncOp(ctx context.Context, arg EnqueueSyncOpParams) error {
	_, err := q.db.ExecContext(ctx, enqueueSyncOp,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.AnimeID,
		arg.Kind,
		arg.Payload,
	)
	return err
}

const getLatestCompletedSyncOp = `-- name: GetLatestCompletedSyncOp :one
SELECT id, user_id, provider, anime_id, kind, payload, attempts, next_attempt_at, last_error, created_at, completed_at FROM sync_outbox
WHERE user_id = ? AND provider = ? AND completed_at IS NOT NULL AND last_error IS NULL
ORDER BY completed_at DESC LIMIT 1
`

type GetLatestCompletedSyncOpParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetLatestCompletedSyncOp(ctx context.Context, arg GetLatestCompletedSyncOpParams) (SyncOutbox, error) {
	row := q.db.QueryRowContext(ctx, getLatestCompletedSyncOp, arg.UserID, arg.Provider)
	var i SyncOutbox
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AnimeID,
		&i.Kind,
		&i.Payload,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listReadySyncOps = `-- name: ListReadySyncOps :many
SELECT id, user_id, provider, anime_id, kind, payload, attempts, next_attempt_at, last_error, created_at, completed_at FROM sync_outbox
WHERE completed_at IS NULL AND next_attempt_at <= strftime('%Y-%m-%dT%H:%M:%SZ','now')
ORDER BY next_attempt_at ASC
LIMIT ?
`

func (q *Queries) ListReadySyncOps(ctx context.Context, limit int64) ([]SyncOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listReadySyncOps, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncOutbox{}
	for rows.Next() {
		var i SyncOutbox
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.AnimeID,
			&i.Kind,
			&i.Payload,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSyncErrors = `-- name: ListRecentSyncErrors :many
SELECT id, user_id, provider, anime_id, kind, payload, attempts, next_attempt_at, last_error, created_at, completed_at FROM sync_outbox
WHERE user_id = ? AND provider = ? AND last_error IS NOT NULL
ORDER BY created_at DESC LIMIT 10
`

type ListRecentSyncErrorsParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) ListRecentSyncErrors(ctx context.Context, arg ListRecentSyncErrorsParams) ([]SyncOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSyncErrors, arg.UserID, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncOutbox{}
	for rows.Next() {
		var i SyncOutbox
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.AnimeID,
			&i.Kind,
			&i.Payload,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSyncOpCompleted = `-- name: MarkSyncOpCompleted :exec
UPDATE sync_outbox
SET completed_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?
`

func (q *Queries) MarkSyncOpCompleted(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markSyncOpCompleted, id)
	return err
}

const markUserProviderOpsFailed = `-- name: MarkUserProviderOpsFailed :exec
UPDATE sync_outbox
SET completed_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'), last_error = ?
WHERE user_id = ? AND provider = ? AND completed_at IS NULL
`

type MarkUserProviderOpsFailedParams struct {
	LastError sql.NullString `json:"last_error"`
	UserID    string         `json:"user_id"`
	Provider  string         `json:"provider"`
}

func (q *Queries) MarkUserProviderOpsFailed(ctx context.Context, arg MarkUserProviderOpsFailedParams) error {
	_, err := q.db.ExecContext(ctx, markUserProviderOpsFailed, arg.LastError, arg.UserID, arg.Provider)
	return err
}

const rescheduleSyncOp = `-- name: RescheduleSyncOp :exec
UPDATE sync_outbox
SET attempts = ?, next_attempt_at = ?, last_error = ?
WHERE id = ?
`

type RescheduleSyncOpParams struct {
	Attempts      int64          `json:"attempts"`
	NextAttemptAt string         `json:"next_attempt_at"`
	LastError     sql.NullString `json:"last_error"`
	ID            string         `json:"id"`
}

func (q *Queries) RescheduleSyncOp(ctx context.Context, arg RescheduleSyncOpParams) error {
	_, err := q.db.ExecContext(ctx, rescheduleSyncOp,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const supersedeProgressOps = `-- name: SupersedeProgressOps :exec
UPDATE sync_outbox
SET completed_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'), last_error = 'superseded'
WHERE user_id = ? AND provider = ? AND anime_id = ? AND kind = 'progress' AND completed_at IS NULL
`

type SupersedeProgressOpsParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
	AnimeID  string `json:"anime_id"`
}

func (q *Queries) SupersedeProgressOps(ctx context.Context, arg SupersedeProgressOpsParams) error {
	_, err := q.db.ExecContext(ctx, supersedeProgressOps, arg.UserID, arg.Provider, arg.AnimeID)
	return err
}
