// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transcode_sessions.sql

package store

import (
	"context"
	"database/sql"
)

const createTranscodeSession = `-- name: CreateTranscodeSession :one
INSERT INTO transcode_sessions (id, media_file_id, session_token, status, output_dir, codec, resolution, progress, expires_at)
VALUES (?, ?, ?, 'pending', ?, ?, ?, 0, ?)
RETURNING id, media_file_id, session_token, status, output_dir, codec, resolution, progress, expires_at, created_at
`

type CreateTranscodeSessionParams struct {
	ID           string         `json:"id"`
	MediaFileID  string         `json:"media_file_id"`
	SessionToken string         `json:"session_token"`
	OutputDir    string         `json:"output_dir"`
	Codec        sql.NullString `json:"codec"`
	Resolution   sql.NullString `json:"resolution"`
	ExpiresAt    string         `json:"expires_at"`
}

func (q *Queries) CreateTranscodeSession(ctx context.Context, arg CreateTranscodeSessionParams) (TranscodeSession, error) {
	row := q.db.QueryRowContext(ctx, createTranscodeSession,
		arg.ID,
		arg.MediaFileID,
		arg.SessionToken,
		arg.OutputDir,
		arg.Codec,
		arg.Resolution,
		arg.ExpiresAt,
	)
	var i TranscodeSession
	err := row.Scan(
		&i.ID,
		&i.MediaFileID,
		&i.SessionToken,
		&i.Status,
		&i.OutputDir,
		&i.Codec,
		&i.Resolution,
		&i.Progress,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTranscodeSession = `-- name: DeleteTranscodeSession :exec
DELETE FROM transcode_sessions WHERE session_token = ?
`

func (q *Queries) DeleteTranscodeSession(ctx context.Context, sessionToken string) error {
	_, err := q.db.ExecContext(ctx, deleteTranscodeSession, sessionToken)
	return err
}

const getTranscodeSession = `-- name: GetTranscodeSession :one
SELECT id, media_file_id, session_token, status, output_dir, codec, resolution, progress, expires_at, created_at FROM transcode_sessions WHERE session_token = ? LIMIT 1
`

func (q *Queries) GetTranscodeSession(ctx context.Context, sessionToken string) (TranscodeSession, error) {
	row := q.db.QueryRowContext(ctx, getTranscodeSession, sessionToken)
	var i TranscodeSession
	err := row.Scan(
		&i.ID,
		&i.MediaFileID,
		&i.SessionToken,
		&i.Status,
		&i.OutputDir,
		&i.Codec,
		&i.Resolution,
		&i.Progress,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTranscodeSessionsByFile = `-- name: ListTranscodeSessionsByFile :many
SELECT id, media_file_id, session_token, status, output_dir, codec, resolution, progress, expires_at, created_at FROM transcode_sessions WHERE media_file_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListTranscodeSessionsByFile(ctx context.Context, mediaFileID string) ([]TranscodeSession, error) {
	rows, err := q.db.QueryContext(ctx, listTranscodeSessionsByFile, mediaFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscodeSession{}
	for rows.Next() {
		var i TranscodeSession
		if err := rows.Scan(
			&i.ID,
			&i.MediaFileID,
			&i.SessionToken,
			&i.Status,
			&i.OutputDir,
			&i.Codec,
			&i.Resolution,
			&i.Progress,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTranscodeSessionStatus = `-- name: UpdateTranscodeSessionStatus :exec
UPDATE transcode_sessions SET status = ?, progress = ? WHERE session_token = ?
`

type UpdateTranscodeSessionStatusParams struct {
	Status       string `json:"status"`
	Progress     int64  `json:"progress"`
	SessionToken string `json:"session_token"`
}

func (q *Queries) UpdateTranscodeSessionStatus(ctx context.Context, arg UpdateTranscodeSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTranscodeSessionStatus, arg.Status, arg.Progress, arg.SessionToken)
	return err
}
