// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watch_progress.sql

package store

import (
	"context"
	"database/sql"
)

const getWatchProgress = `-- name: GetWatchProgress :one
SELECT id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at, bangumi_synced_at, mal_synced_at, anilist_synced_at FROM watch_progress WHERE user_id = ? AND episode_id = ? LIMIT 1
`

type GetWatchProgressParams struct {
	UserID    string `json:"user_id"`
	EpisodeID string `json:"episode_id"`
}

func (q *Queries) GetWatchProgress(ctx context.Context, arg GetWatchProgressParams) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, getWatchProgress, arg.UserID, arg.EpisodeID)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.MediaFileID,
		&i.PositionSeconds,
		&i.DurationSeconds,
		&i.Completed,
		&i.LastWatchedAt,
		&i.BangumiSyncedAt,
		&i.MalSyncedAt,
		&i.AnilistSyncedAt,
	)
	return i, err
}

const getWatchProgressByMediaFile = `-- name: GetWatchProgressByMediaFile :one
SELECT id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at, bangumi_synced_at, mal_synced_at, anilist_synced_at FROM watch_progress WHERE user_id = ? AND media_file_id = ? LIMIT 1
`

type GetWatchProgressByMediaFileParams struct {
	UserID      string         `json:"user_id"`
	MediaFileID sql.NullString `json:"media_file_id"`
}

func (q *Queries) GetWatchProgressByMediaFile(ctx context.Context, arg GetWatchProgressByMediaFileParams) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, getWatchProgressByMediaFile, arg.UserID, arg.MediaFileID)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.MediaFileID,
		&i.PositionSeconds,
		&i.DurationSeconds,
		&i.Completed,
		&i.LastWatchedAt,
		&i.BangumiSyncedAt,
		&i.MalSyncedAt,
		&i.AnilistSyncedAt,
	)
	return i, err
}

const listCompletedWatchProgress = `-- name: ListCompletedWatchProgress :many
SELECT id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at, bangumi_synced_at, mal_synced_at, anilist_synced_at FROM watch_progress WHERE user_id = ? AND completed = 1 ORDER BY last_watched_at DESC
`

func (q *Queries) ListCompletedWatchProgress(ctx context.Context, userID string) ([]WatchProgress, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedWatchProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchProgress{}
	for rows.Next() {
		var i WatchProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.MediaFileID,
			&i.PositionSeconds,
			&i.DurationSeconds,
			&i.Completed,
			&i.LastWatchedAt,
			&i.BangumiSyncedAt,
			&i.MalSyncedAt,
			&i.AnilistSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentProgressWithAnime = `-- name: ListRecentProgressWithAnime :many
WITH ranked AS (
    SELECT
        wp.id, wp.user_id, wp.episode_id, wp.media_file_id,
        wp.position_seconds, wp.duration_seconds, wp.completed, wp.last_watched_at,
        e.anime_id, e.episode_number,
        a.bangumi_id,
        ROW_NUMBER() OVER (PARTITION BY COALESCE(a.bangumi_id, a.id) ORDER BY wp.last_watched_at DESC) AS rn
    FROM watch_progress wp
    JOIN episodes e ON e.id = wp.episode_id
    JOIN anime a ON a.id = e.anime_id
    WHERE wp.user_id = ?
)
SELECT
    r.id, r.user_id, r.episode_id, r.media_file_id,
    r.position_seconds, r.duration_seconds, r.completed, r.last_watched_at,
    a.id AS anime_id, a.title AS anime_title, a.title_zh AS anime_title_zh,
    a.cover_image_url AS anime_cover_image_url, a.bangumi_id AS anime_bangumi_id,
    r.episode_number
FROM ranked r
JOIN anime a ON a.id = r.anime_id
WHERE r.rn = 1
ORDER BY r.last_watched_at DESC
LIMIT 20
`

type ListRecentProgressWithAnimeRow struct {
	ID                 string         `json:"id"`
	UserID             string         `json:"user_id"`
	EpisodeID          string         `json:"episode_id"`
	MediaFileID        sql.NullString `json:"media_file_id"`
	PositionSeconds    int64          `json:"position_seconds"`
	DurationSeconds    sql.NullInt64  `json:"duration_seconds"`
	Completed          int64          `json:"completed"`
	LastWatchedAt      string         `json:"last_watched_at"`
	AnimeID            string         `json:"anime_id"`
	AnimeTitle         string         `json:"anime_title"`
	AnimeTitleZh       sql.NullString `json:"anime_title_zh"`
	AnimeCoverImageUrl sql.NullString `json:"anime_cover_image_url"`
	AnimeBangumiID     sql.NullInt64  `json:"anime_bangumi_id"`
	EpisodeNumber      float64        `json:"episode_number"`
}

func (q *Queries) ListRecentProgressWithAnime(ctx context.Context, userID string) ([]ListRecentProgressWithAnimeRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentProgressWithAnime, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentProgressWithAnimeRow{}
	for rows.Next() {
		var i ListRecentProgressWithAnimeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.MediaFileID,
			&i.PositionSeconds,
			&i.DurationSeconds,
			&i.Completed,
			&i.LastWatchedAt,
			&i.AnimeID,
			&i.AnimeTitle,
			&i.AnimeTitleZh,
			&i.AnimeCoverImageUrl,
			&i.AnimeBangumiID,
			&i.EpisodeNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchProgressByUser = `-- name: ListWatchProgressByUser :many
SELECT id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at, bangumi_synced_at, mal_synced_at, anilist_synced_at FROM watch_progress WHERE user_id = ? ORDER BY last_watched_at DESC LIMIT 20
`

func (q *Queries) ListWatchProgressByUser(ctx context.Context, userID string) ([]WatchProgress, error) {
	rows, err := q.db.QueryContext(ctx, listWatchProgressByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchProgress{}
	for rows.Next() {
		var i WatchProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.MediaFileID,
			&i.PositionSeconds,
			&i.DurationSeconds,
			&i.Completed,
			&i.LastWatchedAt,
			&i.BangumiSyncedAt,
			&i.MalSyncedAt,
			&i.AnilistSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWatchProgress = `-- name: UpsertWatchProgress :one
INSERT INTO watch_progress (id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at)
VALUES (?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
ON CONFLICT(user_id, episode_id) DO UPDATE SET
    position_seconds = excluded.position_seconds,
    duration_seconds = excluded.duration_seconds,
    completed = excluded.completed,
    media_file_id = excluded.media_file_id,
    last_watched_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at, bangumi_synced_at, mal_synced_at, anilist_synced_at
`

type UpsertWatchProgressParams struct {
	ID              string         `json:"id"`
	UserID          string         `json:"user_id"`
	EpisodeID       string         `json:"episode_id"`
	MediaFileID     sql.NullString `json:"media_file_id"`
	PositionSeconds int64          `json:"position_seconds"`
	DurationSeconds sql.NullInt64  `json:"duration_seconds"`
	Completed       int64          `json:"completed"`
}

func (q *Queries) UpsertWatchProgress(ctx context.Context, arg UpsertWatchProgressParams) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, upsertWatchProgress,
		arg.ID,
		arg.UserID,
		arg.EpisodeID,
		arg.MediaFileID,
		arg.PositionSeconds,
		arg.DurationSeconds,
		arg.Completed,
	)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.MediaFileID,
		&i.PositionSeconds,
		&i.DurationSeconds,
		&i.Completed,
		&i.LastWatchedAt,
		&i.BangumiSyncedAt,
		&i.MalSyncedAt,
		&i.AnilistSyncedAt,
	)
	return i, err
}
