// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watch_progress.sql

package store

import (
	"context"
	"database/sql"
	"strings"
)

const batchDeleteWatchProgress = `-- name: BatchDeleteWatchProgress :execrows
DELETE FROM watch_progress
WHERE user_id = ?1 AND id IN (/*SLICE:ids*/?)
`

type BatchDeleteWatchProgressParams struct {
	UserID string   `json:"user_id"`
	Ids    []string `json:"ids"`
}

func (q *Queries) BatchDeleteWatchProgress(ctx context.Context, arg BatchDeleteWatchProgressParams) (int64, error) {
	query := batchDeleteWatchProgress
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countCompletedWatchProgressByAnime = `-- name: CountCompletedWatchProgressByAnime :one
SELECT
    COALESCE(SUM(CASE WHEN wp.completed = 1 THEN 1 ELSE 0 END), 0) AS completed_count,
    COALESCE(MAX(wp.last_watched_at), '') AS last_played_at,
    COALESCE(MAX(CASE WHEN wp.completed = 1 THEN wp.last_watched_at END), '') AS series_completed_at
FROM watch_progress wp
JOIN episodes e ON e.id = wp.episode_id
WHERE wp.user_id = ?1 AND e.anime_id = ?2
`

type CountCompletedWatchProgressByAnimeParams struct {
	UserID  string `json:"user_id"`
	AnimeID string `json:"anime_id"`
}

type CountCompletedWatchProgressByAnimeRow struct {
	CompletedCount    interface{} `json:"completed_count"`
	LastPlayedAt      interface{} `json:"last_played_at"`
	SeriesCompletedAt interface{} `json:"series_completed_at"`
}

func (q *Queries) CountCompletedWatchProgressByAnime(ctx context.Context, arg CountCompletedWatchProgressByAnimeParams) (CountCompletedWatchProgressByAnimeRow, error) {
	row := q.db.QueryRowContext(ctx, countCompletedWatchProgressByAnime, arg.UserID, arg.AnimeID)
	var i CountCompletedWatchProgressByAnimeRow
	err := row.Scan(&i.CompletedCount, &i.LastPlayedAt, &i.SeriesCompletedAt)
	return i, err
}

const deleteAllWatchProgressByUser = `-- name: DeleteAllWatchProgressByUser :execrows
DELETE FROM watch_progress WHERE user_id = ?1
`

func (q *Queries) DeleteAllWatchProgressByUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllWatchProgressByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWatchProgress = `-- name: DeleteWatchProgress :execrows
DELETE FROM watch_progress
WHERE id = ?1 AND user_id = ?2
`

type DeleteWatchProgressParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteWatchProgress(ctx context.Context, arg DeleteWatchProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWatchProgress, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWatchProgress = `-- name: GetWatchProgress :one
SELECT id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at, bangumi_synced_at, mal_synced_at, anilist_synced_at FROM watch_progress WHERE user_id = ? AND episode_id = ? LIMIT 1
`

type GetWatchProgressParams struct {
	UserID    string `json:"user_id"`
	EpisodeID string `json:"episode_id"`
}

func (q *Queries) GetWatchProgress(ctx context.Context, arg GetWatchProgressParams) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, getWatchProgress, arg.UserID, arg.EpisodeID)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.MediaFileID,
		&i.PositionSeconds,
		&i.DurationSeconds,
		&i.Completed,
		&i.LastWatchedAt,
		&i.BangumiSyncedAt,
		&i.MalSyncedAt,
		&i.AnilistSyncedAt,
	)
	return i, err
}

const getWatchProgressByMediaFile = `-- name: GetWatchProgressByMediaFile :one
SELECT id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at, bangumi_synced_at, mal_synced_at, anilist_synced_at FROM watch_progress WHERE user_id = ? AND media_file_id = ? LIMIT 1
`

type GetWatchProgressByMediaFileParams struct {
	UserID      string         `json:"user_id"`
	MediaFileID sql.NullString `json:"media_file_id"`
}

func (q *Queries) GetWatchProgressByMediaFile(ctx context.Context, arg GetWatchProgressByMediaFileParams) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, getWatchProgressByMediaFile, arg.UserID, arg.MediaFileID)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.MediaFileID,
		&i.PositionSeconds,
		&i.DurationSeconds,
		&i.Completed,
		&i.LastWatchedAt,
		&i.BangumiSyncedAt,
		&i.MalSyncedAt,
		&i.AnilistSyncedAt,
	)
	return i, err
}

const hasAnyWatchProgress = `-- name: HasAnyWatchProgress :one
SELECT EXISTS(
    SELECT 1 FROM watch_progress wp
    JOIN episodes e ON e.id = wp.episode_id
    WHERE wp.user_id = ?1 AND e.anime_id = ?2
) AS has_progress
`

type HasAnyWatchProgressParams struct {
	UserID  string `json:"user_id"`
	AnimeID string `json:"anime_id"`
}

func (q *Queries) HasAnyWatchProgress(ctx context.Context, arg HasAnyWatchProgressParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasAnyWatchProgress, arg.UserID, arg.AnimeID)
	var has_progress int64
	err := row.Scan(&has_progress)
	return has_progress, err
}

const listBangumiEpisodeIDsForAnimeWatchedByUser = `-- name: ListBangumiEpisodeIDsForAnimeWatchedByUser :many
SELECT e.bangumi_episode_id
FROM episodes e
JOIN watch_progress wp ON wp.episode_id = e.id
WHERE e.anime_id = ?1
  AND wp.user_id = ?2
  AND wp.completed = 1
  AND e.bangumi_episode_id IS NOT NULL
`

type ListBangumiEpisodeIDsForAnimeWatchedByUserParams struct {
	AnimeID string `json:"anime_id"`
	UserID  string `json:"user_id"`
}

// C4 fix: list Bangumi episode IDs for all completed episodes of this anime.
func (q *Queries) ListBangumiEpisodeIDsForAnimeWatchedByUser(ctx context.Context, arg ListBangumiEpisodeIDsForAnimeWatchedByUserParams) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, listBangumiEpisodeIDsForAnimeWatchedByUser, arg.AnimeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var bangumi_episode_id sql.NullInt64
		if err := rows.Scan(&bangumi_episode_id); err != nil {
			return nil, err
		}
		items = append(items, bangumi_episode_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedWatchProgress = `-- name: ListCompletedWatchProgress :many
SELECT id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at, bangumi_synced_at, mal_synced_at, anilist_synced_at FROM watch_progress WHERE user_id = ? AND completed = 1 ORDER BY last_watched_at DESC
`

func (q *Queries) ListCompletedWatchProgress(ctx context.Context, userID string) ([]WatchProgress, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedWatchProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchProgress{}
	for rows.Next() {
		var i WatchProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.MediaFileID,
			&i.PositionSeconds,
			&i.DurationSeconds,
			&i.Completed,
			&i.LastWatchedAt,
			&i.BangumiSyncedAt,
			&i.MalSyncedAt,
			&i.AnilistSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryWithAnime = `-- name: ListHistoryWithAnime :many
SELECT
    wp.id, wp.user_id, wp.episode_id, wp.media_file_id,
    wp.position_seconds, wp.duration_seconds, wp.completed, wp.last_watched_at,
    a.id AS anime_id, a.title AS anime_title, a.title_zh AS anime_title_zh,
    a.cover_image_url AS anime_cover_image_url, a.bangumi_id AS anime_bangumi_id,
    e.episode_number
FROM watch_progress wp
JOIN episodes e ON e.id = wp.episode_id
JOIN anime a ON a.id = e.anime_id
WHERE wp.user_id = ?1
  AND (?2 = '' OR wp.last_watched_at < ?2)
  AND (
    ?3 = 'all'
    OR (?3 = 'completed' AND wp.completed = 1)
    OR (?3 = 'in_progress' AND wp.completed = 0)
  )
  AND (
    ?4 = ''
    OR LOWER(a.title) LIKE LOWER('%' || ?4 || '%')
    OR LOWER(COALESCE(a.title_zh, '')) LIKE LOWER('%' || ?4 || '%')
  )
ORDER BY wp.last_watched_at DESC, wp.id DESC
LIMIT ?5
`

type ListHistoryWithAnimeParams struct {
	UserID string      `json:"user_id"`
	Before interface{} `json:"before"`
	Filter interface{} `json:"filter"`
	Q      interface{} `json:"q"`
	Lim    int64       `json:"lim"`
}

type ListHistoryWithAnimeRow struct {
	ID                 string         `json:"id"`
	UserID             string         `json:"user_id"`
	EpisodeID          string         `json:"episode_id"`
	MediaFileID        sql.NullString `json:"media_file_id"`
	PositionSeconds    int64          `json:"position_seconds"`
	DurationSeconds    sql.NullInt64  `json:"duration_seconds"`
	Completed          int64          `json:"completed"`
	LastWatchedAt      string         `json:"last_watched_at"`
	AnimeID            string         `json:"anime_id"`
	AnimeTitle         string         `json:"anime_title"`
	AnimeTitleZh       sql.NullString `json:"anime_title_zh"`
	AnimeCoverImageUrl sql.NullString `json:"anime_cover_image_url"`
	AnimeBangumiID     sql.NullInt64  `json:"anime_bangumi_id"`
	EpisodeNumber      float64        `json:"episode_number"`
}

// Paginated, filterable list of watch progress enriched with anime + episode.
// No per-anime dedup: every watch_progress row is returned (one per episode).
// Cursor pagination on (last_watched_at DESC, id DESC).
// When 'before' is empty string, no cursor is applied (first page).
// When 'q' is empty string, no search filter is applied.
func (q *Queries) ListHistoryWithAnime(ctx context.Context, arg ListHistoryWithAnimeParams) ([]ListHistoryWithAnimeRow, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryWithAnime,
		arg.UserID,
		arg.Before,
		arg.Filter,
		arg.Q,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHistoryWithAnimeRow{}
	for rows.Next() {
		var i ListHistoryWithAnimeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.MediaFileID,
			&i.PositionSeconds,
			&i.DurationSeconds,
			&i.Completed,
			&i.LastWatchedAt,
			&i.AnimeID,
			&i.AnimeTitle,
			&i.AnimeTitleZh,
			&i.AnimeCoverImageUrl,
			&i.AnimeBangumiID,
			&i.EpisodeNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentProgressWithAnime = `-- name: ListRecentProgressWithAnime :many
WITH ranked AS (
    SELECT
        wp.id, wp.user_id, wp.episode_id, wp.media_file_id,
        wp.position_seconds, wp.duration_seconds, wp.completed, wp.last_watched_at,
        e.anime_id, e.episode_number,
        a.bangumi_id,
        ROW_NUMBER() OVER (PARTITION BY COALESCE(a.bangumi_id, a.id) ORDER BY wp.last_watched_at DESC) AS rn
    FROM watch_progress wp
    JOIN episodes e ON e.id = wp.episode_id
    JOIN anime a ON a.id = e.anime_id
    WHERE wp.user_id = ?
)
SELECT
    r.id, r.user_id, r.episode_id, r.media_file_id,
    r.position_seconds, r.duration_seconds, r.completed, r.last_watched_at,
    a.id AS anime_id, a.title AS anime_title, a.title_zh AS anime_title_zh,
    a.cover_image_url AS anime_cover_image_url, a.bangumi_id AS anime_bangumi_id,
    r.episode_number
FROM ranked r
JOIN anime a ON a.id = r.anime_id
WHERE r.rn = 1
ORDER BY r.last_watched_at DESC
LIMIT 20
`

type ListRecentProgressWithAnimeRow struct {
	ID                 string         `json:"id"`
	UserID             string         `json:"user_id"`
	EpisodeID          string         `json:"episode_id"`
	MediaFileID        sql.NullString `json:"media_file_id"`
	PositionSeconds    int64          `json:"position_seconds"`
	DurationSeconds    sql.NullInt64  `json:"duration_seconds"`
	Completed          int64          `json:"completed"`
	LastWatchedAt      string         `json:"last_watched_at"`
	AnimeID            string         `json:"anime_id"`
	AnimeTitle         string         `json:"anime_title"`
	AnimeTitleZh       sql.NullString `json:"anime_title_zh"`
	AnimeCoverImageUrl sql.NullString `json:"anime_cover_image_url"`
	AnimeBangumiID     sql.NullInt64  `json:"anime_bangumi_id"`
	EpisodeNumber      float64        `json:"episode_number"`
}

func (q *Queries) ListRecentProgressWithAnime(ctx context.Context, userID string) ([]ListRecentProgressWithAnimeRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentProgressWithAnime, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentProgressWithAnimeRow{}
	for rows.Next() {
		var i ListRecentProgressWithAnimeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.MediaFileID,
			&i.PositionSeconds,
			&i.DurationSeconds,
			&i.Completed,
			&i.LastWatchedAt,
			&i.AnimeID,
			&i.AnimeTitle,
			&i.AnimeTitleZh,
			&i.AnimeCoverImageUrl,
			&i.AnimeBangumiID,
			&i.EpisodeNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchProgressByUser = `-- name: ListWatchProgressByUser :many
SELECT id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at, bangumi_synced_at, mal_synced_at, anilist_synced_at FROM watch_progress WHERE user_id = ? ORDER BY last_watched_at DESC LIMIT 20
`

func (q *Queries) ListWatchProgressByUser(ctx context.Context, userID string) ([]WatchProgress, error) {
	rows, err := q.db.QueryContext(ctx, listWatchProgressByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchProgress{}
	for rows.Next() {
		var i WatchProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.MediaFileID,
			&i.PositionSeconds,
			&i.DurationSeconds,
			&i.Completed,
			&i.LastWatchedAt,
			&i.BangumiSyncedAt,
			&i.MalSyncedAt,
			&i.AnilistSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWatchProgress = `-- name: UpsertWatchProgress :one
INSERT INTO watch_progress (id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at)
VALUES (?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
ON CONFLICT(user_id, episode_id) DO UPDATE SET
    position_seconds = excluded.position_seconds,
    duration_seconds = excluded.duration_seconds,
    completed = excluded.completed,
    media_file_id = excluded.media_file_id,
    last_watched_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, user_id, episode_id, media_file_id, position_seconds, duration_seconds, completed, last_watched_at, bangumi_synced_at, mal_synced_at, anilist_synced_at
`

type UpsertWatchProgressParams struct {
	ID              string         `json:"id"`
	UserID          string         `json:"user_id"`
	EpisodeID       string         `json:"episode_id"`
	MediaFileID     sql.NullString `json:"media_file_id"`
	PositionSeconds int64          `json:"position_seconds"`
	DurationSeconds sql.NullInt64  `json:"duration_seconds"`
	Completed       int64          `json:"completed"`
}

func (q *Queries) UpsertWatchProgress(ctx context.Context, arg UpsertWatchProgressParams) (WatchProgress, error) {
	row := q.db.QueryRowContext(ctx, upsertWatchProgress,
		arg.ID,
		arg.UserID,
		arg.EpisodeID,
		arg.MediaFileID,
		arg.PositionSeconds,
		arg.DurationSeconds,
		arg.Completed,
	)
	var i WatchProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.MediaFileID,
		&i.PositionSeconds,
		&i.DurationSeconds,
		&i.Completed,
		&i.LastWatchedAt,
		&i.BangumiSyncedAt,
		&i.MalSyncedAt,
		&i.AnilistSyncedAt,
	)
	return i, err
}
