services:
  redis:
    image: redis:alpine
    container_name: milmil-redis
    ports:
      - "6379:6379"
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis-config/redis.conf:/etc/redis/redis.conf:ro
      - ./redis-config/users.acl:/etc/redis/users.acl:ro
      - redis_data:/data
    env_file:
      - ./api/.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'redis-cli --user "$${REDIS_USERNAME}" --pass "$${REDIS_PASSWORD}" ping | grep -q PONG',
        ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
