/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RssRouteImport } from './routes/rss'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibrariesRouteImport } from './routes/libraries'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchFileIdRouteImport } from './routes/watch.$fileId'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RssRoute = RssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesRoute = LibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchFileIdRoute = WatchFileIdRouteImport.update({
  id: '/watch/$fileId',
  path: '/watch/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/libraries': typeof LibrariesRoute
  '/login': typeof LoginRoute
  '/rss': typeof RssRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/trending': typeof TrendingRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$fileId': typeof WatchFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/libraries': typeof LibrariesRoute
  '/login': typeof LoginRoute
  '/rss': typeof RssRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/trending': typeof TrendingRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$fileId': typeof WatchFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/libraries': typeof LibrariesRoute
  '/login': typeof LoginRoute
  '/rss': typeof RssRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/trending': typeof TrendingRoute
  '/anime/$id': typeof AnimeIdRoute
  '/watch/$fileId': typeof WatchFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/libraries'
    | '/login'
    | '/rss'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/setup'
    | '/trending'
    | '/anime/$id'
    | '/watch/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/libraries'
    | '/login'
    | '/rss'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/setup'
    | '/trending'
    | '/anime/$id'
    | '/watch/$fileId'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/libraries'
    | '/login'
    | '/rss'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/setup'
    | '/trending'
    | '/anime/$id'
    | '/watch/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  LibrariesRoute: typeof LibrariesRoute
  LoginRoute: typeof LoginRoute
  RssRoute: typeof RssRoute
  ScheduleRoute: typeof ScheduleRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TrendingRoute: typeof TrendingRoute
  AnimeIdRoute: typeof AnimeIdRoute
  WatchFileIdRoute: typeof WatchFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss': {
      id: '/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof RssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries': {
      id: '/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$fileId': {
      id: '/watch/$fileId'
      path: '/watch/$fileId'
      fullPath: '/watch/$fileId'
      preLoaderRoute: typeof WatchFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  LibrariesRoute: LibrariesRoute,
  LoginRoute: LoginRoute,
  RssRoute: RssRoute,
  ScheduleRoute: ScheduleRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TrendingRoute: TrendingRoute,
  AnimeIdRoute: AnimeIdRoute,
  WatchFileIdRoute: WatchFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
